import { images } from "@/lib/images";

export const dealCategories = [
  "Package Deals",
  "Accommodation",
  "Experiences",
] as const;

export type DealCategory = (typeof dealCategories)[number];

/** URL slugs for deals hub categories */
export const dealCategorySlugs: Record<DealCategory, string> = {
  "Package Deals": "package-deals",
  Accommodation: "accommodation",
  Experiences: "experiences",
};

export const slugToCategory: Record<string, DealCategory> = {
  "package-deals": "Package Deals",
  accommodation: "Accommodation",
  experiences: "Experiences",
};

export type DealCtaVariant = "viewPackage" | "checkAvailability" | "bookNow";

export type DealUrgencyKind =
  | "bookBefore"
  | "limitedTime"
  | "limitedAvailability"
  | "spotsLeft"
  | "mostPopular"
  | "popularThisWeek"
  | "trendingPackage";

export type DealPackageTag =
  | "luxuryEscape"
  | "familyFavourite"
  | "mostBooked"
  | "bestSeller"
  | "honeymoonCollection"
  | "limitedTimeOffer"
  | "exclusiveDeal";

export type DealInclusionKind =
  | "flightsIncluded"
  | "airportTransfersIncluded"
  | "breakfastIncluded"
  | "allInclusive"
  | "kidsStayFree"
  | "kidsEatFree"
  | "complimentaryActivities"
  | "freeExcursions"
  | "familyPackage"
  | "honeymoonPackage"
  | "luxuryCollection";

export interface DealValueBlock {
  bonusValue?: string;
  resortCredit?: string;
  includedTours?: string[];
  includedExperiences?: string[];
  includedTransportation?: string[];
}

export type DealTrustKind =
  | "verifiedPartner"
  | "verifiedResort"
  | "bestSeller"
  | "highlyRated";

export interface DealPackageDetail {
  overview?: string;
  exclusions?: string[];
  travelDates?: string;
  roomTypes?: string[];
  activities?: string[];
  transportation?: string[];
  highlights?: string[];
  faqs?: Array<{ question: string; answer: string }>;
}

export interface FijiDeal {
  slug: string;
  title: string;
  description: string;
  location: string;
  price: string;
  priceNote?: string;
  image: string;
  category: DealCategory;
  featured?: boolean;
  includes?: string[];
  /** Commercial booking metadata — optional; richest on Package Deals */
  destination?: string;
  resortName?: string;
  duration?: string;
  travelDates?: string;
  bookBeforeDate?: string;
  nights?: number;
  transfersIncluded?: boolean;
  flightsIncluded?: boolean;
  breakfastIncluded?: boolean;
  allInclusive?: boolean;
  kidsStayFree?: boolean;
  kidsEatFree?: boolean;
  familyPackage?: boolean;
  honeymoonPackage?: boolean;
  luxuryCollection?: boolean;
  freeCancellation?: boolean;
  instantConfirmation?: boolean;
  travelWindow?: string;
  urgency?: DealUrgencyKind;
  bookBefore?: string;
  spotsLeft?: number;
  packageTags?: DealPackageTag[];
  verifiedSupplier?: boolean;
  trustTags?: DealTrustKind[];
  rating?: number;
  reviewCount?: number;
  originalPrice?: string;
  discountLabel?: string;
  resortCredit?: string;
  bonusValue?: string;
  valueBlock?: DealValueBlock;
  complimentaryActivities?: string;
  complimentaryTransfers?: boolean;
  freeExcursions?: string;
  highlights?: string[];
  packageDetail?: DealPackageDetail;
  ctaPrimary?: DealCtaVariant;
  ctaSecondary?: DealCtaVariant;
}

export const deals: FijiDeal[] = [
  {
    slug: "denarau-resort-package",
    title: "Denarau Island Resort Package",
    description:
      "Ocean-view suite with return flights, private Denarau transfers, daily breakfast and FJD 500 resort credit.",
    location: "Denarau Island",
    destination: "Denarau Island",
    resortName: "InterContinental Fiji",
    duration: "5 nights",
    travelDates: "Travel 1 Oct 2025 – 31 May 2026",
    bookBeforeDate: "30 Jun 2026",
    price: "FJD 2,199",
    priceNote: "per person",
    image: images.resortIntercontinental,
    category: "Package Deals",
    featured: true,
    includes: ["Return flights", "Ocean-view suite", "Daily breakfast"],
    nights: 5,
    transfersIncluded: true,
    flightsIncluded: true,
    freeCancellation: true,
    instantConfirmation: true,
    travelWindow: "Travel Oct 2025 – May 2026",
    urgency: "bookBefore",
    bookBefore: "30 Jun 2026",
    verifiedSupplier: true,
    rating: 4.9,
    reviewCount: 218,
    originalPrice: "FJD 2,699",
    discountLabel: "Save 19%",
    resortCredit: "FJD 500 resort credit",
    breakfastIncluded: true,
    luxuryCollection: true,
    trustTags: ["verifiedResort", "bestSeller"],
    packageTags: ["luxuryEscape", "bestSeller", "exclusiveDeal"],
    valueBlock: {
      resortCredit: "FJD 500 resort credit",
      includedTransportation: ["Return flights Nadi–Denarau", "Private airport & marina transfers"],
      includedExperiences: ["Sunset harbour cruise", "Natadola Beach day pass"],
    },
    highlights: [
      "Ocean-view suite with private balcony",
      "FJD 500 resort credit for spa & dining",
      "Return Nadi–Denarau flights included",
    ],
    packageDetail: {
      overview:
        "A flagship Denarau escape pairing return flights, private transfers and five nights in an ocean-view suite — with daily breakfast and generous resort credit for spa rituals or waterfront dining.",
      travelDates: "Travel 1 Oct 2025 – 31 May 2026",
      roomTypes: ["Ocean-view suite", "Premium ocean suite (upgrade)"],
      activities: ["Sunset harbour cruise", "Natadola Beach day pass", "Spa credit eligible treatments"],
      transportation: ["Return flights Nadi–Denarau", "Private airport & marina transfers"],
      exclusions: ["Travel insurance", "Meals beyond breakfast unless using resort credit"],
      highlights: [
        "Ocean-view suite with private balcony",
        "FJD 500 resort credit for spa & dining",
        "Return Nadi–Denarau flights included",
      ],
      faqs: [
        {
          question: "Are flights from Australia included?",
          answer:
            "International flights can be bundled on request. This package includes return domestic flights between Nadi and Denarau.",
        },
        {
          question: "How is resort credit applied?",
          answer:
            "Credit is applied to your folio at checkout for eligible spa, dining and activity charges during your stay.",
        },
      ],
    },
  },
  {
    slug: "romantic-honeymoon-escape",
    title: "Likuliku Overwater Honeymoon",
    description:
      "Adults-only overwater bure with champagne arrival, couples spa ritual and private sandbank dinner.",
    location: "Mamanuca Islands",
    destination: "Mamanuca Islands",
    resortName: "Likuliku Lagoon Resort",
    duration: "4 nights",
    travelDates: "Valid year-round; peak demand Dec–Apr",
    price: "FJD 3,450",
    priceNote: "per couple",
    image: images.dealLikuliku,
    category: "Package Deals",
    includes: ["Overwater bure", "Couples spa", "Sandbank dinner"],
    nights: 4,
    transfersIncluded: true,
    flightsIncluded: false,
    freeCancellation: true,
    instantConfirmation: true,
    travelWindow: "Travel year-round",
    urgency: "trendingPackage",
    honeymoonPackage: true,
    luxuryCollection: true,
    verifiedSupplier: true,
    trustTags: ["verifiedResort", "highlyRated"],
    packageTags: ["honeymoonCollection", "luxuryEscape", "mostBooked"],
    valueBlock: {
      bonusValue: "FJD 1,200 bonus inclusions",
      includedExperiences: ["Sunset sailing", "Couples spa ritual"],
      includedTransportation: ["Return boat transfers from Denarau Marina"],
    },
    rating: 4.95,
    reviewCount: 96,
    bonusValue: "FJD 1,200 bonus inclusions",
    complimentaryActivities: "Sunset sailing & couples spa ritual",
    highlights: [
      "Adults-only overwater bure",
      "Champagne arrival & sandbank dinner",
      "Private Mamanuca boat transfers",
    ],
    packageDetail: {
      overview:
        "Fiji's most coveted adults-only overwater experience — champagne on arrival, a couples spa ritual and a private sandbank dinner crafted for honeymoons and milestone celebrations.",
      travelDates: "Valid year-round; peak demand Dec–Apr",
      roomTypes: ["Overwater bure", "Beachfront bure (on request)"],
      activities: ["Couples spa ritual", "Sunset sailing", "Private sandbank dinner"],
      transportation: ["Return boat transfers from Denarau Marina"],
      exclusions: ["International flights", "Premium spirits beyond house selection"],
      highlights: [
        "Adults-only overwater bure",
        "Champagne arrival & sandbank dinner",
        "Private Mamanuca boat transfers",
      ],
      faqs: [
        {
          question: "Is this package adults-only?",
          answer: "Yes — Likuliku Lagoon is an adults-only sanctuary designed for couples.",
        },
      ],
    },
  },
  {
    slug: "mamanuca-island-escape",
    title: "Mamanuca Island Escape",
    description:
      "Return seaplane transfers, beachfront villa and daily snorkelling with FJD 350 activity credit.",
    location: "Mamanuca Islands",
    destination: "Mamanuca Islands",
    resortName: "Treasure Island Resort",
    duration: "3 nights",
    travelDates: "Travel 1 Apr – 30 Nov 2026",
    price: "FJD 1,850",
    priceNote: "per person",
    image: images.dealMamanuca,
    category: "Package Deals",
    includes: ["Seaplane transfer", "Beachfront villa", "Snorkel hire"],
    nights: 3,
    transfersIncluded: true,
    flightsIncluded: true,
    freeCancellation: true,
    instantConfirmation: true,
    travelWindow: "Travel Apr – Nov 2026",
    urgency: "spotsLeft",
    spotsLeft: 6,
    verifiedSupplier: true,
    rating: 4.8,
    reviewCount: 142,
    originalPrice: "FJD 2,150",
    discountLabel: "Save 14%",
    resortCredit: "FJD 350 activity credit",
    breakfastIncluded: true,
    trustTags: ["verifiedPartner", "bestSeller"],
    packageTags: ["bestSeller", "limitedTimeOffer"],
    valueBlock: {
      resortCredit: "FJD 350 activity credit",
      includedTours: ["Guided reef snorkel", "Village cultural visit"],
      includedTransportation: ["Return seaplane Nadi–resort", "Island boat transfers"],
    },
    freeExcursions: "Guided reef snorkel & village visit",
    highlights: [
      "Return seaplane transfers",
      "Beachfront villa with reef access",
      "FJD 350 activity credit",
    ],
    packageDetail: {
      overview:
        "Arrive by seaplane to a beachfront villa on the Mamanuca reef — with daily snorkelling, guided reef excursions and activity credit for diving or island-hopping.",
      travelDates: "Travel 1 Apr – 30 Nov 2026",
      roomTypes: ["Beachfront villa", "Garden villa"],
      activities: ["Daily snorkel hire", "Guided reef snorkel", "Village cultural visit"],
      transportation: ["Return seaplane Nadi–resort", "Island boat transfers"],
      exclusions: ["Travel insurance", "Alcoholic beverages"],
      highlights: [
        "Return seaplane transfers",
        "Beachfront villa with reef access",
        "FJD 350 activity credit",
      ],
    },
  },
  {
    slug: "family-coral-coast-package",
    title: "Family Coral Coast Package",
    description:
      "Interconnecting bures, kids' club and Natadola Beach with complimentary family transfers included.",
    location: "Coral Coast",
    destination: "Coral Coast",
    resortName: "Outrigger Fiji Beach Resort",
    duration: "5 nights",
    travelDates: "School holidays 2026 — limited family bures",
    price: "FJD 1,680",
    priceNote: "per adult",
    image: images.dealBeach,
    category: "Package Deals",
    includes: ["Kids' club", "Family bure", "Beach activities"],
    nights: 5,
    transfersIncluded: true,
    flightsIncluded: false,
    freeCancellation: true,
    instantConfirmation: true,
    travelWindow: "Travel school holidays 2026",
    urgency: "limitedAvailability",
    familyPackage: true,
    kidsStayFree: true,
    kidsEatFree: true,
    verifiedSupplier: true,
    trustTags: ["verifiedPartner"],
    packageTags: ["familyFavourite", "mostBooked"],
    valueBlock: {
      resortCredit: "FJD 400 dining credit",
      includedTransportation: ["Complimentary Nadi airport transfers", "Resort shuttle to Natadola"],
      includedExperiences: ["Kids' club", "Natadola Beach activities"],
    },
    rating: 4.7,
    reviewCount: 184,
    resortCredit: "FJD 400 dining credit",
    complimentaryTransfers: true,
    highlights: [
      "Interconnecting family bures",
      "Kids' club & Natadola Beach access",
      "Complimentary family transfers",
    ],
    packageDetail: {
      overview:
        "Designed for families — interconnecting bures, kids' club programming and Natadola Beach with complimentary transfers and dining credit for relaxed Coral Coast evenings.",
      travelDates: "School holidays 2026 — limited family bures",
      roomTypes: ["Interconnecting family bure", "Two-bedroom beach bure"],
      activities: ["Kids' club", "Natadola Beach activities", "Village visit (optional)"],
      transportation: ["Complimentary Nadi airport transfers", "Resort shuttle to Natadola"],
      exclusions: ["Flights", "Travel insurance"],
      highlights: [
        "Interconnecting family bures",
        "Kids' club & Natadola Beach access",
        "Complimentary family transfers",
      ],
    },
  },
  {
    slug: "private-island-buyout",
    title: "Private Island Buyout",
    description:
      "Exclusive Mamanuca island for up to 12 guests — private chef, yacht and dedicated butler team.",
    location: "Mamanuca Islands",
    destination: "Mamanuca Islands",
    resortName: "Private Mamanuca Island",
    duration: "7 nights",
    travelDates: "By arrangement — peak season books 6–9 months ahead",
    price: "On request",
    priceNote: "tailored quote",
    image: images.dealPrivateIsland,
    category: "Package Deals",
    includes: ["Exclusive island", "Private chef", "Yacht charter"],
    nights: 7,
    transfersIncluded: true,
    flightsIncluded: false,
    freeCancellation: false,
    instantConfirmation: false,
    travelWindow: "By arrangement",
    verifiedSupplier: true,
    rating: 5,
    reviewCount: 24,
    bonusValue: "Complimentary welcome feast",
    complimentaryActivities: "Sunset cruise & reef snorkel",
    luxuryCollection: true,
    trustTags: ["verifiedResort", "highlyRated"],
    packageTags: ["luxuryEscape", "exclusiveDeal"],
    valueBlock: {
      bonusValue: "Complimentary welcome feast",
      includedExperiences: ["Sunset cruise", "Reef snorkel", "Private beach dining"],
      includedTransportation: ["Private boat transfers", "Yacht charter during stay"],
    },
    highlights: [
      "Exclusive island for up to 12 guests",
      "Private chef & dedicated butler team",
      "Yacht charter included",
    ],
    packageDetail: {
      overview:
        "Take an entire Mamanuca island for your party — private chef, yacht charter and a butler team orchestrating every detail from arrival to farewell feast.",
      travelDates: "By arrangement — peak season books 6–9 months ahead",
      roomTypes: ["Multiple beachfront villas", "Staff quarters included"],
      activities: ["Sunset cruise", "Reef snorkel", "Private beach dining"],
      transportation: ["Private boat transfers", "Yacht charter during stay"],
      exclusions: ["International flights", "Premium spirits procurement"],
      highlights: [
        "Exclusive island for up to 12 guests",
        "Private chef & dedicated butler team",
        "Yacht charter included",
      ],
    },
  },
  {
    slug: "stay-and-play-nadi",
    title: "Stay & Play Nadi Package",
    description:
      "Denarau resort stay with curated village visit, Sabeto mud pools and private island picnic day.",
    location: "Nadi & Denarau",
    destination: "Nadi & Denarau",
    resortName: "Sheraton Denarau Villas",
    duration: "4 nights",
    travelDates: "Valid anytime in 2026",
    bookBeforeDate: "15 Aug 2026",
    price: "FJD 1,290",
    priceNote: "per person",
    image: images.dealPool,
    category: "Package Deals",
    includes: ["Resort stay", "2 curated day trips", "All transfers"],
    nights: 4,
    transfersIncluded: true,
    flightsIncluded: true,
    freeCancellation: true,
    instantConfirmation: true,
    travelWindow: "Travel anytime 2026",
    urgency: "bookBefore",
    bookBefore: "15 Aug 2026",
    verifiedSupplier: true,
    rating: 4.6,
    reviewCount: 127,
    originalPrice: "FJD 1,490",
    discountLabel: "Save 13%",
    complimentaryTransfers: true,
    breakfastIncluded: true,
    trustTags: ["verifiedPartner"],
    packageTags: ["limitedTimeOffer", "mostBooked"],
    valueBlock: {
      includedTours: ["Village visit & Sabeto mud pools day"],
      includedTransportation: ["Return flights", "All day-trip transfers included"],
      includedExperiences: ["Private island picnic day"],
    },
    freeExcursions: "Village visit & Sabeto mud pools day",
    highlights: [
      "Denarau resort base with curated day trips",
      "Private island picnic day",
      "All transfers included",
    ],
    packageDetail: {
      overview:
        "A smart Nadi–Denarau base with two curated day experiences — village culture, Sabeto mud pools and a private island picnic — with all transfers handled.",
      travelDates: "Valid anytime in 2026",
      roomTypes: ["Garden-view room", "Marina-view room"],
      activities: ["Village visit", "Sabeto mud pools", "Private island picnic"],
      transportation: ["Return flights", "All day-trip transfers included"],
      exclusions: ["Travel insurance", "Lunch on free days"],
      highlights: [
        "Denarau resort base with curated day trips",
        "Private island picnic day",
        "All transfers included",
      ],
    },
  },
  {
    slug: "nadi-airport-layover-escape",
    title: "Nadi Airport Layover Escape",
    description:
      "Two-night Nadi stopover with temple visit, Sleeping Giant gardens and private airport transfers — perfect before or after island hops.",
    location: "Nadi",
    destination: "Nadi",
    resortName: "Tanoa Skylodge Hotel",
    duration: "2 nights",
    travelDates: "Valid year-round 2026",
    price: "FJD 490",
    priceNote: "per person",
    image: images.dealNadiPackage,
    category: "Package Deals",
    includes: ["Boutique hotel", "Temple & gardens tour", "Airport transfers"],
    nights: 2,
    transfersIncluded: true,
    flightsIncluded: false,
    freeCancellation: true,
    instantConfirmation: true,
    travelWindow: "Valid year-round 2026",
    verifiedSupplier: true,
    rating: 4.5,
    reviewCount: 89,
    complimentaryTransfers: true,
    breakfastIncluded: true,
    trustTags: ["verifiedPartner"],
    packageTags: ["mostBooked"],
    valueBlock: {
      includedTours: ["Sri Siva temple & Sleeping Giant gardens"],
      includedTransportation: ["Private Nadi airport transfers"],
    },
    highlights: [
      "Ideal pre- or post-island stopover",
      "Temple & gardens day included",
      "Private airport transfers",
    ],
    packageDetail: {
      overview:
        "A polished Nadi layover — boutique hillside hotel, curated temple and gardens half-day, and seamless airport transfers timed to your flights.",
      travelDates: "Valid year-round 2026",
      roomTypes: ["Garden-view room", "Pool-view room"],
      activities: ["Temple visit", "Sleeping Giant gardens", "Market stroll (optional)"],
      transportation: ["Private Nadi airport transfers"],
      exclusions: ["International flights", "Travel insurance"],
      highlights: [
        "Ideal pre- or post-island stopover",
        "Temple & gardens day included",
        "Private airport transfers",
      ],
    },
  },
  {
    slug: "denarau-marina-luxury-weekend",
    title: "Denarau Marina Luxury Weekend",
    description:
      "Three nights at a five-star Denarau resort with sunset cruise, spa credit and Mamanuca day trip from Port Denarau.",
    location: "Nadi & Denarau",
    destination: "Nadi & Denarau",
    resortName: "Radisson Blu Resort Fiji",
    duration: "3 nights",
    travelDates: "Travel anytime in 2026",
    price: "FJD 1,450",
    priceNote: "per person",
    image: images.dealDenarau,
    category: "Package Deals",
    includes: ["5-star resort", "Sunset cruise", "Mamanuca day trip"],
    nights: 3,
    transfersIncluded: true,
    flightsIncluded: false,
    freeCancellation: true,
    instantConfirmation: true,
    travelWindow: "Travel anytime in 2026",
    verifiedSupplier: true,
    rating: 4.7,
    reviewCount: 156,
    resortCredit: "FJD 250 spa credit",
    complimentaryTransfers: true,
    breakfastIncluded: true,
    trustTags: ["verifiedPartner", "highlyRated"],
    packageTags: ["limitedTimeOffer"],
    valueBlock: {
      resortCredit: "FJD 250 spa credit",
      includedTours: ["Mamanuca Islands day cruise"],
      includedTransportation: ["Nadi airport transfers", "Marina ferry connections"],
      includedExperiences: ["Sunset catamaran cruise"],
    },
    highlights: [
      "Denarau marina base",
      "Sunset cruise & Mamanuca day trip",
      "FJD 250 spa credit",
    ],
    packageDetail: {
      overview:
        "Weekend luxury from Nadi — five-star Denarau beachfront, sunset sailing, a full Mamanuca day cruise and spa credit for unhurried Pacific evenings.",
      travelDates: "Travel anytime in 2026",
      roomTypes: ["Lagoon-view room", "Beachfront suite"],
      activities: ["Sunset cruise", "Mamanuca day cruise", "Spa ritual"],
      transportation: ["Nadi airport transfers", "Marina ferry connections"],
      exclusions: ["Flights", "Premium spirits"],
      highlights: [
        "Denarau marina base",
        "Sunset cruise & Mamanuca day trip",
        "FJD 250 spa credit",
      ],
    },
  },
  {
    slug: "nadi-culture-heritage-package",
    title: "Nadi Culture & Heritage Package",
    description:
      "Four nights exploring Nadi's temples, markets, Sabeto mud pools and a highland village with all transfers and guided days included.",
    location: "Nadi",
    destination: "Nadi",
    resortName: "Hilton Fiji Beach Resort & Spa",
    duration: "4 nights",
    travelDates: "Travel May – Oct 2026",
    price: "FJD 1,680",
    priceNote: "per person",
    image: images.dealPool,
    category: "Package Deals",
    includes: ["Resort stay", "3 guided cultural days", "All transfers"],
    nights: 4,
    transfersIncluded: true,
    flightsIncluded: true,
    freeCancellation: true,
    instantConfirmation: true,
    travelWindow: "Travel May – Oct 2026",
    verifiedSupplier: true,
    rating: 4.8,
    reviewCount: 94,
    originalPrice: "FJD 1,890",
    discountLabel: "Save 11%",
    complimentaryTransfers: true,
    breakfastIncluded: true,
    trustTags: ["verifiedPartner"],
    packageTags: ["familyFavourite"],
    valueBlock: {
      includedTours: ["Temple & market day", "Sabeto mud pools", "Highland village feast"],
      includedTransportation: ["Return flights", "All excursion transfers"],
    },
    highlights: [
      "Three curated cultural days",
      "Sabeto mud pools & highland village",
      "Return flights included",
    ],
    packageDetail: {
      overview:
        "Discover Nadi beyond the airport — temple architecture, market flavours, Sabeto's healing mud pools and a highland village lovo feast with every transfer handled.",
      travelDates: "Travel May – Oct 2026",
      roomTypes: ["Garden-view room", "Marina-view room"],
      activities: ["Temple tour", "Market visit", "Sabeto mud pools", "Highland village"],
      transportation: ["Return flights", "All excursion transfers"],
      exclusions: ["Travel insurance", "Personal shopping"],
      highlights: [
        "Three curated cultural days",
        "Sabeto mud pools & highland village",
        "Return flights included",
      ],
    },
  },
  {
    slug: "yasawa-island-explorer",
    title: "Yasawa Island Explorer",
    description:
      "Island-hop the Yasawa chain with beachfront lodges, village welcomes and daily snorkel safaris.",
    location: "Yasawa Islands",
    destination: "Yasawa Islands",
    resortName: "Boutique Yasawa Beach Lodges",
    duration: "6 nights",
    travelDates: "Travel May – Oct 2026",
    price: "FJD 2,450",
    priceNote: "per person",
    image: images.dealYasawaAdventure,
    category: "Package Deals",
    includes: ["Island-hopping", "Beachfront lodge", "Snorkel safaris"],
    nights: 6,
    transfersIncluded: true,
    flightsIncluded: false,
    freeCancellation: true,
    instantConfirmation: true,
    travelWindow: "Travel May – Oct 2026",
    verifiedSupplier: true,
    rating: 4.8,
    reviewCount: 96,
    breakfastIncluded: true,
    trustTags: ["verifiedPartner"],
    packageTags: ["bestSeller"],
    valueBlock: {
      includedTours: ["Village welcome ceremony", "Blue Lagoon snorkel day"],
      includedTransportation: ["Inter-island boat transfers", "Nadi airport pickup"],
    },
    highlights: [
      "Three Yasawa islands in one journey",
      "Village welcome & cultural lunch",
      "Daily guided snorkel safaris",
    ],
    packageDetail: {
      overview:
        "Trace the Yasawa chain at an unhurried pace — beachfront lodges on three islands, a village welcome with lovo lunch, daily guided snorkel safaris and every inter-island transfer handled.",
      travelDates: "Travel May – Oct 2026",
      roomTypes: ["Beachfront bure", "Garden-view lodge room"],
      activities: [
        "Village welcome ceremony",
        "Blue Lagoon snorkel day",
        "Daily snorkel safaris",
        "Sunset beach dinner",
      ],
      transportation: ["Inter-island boat transfers", "Nadi airport pickup"],
      exclusions: ["International flights", "Travel insurance", "Alcoholic beverages"],
      highlights: [
        "Three Yasawa islands in one journey",
        "Village welcome & cultural lunch",
        "Daily guided snorkel safaris",
      ],
    },
  },
  {
    slug: "coral-coast-wellness-retreat",
    title: "Coral Coast Wellness Retreat",
    description:
      "Five nights of spa rituals, sunrise yoga and organic farm-to-table dining beside Natadola Beach.",
    location: "Coral Coast",
    destination: "Coral Coast",
    resortName: "Natadola Bay Wellness Pavilion",
    duration: "5 nights",
    travelDates: "Valid year-round; spa suites limited Dec–Apr",
    price: "FJD 2,120",
    priceNote: "per person",
    image: images.dealSpa,
    category: "Package Deals",
    includes: ["Spa suite", "Daily yoga", "Wellness dining"],
    nights: 5,
    transfersIncluded: true,
    flightsIncluded: false,
    freeCancellation: true,
    instantConfirmation: true,
    travelWindow: "Travel year-round",
    urgency: "trendingPackage",
    verifiedSupplier: true,
    rating: 4.85,
    reviewCount: 142,
    resortCredit: "FJD 600 spa credit",
    breakfastIncluded: true,
    allInclusive: false,
    luxuryCollection: true,
    trustTags: ["verifiedResort", "highlyRated"],
    packageTags: ["luxuryEscape", "exclusiveDeal"],
    valueBlock: {
      resortCredit: "FJD 600 spa credit",
      includedExperiences: ["Daily yoga pavilion", "Sunrise meditation", "Organic degustation dinner"],
      includedTransportation: ["Private Nadi airport transfers"],
    },
    highlights: [
      "Ocean-view spa suite",
      "FJD 600 spa & wellness credit",
      "Organic farm-to-table dining",
    ],
  },
  {
    slug: "natadola-luxury-escape",
    title: "Natadola Luxury Escape",
    description:
      "Beachfront suite on Fiji's finest sand with private cabana days, reef snorkel and sunset degustation.",
    location: "Natadola",
    destination: "Coral Coast",
    resortName: "InterContinental Natadola",
    duration: "4 nights",
    travelDates: "Travel year-round; suites limited Dec–Jan",
    price: "FJD 2,350",
    priceNote: "per person",
    image: images.dealCoralCoast,
    category: "Package Deals",
    includes: ["Beachfront suite", "Reef snorkel", "Degustation dinner"],
    nights: 4,
    transfersIncluded: true,
    flightsIncluded: false,
    freeCancellation: true,
    instantConfirmation: true,
    travelWindow: "Travel year-round",
    urgency: "mostPopular",
    verifiedSupplier: true,
    rating: 4.88,
    reviewCount: 167,
    resortCredit: "FJD 450 dining credit",
    breakfastIncluded: true,
    luxuryCollection: true,
    trustTags: ["verifiedResort", "highlyRated"],
    packageTags: ["luxuryEscape", "bestSeller"],
    valueBlock: {
      resortCredit: "FJD 450 dining credit",
      includedExperiences: ["Private cabana day", "Guided reef snorkel", "Sunset degustation"],
      includedTransportation: ["Private Nadi airport transfers"],
    },
    highlights: [
      "Natadola Beach beachfront suite",
      "Private cabana & reef snorkel",
      "FJD 450 dining credit",
    ],
  },
  {
    slug: "sigatoka-river-cultural-package",
    title: "Sigatoka River Cultural Package",
    description:
      "River safari, pottery village visit and hillside lodge with Fijian feast and Coral Coast transfers.",
    location: "Sigatoka",
    destination: "Coral Coast",
    resortName: "Sigatoka Valley Riverside Lodge",
    duration: "3 nights",
    travelDates: "Valid anytime in 2026",
    price: "FJD 1,420",
    priceNote: "per person",
    image: images.coralCoastCard,
    category: "Package Deals",
    includes: ["River safari", "Village visit", "Lodge stay"],
    nights: 3,
    transfersIncluded: true,
    flightsIncluded: false,
    freeCancellation: true,
    instantConfirmation: true,
    travelWindow: "Travel anytime 2026",
    urgency: "popularThisWeek",
    verifiedSupplier: true,
    rating: 4.6,
    reviewCount: 89,
    breakfastIncluded: true,
    trustTags: ["verifiedPartner"],
    packageTags: ["familyFavourite", "mostBooked"],
    valueBlock: {
      includedTours: ["Sigatoka River safari", "Pottery village visit"],
      includedTransportation: ["Coral Coast resort transfers", "Nadi airport pickup"],
      includedExperiences: ["Traditional Fijian feast", "Kava ceremony"],
    },
    highlights: [
      "Sigatoka River safari day",
      "Pottery village & kava ceremony",
      "All Coral Coast transfers included",
    ],
  },
  {
    slug: "korotogo-honeymoon-hideaway",
    title: "Korotogo Honeymoon Hideaway",
    description:
      "Clifftop bure with couples spa, private candlelit dinner and champagne on your ocean-view deck.",
    location: "Korotogo",
    destination: "Coral Coast",
    resortName: "Korotogo Clifftop Retreat",
    duration: "5 nights",
    travelDates: "Valid year-round; clifftop bures limited",
    price: "FJD 2,980",
    priceNote: "per couple",
    image: images.coralCoast,
    category: "Package Deals",
    includes: ["Clifftop bure", "Couples spa", "Private dinner"],
    nights: 5,
    transfersIncluded: true,
    flightsIncluded: false,
    freeCancellation: true,
    instantConfirmation: true,
    travelWindow: "Travel year-round",
    urgency: "trendingPackage",
    honeymoonPackage: true,
    luxuryCollection: true,
    verifiedSupplier: true,
    rating: 4.93,
    reviewCount: 118,
    bonusValue: "FJD 700 honeymoon inclusions",
    breakfastIncluded: true,
    trustTags: ["verifiedResort", "highlyRated"],
    packageTags: ["honeymoonCollection", "luxuryEscape"],
    valueBlock: {
      bonusValue: "FJD 700 honeymoon inclusions",
      includedExperiences: ["Couples spa ritual", "Private candlelit dinner", "Deck champagne"],
      includedTransportation: ["Private Nadi airport transfers"],
    },
    highlights: [
      "Clifftop ocean-view bure",
      "Couples spa & private dinner",
      "Champagne on your private deck",
    ],
  },
  {
    slug: "coral-coast-all-inclusive-week",
    title: "Coral Coast All-Inclusive Week",
    description:
      "Seven nights all-inclusive with daily excursions, kids' activities and unlimited dining across the resort.",
    location: "Coral Coast",
    destination: "Coral Coast",
    resortName: "Warwick Fiji Resort & Spa",
    duration: "7 nights",
    travelDates: "Travel 1 May – 30 Sep 2026",
    price: "FJD 3,150",
    priceNote: "per person",
    image: images.dealResort,
    category: "Package Deals",
    includes: ["All-inclusive", "Daily excursions", "Kids' activities"],
    nights: 7,
    transfersIncluded: true,
    flightsIncluded: true,
    freeCancellation: true,
    instantConfirmation: true,
    travelWindow: "Travel May – Sep 2026",
    urgency: "limitedTime",
    familyPackage: true,
    allInclusive: true,
    verifiedSupplier: true,
    rating: 4.72,
    reviewCount: 241,
    originalPrice: "FJD 3,690",
    discountLabel: "Save 15%",
    breakfastIncluded: true,
    kidsStayFree: true,
    trustTags: ["verifiedPartner", "bestSeller"],
    packageTags: ["familyFavourite", "limitedTimeOffer", "bestSeller"],
    valueBlock: {
      includedTours: ["Sigatoka sand dunes day", "Village cultural visit"],
      includedTransportation: ["Return flights", "Resort airport transfers"],
      includedExperiences: ["Daily kids' club", "Unlimited dining & beverages"],
    },
    highlights: [
      "Seven nights all-inclusive",
      "Return flights included",
      "Daily excursions & kids' club",
    ],
  },
  {
    slug: "taveuni-garden-island-package",
    title: "Taveuni Garden Island Package",
    description:
      "Rainforest eco-lodge with Bouma Falls hike, Rainbow Reef dive day and village kava welcome.",
    location: "Taveuni",
    destination: "Taveuni",
    resortName: "Garden Island Eco Retreat",
    duration: "5 nights",
    travelDates: "Travel Apr – Nov 2026",
    price: "FJD 2,890",
    priceNote: "per person",
    image: images.taveuniCard,
    category: "Package Deals",
    includes: ["Eco-lodge", "Rainforest hike", "Reef dive day"],
    nights: 5,
    transfersIncluded: true,
    flightsIncluded: true,
    freeCancellation: true,
    instantConfirmation: true,
    travelWindow: "Travel Apr – Nov 2026",
    urgency: "limitedAvailability",
    verifiedSupplier: true,
    rating: 4.9,
    reviewCount: 67,
    breakfastIncluded: true,
    trustTags: ["verifiedPartner", "highlyRated"],
    packageTags: ["luxuryEscape", "exclusiveDeal"],
    valueBlock: {
      includedTours: ["Bouma Falls guided hike", "Rainbow Reef dive day"],
      includedTransportation: ["Return flights Nadi–Taveuni", "Resort transfers"],
      includedExperiences: ["Village kava ceremony", "Rainforest birdwatching"],
    },
    highlights: [
      "Bouma Falls rainforest hike",
      "Rainbow Reef dive day included",
      "Return flights Nadi–Taveuni",
    ],
  },
  {
    slug: "pacific-harbour-adventure-package",
    title: "Pacific Harbour Adventure Package",
    description:
      "Beqa Lagoon shark dive, white-water rafting and riverside lodge with all adventure transfers.",
    location: "Pacific Harbour",
    destination: "Pacific Harbour",
    resortName: "Pacific Harbour Riverside Lodge",
    duration: "4 nights",
    travelDates: "Travel year-round; shark dive Tue–Sat",
    price: "FJD 1,950",
    priceNote: "per person",
    image: images.dealSharkDive,
    category: "Package Deals",
    includes: ["Shark dive", "White-water rafting", "Lodge stay"],
    nights: 4,
    transfersIncluded: true,
    flightsIncluded: false,
    freeCancellation: true,
    instantConfirmation: true,
    travelWindow: "Travel year-round",
    urgency: "mostPopular",
    verifiedSupplier: true,
    rating: 4.75,
    reviewCount: 113,
    breakfastIncluded: true,
    trustTags: ["verifiedPartner"],
    packageTags: ["bestSeller", "limitedTimeOffer"],
    valueBlock: {
      includedTours: ["Beqa Lagoon shark dive", "Upper Navua white-water rafting"],
      includedTransportation: ["All adventure day transfers", "Nadi airport pickup"],
      includedExperiences: ["Shark dive equipment & guide", "Riverside lodge dining"],
    },
    highlights: [
      "World-famous Beqa shark dive",
      "Upper Navua rafting day",
      "All adventure transfers included",
    ],
  },
  {
    slug: "denarau-sunset-sailing-package",
    title: "Denarau Sunset Sailing Package",
    description:
      "Marina-view villa with private sunset catamaran sail, champagne canapés and Denarau dining credit.",
    location: "Denarau Island",
    destination: "Denarau Island",
    resortName: "Port Denarau Marina Villas",
    duration: "4 nights",
    travelDates: "Valid anytime in 2026",
    bookBeforeDate: "31 Dec 2026",
    price: "FJD 1,740",
    priceNote: "per person",
    image: images.dealSunsetCruise,
    category: "Package Deals",
    includes: ["Marina villa", "Sunset sail", "Dining credit"],
    nights: 4,
    transfersIncluded: true,
    flightsIncluded: true,
    freeCancellation: true,
    instantConfirmation: true,
    travelWindow: "Travel anytime 2026",
    urgency: "bookBefore",
    bookBefore: "31 Dec 2026",
    verifiedSupplier: true,
    rating: 4.65,
    reviewCount: 156,
    resortCredit: "FJD 350 dining credit",
    breakfastIncluded: true,
    trustTags: ["verifiedPartner"],
    packageTags: ["mostBooked", "limitedTimeOffer"],
    valueBlock: {
      resortCredit: "FJD 350 dining credit",
      includedExperiences: ["Private sunset catamaran sail", "Champagne canapés on board"],
      includedTransportation: ["Return flights", "Marina transfers"],
    },
    highlights: [
      "Private sunset catamaran sail",
      "Marina-view villa stay",
      "FJD 350 waterfront dining credit",
    ],
  },
  {
    slug: "tokoriki-romance-package",
    title: "Tokoriki Romance Package",
    description:
      "Adults-only beachfront bure with couples spa, private beach dinner and return helicopter transfers.",
    location: "Mamanuca Islands",
    destination: "Mamanuca Islands",
    resortName: "Tokoriki Island Resort",
    duration: "5 nights",
    travelDates: "Valid year-round; peak demand Jun–Sep",
    price: "FJD 3,280",
    priceNote: "per couple",
    image: images.dealHoneymoon,
    category: "Package Deals",
    includes: ["Beachfront bure", "Couples spa", "Beach dinner"],
    nights: 5,
    transfersIncluded: true,
    flightsIncluded: false,
    freeCancellation: true,
    instantConfirmation: true,
    travelWindow: "Travel year-round",
    urgency: "trendingPackage",
    honeymoonPackage: true,
    luxuryCollection: true,
    verifiedSupplier: true,
    rating: 4.92,
    reviewCount: 203,
    bonusValue: "FJD 800 romance inclusions",
    breakfastIncluded: true,
    trustTags: ["verifiedResort", "highlyRated"],
    packageTags: ["honeymoonCollection", "luxuryEscape", "exclusiveDeal"],
    valueBlock: {
      bonusValue: "FJD 800 romance inclusions",
      includedExperiences: ["Couples spa ritual", "Private beach dinner", "Sunset champagne"],
      includedTransportation: ["Return helicopter Nadi–Tokoriki"],
    },
    highlights: [
      "Return helicopter transfers",
      "Couples spa & private beach dinner",
      "Adults-only beachfront bure",
    ],
  },
  {
    slug: "nadi-gateway-stopover",
    title: "Nadi Gateway Stopover",
    description: "Two-night airport-side luxury with Sabeto mud pools, temple visit and private transfers.",
    location: "Nadi",
    destination: "Nadi",
    resortName: "Fiji Marriott Momi Bay",
    duration: "2 nights",
    travelDates: "Valid anytime in 2026",
    price: "FJD 890",
    priceNote: "per person",
    image: images.nadiCard,
    category: "Package Deals",
    nights: 2,
    transfersIncluded: true,
    flightsIncluded: false,
    freeCancellation: true,
    instantConfirmation: true,
    travelWindow: "Valid anytime in 2026",
    urgency: "mostPopular",
    breakfastIncluded: true,
    verifiedSupplier: true,
    rating: 4.6,
    reviewCount: 142,
    packageTags: ["mostBooked", "limitedTimeOffer"],
    valueBlock: {
      includedTours: ["Sabeto mud pools", "Sri Siva temple visit"],
      includedTransportation: ["Private Nadi airport transfers"],
    },
  },
  {
    slug: "nadi-culture-temple-package",
    title: "Nadi Culture & Temple Package",
    description: "Garden of the Sleeping Giant, Sri Siva temple tour and boutique resort with daily breakfast.",
    location: "Nadi",
    destination: "Nadi",
    resortName: "Tanoa Skylodge Hotel",
    duration: "3 nights",
    travelDates: "Valid year-round",
    price: "FJD 1,050",
    priceNote: "per person",
    image: images.culture,
    category: "Package Deals",
    nights: 3,
    transfersIncluded: true,
    flightsIncluded: false,
    freeCancellation: true,
    instantConfirmation: true,
    travelWindow: "Valid year-round",
    urgency: "popularThisWeek",
    breakfastIncluded: true,
    verifiedSupplier: true,
    rating: 4.7,
    reviewCount: 98,
    originalPrice: "FJD 1,190",
    discountLabel: "Save 12%",
    packageTags: ["familyFavourite", "bestSeller"],
    valueBlock: {
      includedTours: ["Sleeping Giant gardens", "Sri Siva temple tour"],
      includedTransportation: ["Private Nadi airport transfers"],
    },
  },
  {
    slug: "nadi-mamanuca-sampler",
    title: "Nadi & Mamanuca Sampler",
    description: "Nadi base plus full-day Mamanuca island hop with snorkel, beach lunch and marina transfers.",
    location: "Nadi",
    destination: "Nadi",
    resortName: "Radisson Blu Resort Fiji",
    duration: "4 nights",
    travelDates: "Travel Apr – Nov 2026",
    price: "FJD 1,380",
    priceNote: "per person",
    image: images.dealDenarau,
    category: "Package Deals",
    nights: 4,
    transfersIncluded: true,
    flightsIncluded: true,
    freeCancellation: true,
    instantConfirmation: true,
    travelWindow: "Travel Apr – Nov 2026",
    breakfastIncluded: true,
    verifiedSupplier: true,
    rating: 4.8,
    reviewCount: 167,
    packageTags: ["mostBooked", "limitedTimeOffer"],
    valueBlock: {
      includedTours: ["Full-day Mamanuca island hop"],
      includedTransportation: ["Return flights", "Marina & airport transfers"],
      includedExperiences: ["Snorkel safari & beach lunch"],
    },
  },
  {
    slug: "suva-capital-discovery",
    title: "Suva Capital Discovery",
    description: "Grand Pacific heritage stay with guided city walk, museum tour and municipal market tastings.",
    location: "Suva",
    destination: "Suva",
    resortName: "Grand Pacific Hotel",
    duration: "3 nights",
    travelDates: "Valid anytime in 2026",
    price: "FJD 1,120",
    priceNote: "per person",
    image: images.suvaCard,
    category: "Package Deals",
    nights: 3,
    transfersIncluded: true,
    breakfastIncluded: true,
    verifiedSupplier: true,
    rating: 4.65,
    reviewCount: 88,
    packageTags: ["familyFavourite", "mostBooked"],
  },
  {
    slug: "suva-colonial-heritage-package",
    title: "Suva Colonial Heritage Package",
    description: "Heritage suites, Thurston Gardens, Fiji Museum and fine harbour dining at the capital's grande dame.",
    location: "Suva",
    destination: "Suva",
    duration: "4 nights",
    travelDates: "Valid year-round",
    price: "FJD 1,280",
    priceNote: "per person",
    image: images.suva,
    category: "Package Deals",
    nights: 4,
    transfersIncluded: true,
    breakfastIncluded: true,
    luxuryCollection: true,
    verifiedSupplier: true,
    rating: 4.7,
    reviewCount: 76,
    packageTags: ["luxuryEscape", "exclusiveDeal"],
  },
  {
    slug: "suva-rainforest-escape",
    title: "Suva Rainforest Escape",
    description: "Colo-i-Suva forest pools, city culture days and boutique harbour hotel with breakfast included.",
    location: "Suva",
    destination: "Suva",
    duration: "3 nights",
    travelDates: "Valid anytime in 2026",
    price: "FJD 1,050",
    priceNote: "per person",
    image: images.wellness,
    category: "Package Deals",
    nights: 3,
    transfersIncluded: true,
    breakfastIncluded: true,
    verifiedSupplier: true,
    rating: 4.6,
    reviewCount: 64,
    packageTags: ["bestSeller", "limitedTimeOffer"],
  },
  {
    slug: "suva-adventure-add-on",
    title: "Suva & Pacific Harbour Adventure",
    description: "Capital culture plus shark dive or rafting day trip with all transfers and harbour hotel base.",
    location: "Suva",
    destination: "Suva",
    duration: "5 nights",
    travelDates: "Travel year-round",
    price: "FJD 1,890",
    priceNote: "per person",
    image: images.pacificHarbourCard,
    category: "Package Deals",
    nights: 5,
    transfersIncluded: true,
    breakfastIncluded: true,
    verifiedSupplier: true,
    rating: 4.8,
    reviewCount: 54,
    packageTags: ["bestSeller", "limitedTimeOffer"],
  },
  {
    slug: "yasawa-blue-lagoon-package",
    title: "Yasawa Blue Lagoon Package",
    description: "Beachfront lodge, Sawa-i-Lau cave day and village homestay with inter-island boat transfers.",
    location: "Yasawa Islands",
    destination: "Yasawa Islands",
    duration: "5 nights",
    travelDates: "Travel May – Oct 2026",
    price: "FJD 2,650",
    priceNote: "per person",
    image: images.yasawaCard,
    category: "Package Deals",
    nights: 5,
    transfersIncluded: true,
    breakfastIncluded: true,
    verifiedSupplier: true,
    rating: 4.85,
    reviewCount: 112,
    packageTags: ["luxuryEscape", "bestSeller"],
  },
  {
    slug: "yasawa-honeymoon-hideaway",
    title: "Yasawa Honeymoon Hideaway",
    description: "Private island bure, sunset sail and couples beach dinner on the remote Yasawa chain.",
    location: "Yasawa Islands",
    destination: "Yasawa Islands",
    duration: "5 nights",
    travelDates: "Valid year-round",
    price: "FJD 3,450",
    priceNote: "per couple",
    image: images.dealHoneymoon,
    category: "Package Deals",
    nights: 5,
    transfersIncluded: true,
    honeymoonPackage: true,
    luxuryCollection: true,
    verifiedSupplier: true,
    rating: 4.92,
    reviewCount: 89,
    packageTags: ["honeymoonCollection", "luxuryEscape"],
  },
  {
    slug: "yasawa-family-island-week",
    title: "Yasawa Family Island Week",
    description: "Seven nights family lodge with kayak days, cave swim and kids' cultural activities included.",
    location: "Yasawa Islands",
    destination: "Yasawa Islands",
    duration: "7 nights",
    travelDates: "Travel school holidays 2026",
    price: "FJD 2,980",
    priceNote: "per adult",
    image: images.yasawa,
    category: "Package Deals",
    nights: 7,
    transfersIncluded: true,
    familyPackage: true,
    kidsStayFree: true,
    verifiedSupplier: true,
    rating: 4.7,
    reviewCount: 134,
    packageTags: ["familyFavourite", "mostBooked"],
  },
  {
    slug: "taveuni-reef-rainforest-package",
    title: "Taveuni Reef & Rainforest Package",
    description: "Rainbow Reef dive day, Bouma Falls hike and oceanfront resort with domestic flights included.",
    location: "Taveuni",
    destination: "Taveuni",
    duration: "5 nights",
    travelDates: "Travel Apr – Nov 2026",
    price: "FJD 2,750",
    priceNote: "per person",
    image: images.taveuniCard,
    category: "Package Deals",
    nights: 5,
    transfersIncluded: true,
    flightsIncluded: true,
    breakfastIncluded: true,
    verifiedSupplier: true,
    rating: 4.9,
    reviewCount: 78,
    packageTags: ["luxuryEscape", "bestSeller"],
  },
  {
    slug: "taveuni-birding-waterfall-package",
    title: "Taveuni Birding & Waterfall Package",
    description: "Birdwatching trail, Lavena Coastal Walk and garden-island eco-lodge with all guided excursions.",
    location: "Taveuni",
    destination: "Taveuni",
    duration: "4 nights",
    travelDates: "Valid year-round",
    price: "FJD 2,280",
    priceNote: "per person",
    image: images.storyTaveuni,
    category: "Package Deals",
    nights: 4,
    transfersIncluded: true,
    breakfastIncluded: true,
    verifiedSupplier: true,
    rating: 4.85,
    reviewCount: 56,
    packageTags: ["exclusiveDeal", "bestSeller"],
  },
  {
    slug: "pacific-harbour-shark-raft-combo",
    title: "Shark Dive & Rafting Combo",
    description: "Beqa shark dive plus Upper Navua rafting with riverside lodge and all adventure transfers.",
    location: "Pacific Harbour",
    destination: "Pacific Harbour",
    duration: "4 nights",
    travelDates: "Travel year-round",
    price: "FJD 2,150",
    priceNote: "per person",
    image: images.dealSharkDive,
    category: "Package Deals",
    nights: 4,
    transfersIncluded: true,
    breakfastIncluded: true,
    verifiedSupplier: true,
    rating: 4.8,
    reviewCount: 145,
    packageTags: ["bestSeller", "mostBooked"],
  },
  {
    slug: "pacific-harbour-adrenaline-week",
    title: "Pacific Harbour Adrenaline Week",
    description: "Shark dive, rafting, zip-line and golf day with Pearl resort base and FJD 400 activity credit.",
    location: "Pacific Harbour",
    destination: "Pacific Harbour",
    duration: "5 nights",
    travelDates: "Valid anytime in 2026",
    price: "FJD 2,680",
    priceNote: "per person",
    image: images.pacificHarbour,
    category: "Package Deals",
    nights: 5,
    transfersIncluded: true,
    resortCredit: "FJD 400 activity credit",
    verifiedSupplier: true,
    rating: 4.75,
    reviewCount: 92,
    packageTags: ["limitedTimeOffer", "bestSeller"],
  },
  {
    slug: "vanua-levu-reef-explorer",
    title: "Vanua Levu Reef Explorer",
    description: "Great Sea Reef snorkel day, plantation tour and boutique north-coast lodge with boat transfers.",
    location: "Vanua Levu",
    destination: "Vanua Levu",
    duration: "5 nights",
    travelDates: "Travel May – Oct 2026",
    price: "FJD 2,420",
    priceNote: "per person",
    image: images.vanuaLevu,
    category: "Package Deals",
    nights: 5,
    transfersIncluded: true,
    breakfastIncluded: true,
    verifiedSupplier: true,
    rating: 4.8,
    reviewCount: 67,
    packageTags: ["luxuryEscape", "exclusiveDeal"],
  },
  {
    slug: "savusavu-romance-package",
    title: "Savusavu Romance Package",
    description: "Hot springs, private villa and couples spa at Namale with bay-view dining and seaplane option.",
    location: "Savusavu",
    destination: "Savusavu",
    resortName: "Namale Resort & Spa",
    duration: "5 nights",
    travelDates: "Valid year-round",
    price: "FJD 3,680",
    priceNote: "per couple",
    image: images.dealSpa,
    category: "Package Deals",
    nights: 5,
    transfersIncluded: true,
    honeymoonPackage: true,
    luxuryCollection: true,
    verifiedSupplier: true,
    rating: 4.9,
    reviewCount: 48,
    packageTags: ["honeymoonCollection", "luxuryEscape"],
  },
  {
    slug: "vanua-levu-diving-week",
    title: "Vanua Levu Diving Week",
    description: "Seven nights with three Great Sea Reef dive days, hot springs and all north-coast transfers.",
    location: "Vanua Levu",
    destination: "Vanua Levu",
    duration: "7 nights",
    travelDates: "Travel Apr – Nov 2026",
    price: "FJD 3,290",
    priceNote: "per person",
    image: images.snorkel,
    category: "Package Deals",
    nights: 7,
    transfersIncluded: true,
    breakfastIncluded: true,
    verifiedSupplier: true,
    rating: 4.85,
    reviewCount: 41,
    packageTags: ["bestSeller", "exclusiveDeal"],
  },
  {
    slug: "kadavu-manta-dive-package",
    title: "Kadavu Manta Dive Package",
    description: "Astrolabe Reef dives, manta channel day and eco-bure stay with domestic flights from Nadi.",
    location: "Kadavu",
    destination: "Kadavu",
    resortName: "Matava Eco Resort",
    duration: "5 nights",
    travelDates: "Travel May – Oct 2026",
    price: "FJD 2,950",
    priceNote: "per person",
    image: images.kadavu,
    category: "Package Deals",
    nights: 5,
    transfersIncluded: true,
    flightsIncluded: true,
    breakfastIncluded: true,
    verifiedSupplier: true,
    rating: 4.9,
    reviewCount: 52,
    packageTags: ["luxuryEscape", "bestSeller"],
  },
  {
    slug: "kadavu-eco-island-week",
    title: "Kadavu Eco Island Week",
    description: "Village cultural day, kayak coast and reef snorkel from sustainable eco-resort base.",
    location: "Kadavu",
    destination: "Kadavu",
    duration: "7 nights",
    travelDates: "Valid year-round",
    price: "FJD 2,680",
    priceNote: "per person",
    image: images.storyKayak,
    category: "Package Deals",
    nights: 7,
    transfersIncluded: true,
    breakfastIncluded: true,
    verifiedSupplier: true,
    rating: 4.75,
    reviewCount: 38,
    packageTags: ["exclusiveDeal", "familyFavourite"],
  },
  {
    slug: "beqa-firewalker-package",
    title: "Beqa Firewalker Package",
    description: "Firewalking ceremony, lagoon snorkel and island resort with boat transfers from Pacific Harbour.",
    location: "Beqa Island",
    destination: "Beqa Island",
    resortName: "Beqa Lagoon Resort",
    duration: "4 nights",
    travelDates: "Valid anytime in 2026",
    price: "FJD 1,780",
    priceNote: "per person",
    image: images.eventFirewalking,
    category: "Package Deals",
    nights: 4,
    transfersIncluded: true,
    breakfastIncluded: true,
    verifiedSupplier: true,
    rating: 4.85,
    reviewCount: 94,
    packageTags: ["bestSeller", "mostBooked"],
  },
  {
    slug: "beqa-shark-fire-combo",
    title: "Beqa Shark & Fire Combo",
    description: "Shark dive day plus firewalking ceremony with island lodge and all boat transfers included.",
    location: "Beqa Island",
    destination: "Beqa Island",
    duration: "3 nights",
    travelDates: "Travel year-round",
    price: "FJD 2,280",
    priceNote: "per person",
    image: images.dealSharkDive,
    category: "Package Deals",
    nights: 3,
    transfersIncluded: true,
    breakfastIncluded: true,
    verifiedSupplier: true,
    rating: 4.9,
    reviewCount: 118,
    packageTags: ["bestSeller", "limitedTimeOffer"],
  },
  {
    slug: "mana-family-island-package",
    title: "Mana Family Island Package",
    description: "House reef snorkel, kids' club and interconnecting bures with return boat transfers from Denarau.",
    location: "Mana Island",
    destination: "Mana Island",
    resortName: "Mana Island Resort & Spa",
    duration: "5 nights",
    travelDates: "School holidays 2026",
    price: "FJD 1,920",
    priceNote: "per adult",
    image: images.mamanucaCard,
    category: "Package Deals",
    nights: 5,
    transfersIncluded: true,
    familyPackage: true,
    kidsEatFree: true,
    verifiedSupplier: true,
    rating: 4.7,
    reviewCount: 156,
    packageTags: ["familyFavourite", "mostBooked"],
  },
  {
    slug: "mana-honeymoon-escape",
    title: "Mana Honeymoon Escape",
    description: "Beachfront bure, sunset cruise and private beach dinner on family-friendly Mana Island.",
    location: "Mana Island",
    destination: "Mana Island",
    duration: "4 nights",
    travelDates: "Valid year-round",
    price: "FJD 2,450",
    priceNote: "per couple",
    image: images.dealBeach,
    category: "Package Deals",
    nights: 4,
    transfersIncluded: true,
    honeymoonPackage: true,
    verifiedSupplier: true,
    rating: 4.8,
    reviewCount: 87,
    packageTags: ["honeymoonCollection", "bestSeller"],
  },
  {
    slug: "malolo-beach-villa-package",
    title: "Malolo Beach Villa Package",
    description: "Beachfront villa, turtle reef snorkel and private beach picnic on Malolo Island.",
    location: "Malolo Island",
    destination: "Malolo Island",
    resortName: "Malolo Island Resort",
    duration: "5 nights",
    travelDates: "Travel Apr – Nov 2026",
    price: "FJD 2,180",
    priceNote: "per person",
    image: images.mamanuca,
    category: "Package Deals",
    nights: 5,
    transfersIncluded: true,
    breakfastIncluded: true,
    verifiedSupplier: true,
    rating: 4.75,
    reviewCount: 102,
    packageTags: ["luxuryEscape", "bestSeller"],
  },
  {
    slug: "malolo-family-fun-package",
    title: "Malolo Family Fun Package",
    description: "Island hike, reef snorkel and kids' activities with beachfront family bure and all transfers.",
    location: "Malolo Island",
    destination: "Malolo Island",
    duration: "5 nights",
    travelDates: "School holidays 2026",
    price: "FJD 1,850",
    priceNote: "per adult",
    image: images.family,
    category: "Package Deals",
    nights: 5,
    transfersIncluded: true,
    familyPackage: true,
    kidsStayFree: true,
    verifiedSupplier: true,
    rating: 4.72,
    reviewCount: 124,
    packageTags: ["familyFavourite", "mostBooked"],
  },
  {
    slug: "tokoriki-island-honeymoon",
    title: "Tokoriki Island Honeymoon",
    description: "Adults-only bure, couples spa ritual and private beach dinner on Tokoriki with helicopter transfers.",
    location: "Tokoriki Island",
    destination: "Tokoriki Island",
    resortName: "Tokoriki Island Resort",
    duration: "5 nights",
    travelDates: "Valid year-round",
    price: "FJD 3,480",
    priceNote: "per couple",
    image: images.dealHoneymoon,
    category: "Package Deals",
    nights: 5,
    transfersIncluded: true,
    honeymoonPackage: true,
    luxuryCollection: true,
    verifiedSupplier: true,
    rating: 4.94,
    reviewCount: 132,
    packageTags: ["honeymoonCollection", "luxuryEscape"],
  },
  {
    slug: "tokoriki-spa-dining-package",
    title: "Tokoriki Spa & Dining Package",
    description: "Oceanfront spa ritual, degustation dinner and beachfront bure on Fiji's romantic adults-only island.",
    location: "Tokoriki Island",
    destination: "Tokoriki Island",
    duration: "4 nights",
    travelDates: "Valid anytime in 2026",
    price: "FJD 2,890",
    priceNote: "per couple",
    image: images.dealSpa,
    category: "Package Deals",
    nights: 4,
    transfersIncluded: true,
    luxuryCollection: true,
    verifiedSupplier: true,
    rating: 4.9,
    reviewCount: 76,
    packageTags: ["luxuryEscape", "exclusiveDeal"],
  },
  {
    slug: "luxury-overwater-bure",
    title: "Luxury Overwater Bure Stay",
    description:
      "Sleep above crystal waters — private deck, butler service and in-bure dining.",
    location: "Mamanuca Islands",
    price: "FJD 1,850",
    priceNote: "per night",
    image: images.dealOverwater,
    category: "Accommodation",
    includes: ["Overwater bure", "Butler service", "In-bure dining"],
  },
  {
    slug: "coral-coast-beach-escape",
    title: "Coral Coast Beach Escape",
    description:
      "Natadola Beach resort with FJD 200 spa credit and curated degustation dinner.",
    location: "Coral Coast",
    price: "FJD 980",
    priceNote: "per night",
    image: images.dealBeach,
    category: "Accommodation",
    includes: ["Beachfront room", "Spa credit", "Degustation dinner"],
  },
  {
    slug: "wellness-spa-retreat",
    title: "Wellness & Spa Retreat",
    description:
      "Oceanfront yoga, traditional Bobo massage and organic farm-to-table dining.",
    location: "Denarau",
    price: "FJD 780",
    priceNote: "per night",
    image: images.dealSpa,
    category: "Accommodation",
    includes: ["Daily yoga", "Spa ritual", "Wellness dining"],
  },
  {
    slug: "likuliku-lagoon-stay",
    title: "Likuliku Lagoon Resort",
    description:
      "Fiji's only overwater bures — adults-only sanctuary with all-inclusive dining.",
    location: "Mamanuca Islands",
    price: "FJD 1,850",
    priceNote: "per night · all-inclusive",
    image: images.dealLikuliku,
    category: "Accommodation",
    includes: ["Overwater bure", "All-inclusive", "Adults only"],
  },
  {
    slug: "mamanuca-island-hopping",
    title: "Mamanuca Island Hopping",
    description:
      "Private speedboat, reef snorkelling and champagne picnic on a deserted sandbank.",
    location: "Mamanuca Islands",
    price: "FJD 650",
    priceNote: "per person",
    image: images.islandHop,
    category: "Experiences",
    includes: ["Private boat", "Snorkelling", "Champagne picnic"],
  },
  {
    slug: "yasawa-adventure-package",
    title: "Yasawa Adventure Package",
    description:
      "Guided hikes to hidden waterfalls, sea kayaking and village kava ceremony.",
    location: "Yasawa Islands",
    price: "FJD 890",
    priceNote: "per person",
    image: images.dealYasawaAdventure,
    category: "Experiences",
    includes: ["Waterfall hike", "Kayaking", "Village visit"],
  },
  {
    slug: "beqa-shark-dive",
    title: "Beqa Lagoon Shark Dive",
    description:
      "World-famous shark encounter with equipment, guide and resort transfer from Pacific Harbour.",
    location: "Pacific Harbour",
    price: "FJD 520",
    priceNote: "per person",
    image: images.dealSharkDive,
    category: "Experiences",
    includes: ["Shark dive", "Equipment", "Transfer"],
  },
  {
    slug: "sunset-cruise-denarau",
    title: "Private Sunset Cruise",
    description:
      "Champagne sailing from Denarau Marina — canapés, live music and golden-hour views.",
    location: "Denarau",
    price: "FJD 380",
    priceNote: "per person",
    image: images.dealSunsetCruise,
    category: "Experiences",
    includes: ["Private charter", "Canapés", "Champagne"],
  },
];

export function getFeaturedDeal(category?: DealCategory) {
  if (category) {
    return deals.find((d) => d.category === category && d.featured) ??
      deals.find((d) => d.category === category);
  }
  return deals.find((d) => d.featured) ?? deals[0];
}

export function getDealsByCategory(category: DealCategory) {
  return deals.filter((d) => d.category === category);
}

export function getDealBySlug(slug: string) {
  return deals.find((d) => d.slug === slug);
}

export function getRelatedPackageDeals(slug: string, limit = 3) {
  return deals
    .filter((d) => d.category === "Package Deals" && d.slug !== slug)
    .slice(0, limit);
}
