import { images } from "@/lib/images";
import type { Destination } from "./types";

const baseFaqs = (name: string): Destination["faqs"] => [
  {
    question: `What is the best time to visit ${name}?`,
    answer:
      "May through October offers dry, sunny weather ideal for beaches and water activities. November to April is warmer with lush landscapes and fewer crowds at luxury resorts.",
  },
  {
    question: `How do I get to ${name}?`,
    answer:
      "International flights arrive at Nadi International Airport. Private transfers, seaplanes and resort boats connect you to your final destination within hours.",
  },
];

export const destinations: Destination[] = [
  {
    slug: "coral-coast",
    title: "Coral Coast",
    region: "mainland",
    tagline: "Golden beaches & authentic Fijian culture",
    overview:
      "The Coral Coast stretches along Viti Levu's southern shore — a ribbon of palm-fringed beaches, luxury resorts and traditional villages where fire-walking ceremonies and kava rituals still shape daily life.",
    heroImage: images.coralCoast,
    cardImage: images.coralCoastCard,
    highlights: ["Sigatoka Sand Dunes", "Village ceremonies", "Luxury beach resorts"],
    thingsToDo: ["Village tours", "River safaris", "Golf at championship courses", "Spa retreats"],
    placesToStay: ["InterContinental Fiji", "Outrigger Fiji Beach Resort", "Private beach villas"],
    tours: ["Cultural immersion day", "Coastal helicopter flight", "Sunset dhow cruise"],
    beaches: ["Natadola Beach", "Maui Bay", "Korolevu coastline"],
    dining: ["Beachfront fine dining", "Lovo feasts", "Resort tasting menus"],
    transport: ["Nadi airport 1hr", "Private resort transfers", "Scenic coastal drive"],
    culture: ["Meke performances", "Pottery villages", "Traditional craft markets"],
    weather: "Warm year-round. Dry season May–Oct (26–30°C). Wet season Nov–Apr with afternoon showers.",
    faqs: baseFaqs("the Coral Coast"),
    relatedSlugs: ["pacific-harbour", "denarau", "suva"],
  },
  {
    slug: "nadi",
    title: "Nadi",
    region: "mainland",
    tagline: "Gateway to the Fiji Islands",
    overview:
      "Nadi is your arrival point into paradise — a vibrant hub connecting international travellers to the Mamanuca and Yasawa islands, Denarau Marina and Fiji's highland interior.",
    heroImage: images.nadi,
    cardImage: images.nadiCard,
    highlights: ["Sri Siva Subramaniya Temple", "Garden of the Sleeping Giant", "Denarau Marina"],
    thingsToDo: ["Island day trips", "Temple visits", "Market tours", "Golf"],
    placesToStay: ["Denarau resorts", "Boutique Nadi hotels", "Airport transit lodges"],
    tours: ["Mamanuca day cruise", "Sabeto mud pool & hot springs", "Highland village tour"],
    beaches: ["Denarau Beach", "Wailoaloa Beach"],
    dining: ["Indian-Fijian fusion", "Resort restaurants", "Local market produce"],
    transport: ["Nadi International Airport", "Denarau ferry terminal", "Helicopter transfers"],
    culture: ["Hindu temple architecture", "Multicultural markets", "Fijian craft centres"],
    weather: "Tropical and humid. Best visibility for island hops May–Oct.",
    travelTips: [
      "Pre-book airport transfers — especially for late-night arrivals",
      "Allow a half-day for Sabeto mud pools and Sleeping Giant gardens",
      "Denarau Marina ferries run on a schedule — confirm island departure times",
      "Carry FJD cash for Nadi market stalls and village gifts",
    ],
    faqs: baseFaqs("Nadi"),
    relatedSlugs: ["denarau", "mamanuca", "yasawa"],
  },
  {
    slug: "denarau",
    title: "Denarau",
    region: "mainland",
    tagline: "Luxury marina & world-class resorts",
    overview:
      "Denarau Island is Fiji's premier luxury address — a gated enclave of five-star resorts, championship golf, fine dining and the main departure point for Mamanuca and Yasawa island cruises.",
    heroImage: images.denarau,
    cardImage: images.denarauCard,
    highlights: ["Port Denarau Marina", "Championship golf", "Luxury shopping"],
    thingsToDo: ["Sunset cruises", "Jet ski safaris", "Spa rituals", "Island hopping"],
    placesToStay: ["Hilton Fiji", "Sofitel Fiji", "Radisson Blu", "Private residences"],
    tours: ["Private yacht charter", "Helicopter island tour", "Golf & spa packages"],
    beaches: ["Denarau Beach", "Resort lagoon pools"],
    dining: ["Ports O' Call", "Nuku restaurant", "Beach club dining"],
    transport: ["10 min from Nadi airport", "Marina ferries", "Private car service"],
    culture: ["Resort meke nights", "Craft markets", "Fijian cooking classes"],
    weather: "Sheltered west coast — drier than Suva. Ideal May–October.",
    faqs: baseFaqs("Denarau"),
    relatedSlugs: ["nadi", "mamanuca", "yasawa"],
  },
  {
    slug: "mamanuca",
    title: "Mamanuca Islands",
    region: "islands",
    tagline: "Castaway paradise & crystal lagoons",
    overview:
      "The Mamanuca group is Fiji's most iconic island chain — turquoise lagoons, barefoot luxury and the filming location of countless tropical dreams, reached by seaplane or speedboat from Denarau.",
    heroImage: images.mamanuca,
    cardImage: images.mamanucaCard,
    highlights: ["Castaway Island", "Cloud 9 floating bar", "World-class snorkelling"],
    thingsToDo: ["Snorkelling", "Surf Cloudbreak", "Kayaking", "Private picnics"],
    placesToStay: ["Likuliku Lagoon Resort", "Tokoriki Island Resort", "Castaway Island"],
    tours: ["Snorkel safari", "Sunset sailing", "Scuba discovery dive"],
    beaches: ["Monuriki Beach", "Modriki Island", "Resort private beaches"],
    dining: ["Overwater dining", "Beach BBQ", "Floating bar experiences"],
    transport: ["Speedboat from Denarau", "Seaplane transfers", "Resort private boats"],
    culture: ["Resort cultural nights", "Village visits on nearby islands"],
    weather: "Trade-wind cooled. Dry season perfect for water clarity.",
    faqs: baseFaqs("the Mamanuca Islands"),
    relatedSlugs: ["yasawa", "denarau", "coral-coast"],
  },
  {
    slug: "yasawa",
    title: "Yasawa Islands",
    region: "islands",
    tagline: "Remote islands & untouched beauty",
    overview:
      "The Yasawa archipelago offers Fiji at its most raw and romantic — dramatic volcanic peaks, blue-hole caves, deserted beaches and a handful of the South Pacific's most exclusive eco-luxury retreats.",
    heroImage: images.yasawa,
    cardImage: images.yasawaCard,
    highlights: ["Sawa-i-Lau caves", "Blue Lagoon", "Remote luxury lodges"],
    thingsToDo: ["Cave swimming", "Village homestays", "Hiking", "Diving"],
    placesToStay: ["Yasawa Island Resort", "Turtle Island", "Barefoot luxury lodges"],
    tours: ["Blue Lagoon day trip", "Cave expedition", "Multi-island sailing"],
    beaches: ["Octopus Beach", "Nanuya Levu", "Private resort coves"],
    dining: ["Beach feasts", "Resort degustation", "Catch-of-the-day BBQ"],
    transport: ["Yasawa Flyer ferry", "Seaplane", "Private yacht"],
    culture: ["Remote village visits", "Traditional fishing", "Storytelling evenings"],
    weather: "Drier than mainland. Best visibility Jun–Sep.",
    faqs: baseFaqs("the Yasawa Islands"),
    relatedSlugs: ["mamanuca", "taveuni", "denarau"],
  },
  {
    slug: "taveuni",
    title: "Taveuni",
    region: "islands",
    tagline: "Garden Island & waterfall country",
    overview:
      "Known as the Garden Island, Taveuni is a rainforest sanctuary of waterfalls, rare birds and world-famous dive sites — Bouma National Heritage Park and Rainbow Reef reward travellers who go beyond the resort circuit.",
    heroImage: images.taveuniHero,
    cardImage: images.taveuniCard,
    highlights: ["Bouma National Heritage Park", "Rainbow Reef diving", "Tavoro Waterfalls"],
    thingsToDo: ["Waterfall hikes", "Scuba diving", "Birdwatching", "Kayaking"],
    placesToStay: ["Taveuni Island Resort", "Garden Island Resort", "Eco-lodges"],
    tours: ["Bouma Falls trek", "Rainbow Reef dive", "Lavena Coastal Walk"],
    beaches: ["Lavena Beach", "Matei Beach", "Hidden coves"],
    dining: ["Plantation-style dining", "Fresh tropical produce", "Resort fusion menus"],
    transport: ["Domestic flight from Nadi/Suva", "Resort transfers", "Boat charters"],
    culture: ["Wainibau village", "Traditional taro farms", "Local craft"],
    weather: "Wettest region — lush year-round. Diving best Apr–Oct.",
    faqs: baseFaqs("Taveuni"),
    relatedSlugs: ["yasawa", "suva", "pacific-harbour"],
  },
  {
    slug: "pacific-harbour",
    title: "Pacific Harbour",
    region: "mainland",
    tagline: "Adventure capital of Fiji",
    overview:
      "Pacific Harbour is Fiji's adrenaline address — shark diving in Beqa Lagoon, white-water rafting, zip-lining and luxury villas overlooking the Pacific, all within reach of Suva.",
    heroImage: images.pacificHarbour,
    cardImage: images.pacificHarbourCard,
    highlights: ["Shark diving", "White-water rafting", "Zip Fiji"],
    thingsToDo: ["Shark feed dive", "Rafting Upper Navua", "Golf", "Deep-sea fishing"],
    placesToStay: ["The Pearl South Pacific", "Luxury villas", "Boutique lodges"],
    tours: ["Beqa shark encounter", "River rafting day", "Fishing charter"],
    beaches: ["Deuba coastline", "Resort beaches", "Day trips to Natadola via Coral Coast"],
    dining: ["Marina restaurants", "Resort fine dining", "Local seafood"],
    transport: ["2.5hr from Nadi", "45min from Suva", "Helicopter available"],
    culture: ["Beqa fire-walking", "Village performances", "Artisan markets"],
    weather: "Slightly wetter than west coast. Adventure sports year-round.",
    faqs: baseFaqs("Pacific Harbour"),
    relatedSlugs: ["coral-coast", "suva", "taveuni"],
  },
  {
    slug: "suva",
    title: "Suva",
    region: "mainland",
    tagline: "Capital of culture & commerce",
    overview:
      "Suva is the beating heart of modern Fiji — colonial architecture, vibrant markets, museums and a growing fine-dining scene, perfect for travellers who want culture before the beach.",
    heroImage: images.suva,
    cardImage: images.suvaCard,
    highlights: ["Fiji Museum", "Municipal Market", "Parliament & Thurston Gardens"],
    thingsToDo: ["Market tours", "Museum visits", "Colonial walks", "Nightlife"],
    placesToStay: ["Grand Pacific Hotel", "Holiday Inn Suva", "Boutique city hotels"],
    tours: ["City heritage walk", "Colo-i-Suva forest swim", "Highland day trip"],
    beaches: ["No city beach — day trips to Pacific Harbour"],
    dining: ["Fine dining", "Indian street food", "Seafood markets"],
    transport: ["Nausori International Airport", "Bus to Coral Coast", "Domestic flights"],
    culture: ["Fijian, Indian & Chinese heritage", "Live music", "Art galleries"],
    weather: "Wettest major city. Carry light rain gear year-round.",
    faqs: baseFaqs("Suva"),
    relatedSlugs: ["pacific-harbour", "coral-coast", "taveuni"],
  },
  {
    slug: "vanua-levu",
    title: "Vanua Levu",
    region: "islands",
    tagline: "Northern reefs & rainforest calm",
    overview:
      "Fiji's second-largest island — Savusavu Bay hot springs, Great Sea Reef diving and plantation country without the west-coast crowds. A quieter luxury alternative for repeat visitors.",
    heroImage: images.vanuaLevu,
    cardImage: images.vanuaLevu,
    highlights: ["Savusavu Bay", "Great Sea Reef", "Wasali Nature Reserve"],
    thingsToDo: ["Reef diving", "Hot springs", "Plantation tours", "Kayaking"],
    placesToStay: ["Namale Resort & Spa", "Jean-Michel Cousteau Resort", "Boutique Savusavu lodges"],
    tours: ["Diving expeditions", "Rainforest walks", "Copra plantation visits"],
    beaches: ["Savusavu Bay", "Labasa coast", "Hidden northern coves"],
    dining: ["Resort fine dining", "Savusavu waterfront", "Farm-to-table plantation meals"],
    transport: ["Domestic flight from Nadi/Suva", "Labasa airport", "Private boat charters"],
    culture: ["Village visits", "Copra heritage", "Northern Fijian craft markets"],
    weather: "Wetter north — lush year-round. Diving clearest May–Oct.",
    faqs: baseFaqs("Vanua Levu"),
    relatedSlugs: ["taveuni", "suva", "kadavu"],
  },
  {
    slug: "kadavu",
    title: "Kadavu",
    region: "islands",
    tagline: "Astrolabe Reef & total seclusion",
    overview:
      "Remote Kadavu and the Great Astrolabe Reef deliver manta encounters, drift diving and eco-luxury with almost no development — for travellers who want Fiji without the brochure crowds.",
    heroImage: images.kadavu,
    cardImage: images.kadavu,
    highlights: ["Great Astrolabe Reef", "Manta ray season", "Papageno Resort"],
    thingsToDo: ["Reef diving", "Manta snorkelling", "Kayaking", "Village immersions"],
    placesToStay: ["Papageno Resort", "Matava Eco Resort", "Private island lodges"],
    tours: ["Multi-day dive packages", "Kayak expeditions", "Village homestays"],
    beaches: ["Vunisea Bay", "Namalata coast", "Resort coves"],
    dining: ["Catch-of-the-day feasts", "Resort tasting menus", "Village lovo experiences"],
    transport: ["Domestic flight from Nadi", "Boat from Suva", "Resort transfers"],
    culture: ["Village welcome ceremonies", "Traditional fishing", "Masi weaving"],
    weather: "Tropical south — calm seas Apr–Nov. Manta season peaks in cooler months.",
    faqs: baseFaqs("Kadavu"),
    relatedSlugs: ["vanua-levu", "pacific-harbour", "taveuni"],
  },
  {
    slug: "savusavu",
    title: "Savusavu",
    region: "islands",
    tagline: "Hidden harbour & hot springs luxury",
    overview:
      "Savusavu is Fiji's best-kept secret — a horseshoe bay of boutique resorts, geothermal hot springs and world-class diving on the Great Sea Reef, without the west-coast crowds.",
    description:
      "A boutique northern harbour where luxury travellers discover reef diving, plantation estates and geothermal springs in an intimate, uncrowded setting.",
    heroImage: images.vanuaLevu,
    cardImage: images.vanuaLevu,
    gallery: [images.vanuaLevu, images.resortLikuliku],
    highlights: ["Savusavu Bay", "Hot springs", "Great Sea Reef"],
    thingsToDo: ["Reef diving", "Hot spring bathing", "Plantation tours", "Kayaking"],
    placesToStay: ["Namale Resort & Spa", "Jean-Michel Cousteau Resort", "Boutique bay lodges"],
    tours: ["Dive expeditions", "Rainforest walks", "Copra plantation visits"],
    beaches: ["Savusavu Bay", "Hidden coves", "Resort beaches"],
    dining: ["Waterfront fine dining", "Farm-to-table plantation meals", "Resort tasting menus"],
    transport: ["Domestic flight from Nadi", "Private boat charters", "Resort transfers"],
    culture: ["Village visits", "Northern craft markets", "Copra heritage"],
    weather: "Lush and warm year-round. Diving clearest May–October.",
    bestTimeToVisit: "May through October for dry weather and exceptional reef visibility.",
    travelTips: [
      "Book domestic flights early — limited daily services to Savusavu.",
      "Pack reef-safe sunscreen and a light rain jacket for afternoon showers.",
      "Combine with Taveuni for a twin Garden Island itinerary.",
    ],
    faqs: baseFaqs("Savusavu"),
    relatedSlugs: ["vanua-levu", "taveuni", "kadavu"],
  },
  {
    slug: "beqa-island",
    title: "Beqa Island",
    region: "islands",
    tagline: "Shark diving & fire-walking legends",
    overview:
      "Beqa Lagoon is legendary — home to the Beqa fire-walkers, world-famous shark dives and pristine reef systems just south of Pacific Harbour on Fiji's adventure coast.",
    description:
      "An island of adrenaline and tradition — shark encounters by day, fire-walking ceremonies by night, minutes from Pacific Harbour.",
    heroImage: images.dealSharkDive,
    cardImage: images.pacificHarbourCard,
    gallery: [images.dealSharkDive, images.pacificHarbour],
    highlights: ["Beqa Lagoon shark dive", "Fire-walking", "Pristine reefs"],
    thingsToDo: ["Shark feed diving", "Reef snorkelling", "Village fire-walking", "Deep-sea fishing"],
    placesToStay: ["Beqa Lagoon Resort", "Pacific Harbour villas", "Boutique island lodges"],
    tours: ["Shark encounter dive", "Fire-walking ceremony", "Fishing charter"],
    beaches: ["Beqa lagoon shores", "Resort beaches", "Day trips to Natadola"],
    dining: ["Island lovo feasts", "Marina restaurants", "Catch-of-the-day"],
    transport: ["Boat from Pacific Harbour", "45min from Suva", "Helicopter transfers"],
    culture: ["Beqa fire-walking tradition", "Village ceremonies", "Artisan craft"],
    weather: "Warm tropical. Best diving visibility May–October.",
    bestTimeToVisit: "May to October for calm seas and optimal shark dive conditions.",
    travelTips: [
      "Shark dives require advanced certification or guided discovery programs.",
      "Respect village protocols during fire-walking ceremonies.",
      "Pair with Pacific Harbour for rafting and zip-lining day trips.",
    ],
    faqs: baseFaqs("Beqa Island"),
    relatedSlugs: ["pacific-harbour", "coral-coast", "kadavu"],
  },
  {
    slug: "mana-island",
    title: "Mana Island",
    region: "islands",
    tagline: "Family-friendly island paradise",
    overview:
      "Mana Island sits in the heart of the Mamanucas — a coral-fringed escape with family resorts, snorkelling straight off the beach and easy speedboat access from Denarau.",
    description:
      "A classic Mamanuca island retreat — reef access, resort dining and barefoot luxury ideal for families and first-time island hoppers.",
    heroImage: images.mamanuca,
    cardImage: images.mamanucaCard,
    gallery: [images.mamanuca, images.resortCastaway],
    highlights: ["Reef snorkelling", "Family resorts", "Sunset beaches"],
    thingsToDo: ["Snorkelling", "Kayaking", "Island walks", "Sunset cruises"],
    placesToStay: ["Mana Island Resort", "Nearby Mamanuca resorts"],
    tours: ["Snorkel safari", "Sunset sailing", "Denarau day trips"],
    beaches: ["Mana Island beach", "Reef lagoons", "Private coves"],
    dining: ["Resort buffets", "Beach BBQ", "Island feasts"],
    transport: ["Speedboat from Denarau", "Resort transfers", "Seaplane options"],
    culture: ["Resort meke nights", "Village visits", "Craft demonstrations"],
    weather: "Trade-wind cooled. Dry season May–October ideal.",
    bestTimeToVisit: "May through October for calm lagoon waters and family-friendly conditions.",
    travelTips: [
      "Book return boat transfers when reserving your resort stay.",
      "Bring reef shoes for exploring tidal pools.",
      "Combine with Denarau for marina dining and golf.",
    ],
    faqs: baseFaqs("Mana Island"),
    relatedSlugs: ["mamanuca", "malolo-island", "denarau"],
  },
  {
    slug: "malolo-island",
    title: "Malolo Island",
    region: "islands",
    tagline: "Pristine lagoons & boutique resorts",
    overview:
      "Malolo Lailai is the Mamanuca's resort hub — turquoise lagoons, boutique bures and world-class diving, a short speedboat ride from Port Denarau Marina.",
    description:
      "The Mamanuca's most accessible island resort destination — lagoon swimming, diving and boutique luxury minutes from Denarau.",
    heroImage: images.islandHop,
    cardImage: images.mamanucaCard,
    gallery: [images.islandHop, images.mamanuca],
    highlights: ["Malolo Lailai", "Lagoon swimming", "Boutique resorts"],
    thingsToDo: ["Snorkelling", "Diving", "Spa rituals", "Island hopping"],
    placesToStay: ["Plantation Island Resort", "Lomani Island Resort", "Malolo Island Resort"],
    tours: ["Reef dive packages", "Sunset cruise", "Multi-island sailing"],
    beaches: ["Malolo Lailai lagoon", "Resort beaches", "Hidden sandbanks"],
    dining: ["Overwater dining", "Beach BBQ", "Resort tasting menus"],
    transport: ["Speedboat from Denarau", "Seaplane", "Resort private boats"],
    culture: ["Resort cultural nights", "Village visits", "Fijian cooking classes"],
    weather: "Sheltered lagoons. Best water clarity June–September.",
    bestTimeToVisit: "June to September for crystal-clear lagoon visibility and calm seas.",
    travelTips: [
      "Malolo Lailai is a shared resort island — check which property suits your style.",
      "Pre-book speedboat seats during peak season.",
      "Ideal base for Mamanuca island-hopping day trips.",
    ],
    faqs: baseFaqs("Malolo Island"),
    relatedSlugs: ["mamanuca", "mana-island", "tokoriki-island"],
  },
  {
    slug: "tokoriki-island",
    title: "Tokoriki Island",
    region: "islands",
    tagline: "Honeymoon haven in the Mamanucas",
    overview:
      "Tokoriki Island Resort defines Mamanuca romance — just 36 beachfront bures on a private island, adults-focused luxury and sunsets that stop conversations.",
    description:
      "An intimate adults-oriented island resort — honeymoon bures, private dining and diving on Fiji's most romantic Mamanuca escape.",
    heroImage: images.resortTokoriki,
    cardImage: images.resortTokoriki,
    gallery: [images.resortTokoriki, images.mamanuca],
    highlights: ["Beachfront bures", "Adults luxury", "Private dining"],
    thingsToDo: ["Diving", "Couples spa", "Private picnics", "Village visits"],
    placesToStay: ["Tokoriki Island Resort"],
    tours: ["Dive packages", "Sunset cruise", "Private island picnic"],
    beaches: ["Tokoriki private beach", "Reef access", "Sandbank dinners"],
    dining: ["Private beach dining", "Resort degustation", "Champagne sunsets"],
    transport: ["Speedboat from Denarau", "Helicopter transfers", "Resort meet-and-greet"],
    culture: ["Resort meke nights", "Private dining traditions", "Island hospitality"],
    weather: "Trade-wind cooled west. Ideal May–October.",
    bestTimeToVisit: "May to October for honeymoon-perfect weather and calm lagoon seas.",
    travelTips: [
      "Adults-only atmosphere — ideal for couples and honeymoons.",
      "Book spa and private dining when confirming your stay.",
      "Request a beachfront bure for the best sunset views.",
    ],
    faqs: baseFaqs("Tokoriki Island"),
    relatedSlugs: ["mamanuca", "likuliku-lagoon", "malolo-island"],
  },
];

export function getDestination(slug: string) {
  return destinations.find((d) => d.slug === slug);
}

export function getDestinationSlugs() {
  return destinations.map((d) => d.slug);
}

export const mainlandDestinations = destinations.filter((d) => d.region === "mainland");
export const islandDestinations = destinations.filter((d) => d.region === "islands");
