/**
 * Supplemental marketplace seed — brings every destination hub up to the
 * Coral Coast baseline: 6 experiences, 6 package deals, 6 stays.
 */
import { images } from "@/lib/images";
import type { FijiDeal } from "@/lib/content/deals";
import type { Experience, Resort } from "@/lib/content/types";

const CORAL_COAST_BASELINE = { experiences: 6, packages: 6, stays: 6 } as const;

function mkExp(p: {
  slug: string;
  title: string;
  location: string;
  category: string;
  image?: string;
  priceFrom?: string;
  duration?: string;
}): Experience {
  return {
    slug: p.slug,
    title: p.title,
    location: p.location,
    category: p.category,
    duration: p.duration ?? "Half Day",
    ages: "All ages",
    priceFrom: p.priceFrom ?? "FJD 165",
    rating: { score: "4.8", count: 120 },
    heroImage: p.image ?? images.adventure,
    overview: `${p.title} — a curated luxury experience with expert guides and seamless transfers.`,
    highlights: ["Expert guides", "Premium gear", "Concierge transfers"],
    included: ["Guide", "Transfers", "Refreshments"],
    itinerary: ["Pickup", "Experience", "Return"],
    faqs: [
      {
        question: "How far ahead should I book?",
        answer: "We recommend 48 hours in peak season; your concierge can confirm same-day where available.",
      },
    ],
    relatedSlugs: [],
  };
}

function mkPkg(p: {
  slug: string;
  title: string;
  location: string;
  destination: string;
  price: string;
  image?: string;
  nights?: number;
  priceNote?: string;
}): FijiDeal {
  const nights = p.nights ?? 4;
  return {
    slug: p.slug,
    title: p.title,
    description: `${p.title} with handpicked accommodation, curated experiences and private transfers.`,
    location: p.location,
    destination: p.destination,
    duration: `${nights} nights`,
    travelDates: "Valid anytime in 2026",
    price: p.price,
    priceNote: p.priceNote ?? "per person",
    image: p.image ?? images.dealResort,
    category: "Package Deals",
    nights,
    transfersIncluded: true,
    breakfastIncluded: true,
    verifiedSupplier: true,
    rating: 4.75,
    reviewCount: 96,
    packageTags: ["bestSeller"],
  };
}

function mkResort(p: {
  slug: string;
  title: string;
  location: string;
  priceFrom?: string;
  image?: string;
  stars?: number;
}): Resort {
  return {
    slug: p.slug,
    title: p.title,
    location: p.location,
    stars: p.stars ?? 5,
    priceFrom: p.priceFrom ?? "FJD 680",
    heroImage: p.image ?? images.dealResort,
    overview: `${p.title} — boutique luxury on ${p.location}, curated for discerning travellers.`,
    amenities: ["Beachfront", "Spa", "Fine dining", "Concierge"],
    experiences: ["Snorkelling", "Cultural tours", "Sunset cruise"],
    relatedSlugs: [],
  };
}

export const fillExperiences: Experience[] = [
  // Denarau (+2 → 6)
  mkExp({
    slug: "denarau-marina-walking-tour",
    title: "Port Denarau Marina Walk",
    location: "Denarau",
    category: "Culture",
    image: images.dealDenarau,
  }),
  mkExp({
    slug: "denarau-lagoon-fishing",
    title: "Denarau Lagoon Fishing",
    location: "Denarau",
    category: "Water",
    image: images.dealMamanuca,
    priceFrom: "FJD 195",
  }),
  // Mamanuca (+4 → 6)
  mkExp({
    slug: "cloudbreak-surf-safari",
    title: "Cloudbreak Surf Safari",
    location: "Mamanuca Islands",
    category: "Adventure",
    image: images.surfing,
    priceFrom: "FJD 285",
  }),
  mkExp({
    slug: "modriki-island-day",
    title: "Modriki Island Day Trip",
    location: "Mamanuca Islands",
    category: "Water",
    image: images.dealMamanuca,
  }),
  mkExp({
    slug: "mamanuca-seaplane-scenic",
    title: "Mamanuca Seaplane Scenic",
    location: "Mamanuca Islands",
    category: "Adventure",
    image: images.dealOverwater,
    priceFrom: "FJD 420",
  }),
  mkExp({
    slug: "mamanuca-private-picnic",
    title: "Private Sandbank Picnic",
    location: "Mamanuca Islands",
    category: "Culture",
    image: images.picnic,
    priceFrom: "FJD 350",
  }),
  // Yasawa (+1 → 6)
  mkExp({
    slug: "yasawa-village-craft-tour",
    title: "Yasawa Village Craft Tour",
    location: "Yasawa Islands",
    category: "Culture",
    image: images.culture,
  }),
  // Taveuni (+2 → 6)
  mkExp({
    slug: "taveuni-plantation-tour",
    title: "Taveuni Plantation Tour",
    location: "Taveuni",
    category: "Culture",
    image: images.culture,
  }),
  mkExp({
    slug: "taveuni-kayak-bay",
    title: "Matei Bay Kayaking",
    location: "Taveuni",
    category: "Water",
    image: images.storyKayak,
  }),
  // Pacific Harbour (+3 → 6)
  mkExp({
    slug: "pacific-harbour-deep-sea-fishing",
    title: "Deep Sea Fishing Charter",
    location: "Pacific Harbour",
    category: "Adventure",
    image: images.pacificHarbour,
    priceFrom: "FJD 450",
    duration: "Full Day",
  }),
  mkExp({
    slug: "pacific-harbour-golf-day",
    title: "Pacific Harbour Golf Day",
    location: "Pacific Harbour",
    category: "Adventure",
    image: images.dealDenarau,
  }),
  mkExp({
    slug: "pacific-harbour-cultural-night",
    title: "Beqa Firewalking Night",
    location: "Pacific Harbour",
    category: "Culture",
    image: images.eventFirewalking,
  }),
  // Suva (+2 → 6)
  mkExp({
    slug: "suva-thurston-gardens",
    title: "Thurston Gardens Stroll",
    location: "Suva",
    category: "Nature",
    image: images.suvaCard,
  }),
  mkExp({
    slug: "suva-harbour-sunset",
    title: "Suva Harbour Sunset Walk",
    location: "Suva",
    category: "Culture",
    image: images.suva,
  }),
  // Vanua Levu (+2 → 6)
  mkExp({
    slug: "vanua-levu-waterfall-trek",
    title: "Vanua Levu Waterfall Trek",
    location: "Vanua Levu",
    category: "Adventure",
    image: images.hiking,
  }),
  mkExp({
    slug: "vanua-levu-bay-kayak",
    title: "Savusavu Bay Kayaking",
    location: "Vanua Levu",
    category: "Water",
    image: images.storyKayak,
  }),
  // Kadavu (+2 → 6)
  mkExp({
    slug: "kadavu-manta-snorkel",
    title: "Manta Ray Snorkel",
    location: "Kadavu",
    category: "Water",
    image: images.snorkel,
    priceFrom: "FJD 220",
  }),
  mkExp({
    slug: "kadavu-plantation-walk",
    title: "Kadavu Plantation Walk",
    location: "Kadavu",
    category: "Nature",
    image: images.kadavu,
  }),
  // Savusavu (+5 → 6)
  mkExp({
    slug: "savusavu-diving-day",
    title: "Savusavu Bay Dive Day",
    location: "Savusavu",
    category: "Water",
    image: images.snorkel,
    priceFrom: "FJD 295",
  }),
  mkExp({
    slug: "savusavu-chocolate-tour",
    title: "Savusavu Cacao Tour",
    location: "Savusavu",
    category: "Culture",
    image: images.culture,
  }),
  mkExp({
    slug: "savusavu-bay-sail",
    title: "Savusavu Bay Sunset Sail",
    location: "Savusavu",
    category: "Sailing",
    image: images.dealSunsetCruise,
  }),
  mkExp({
    slug: "savusavu-rainforest-walk",
    title: "Wasali Forest Walk",
    location: "Savusavu",
    category: "Nature",
    image: images.hiking,
  }),
  mkExp({
    slug: "savusavu-village-visit",
    title: "Savusavu Village Visit",
    location: "Savusavu",
    category: "Culture",
    image: images.village,
  }),
  // Beqa (+3 → 6)
  mkExp({
    slug: "beqa-reef-diving",
    title: "Beqa Reef Diving",
    location: "Beqa Island",
    category: "Water",
    image: images.dealSharkDive,
    priceFrom: "FJD 280",
  }),
  mkExp({
    slug: "beqa-kayak-lagoon",
    title: "Beqa Lagoon Kayak",
    location: "Beqa Island",
    category: "Water",
    image: images.storyKayak,
  }),
  mkExp({
    slug: "beqa-cultural-workshop",
    title: "Beqa Craft Workshop",
    location: "Beqa Island",
    category: "Culture",
    image: images.culture,
  }),
  // Mana (+3 → 6)
  mkExp({
    slug: "mana-turtle-snorkel",
    title: "Mana Turtle Reef Snorkel",
    location: "Mana Island",
    category: "Water",
    image: images.snorkel,
  }),
  mkExp({
    slug: "mana-island-hike",
    title: "Mana Island Ridge Hike",
    location: "Mana Island",
    category: "Adventure",
    image: images.hiking,
  }),
  mkExp({
    slug: "mana-village-visit",
    title: "Nearby Village Visit",
    location: "Mana Island",
    category: "Culture",
    image: images.village,
  }),
  // Malolo (+3 → 6)
  mkExp({
    slug: "malolo-sunset-sail",
    title: "Malolo Sunset Sail",
    location: "Malolo Island",
    category: "Sailing",
    image: images.dealSunsetCruise,
  }),
  mkExp({
    slug: "malolo-reef-diving",
    title: "Malolo Reef Diving",
    location: "Malolo Island",
    category: "Water",
    image: images.dealLikuliku,
    priceFrom: "FJD 240",
  }),
  mkExp({
    slug: "malolo-village-tour",
    title: "Malolo Cultural Tour",
    location: "Malolo Island",
    category: "Culture",
    image: images.village,
  }),
  // Tokoriki (+3 → 6)
  mkExp({
    slug: "tokoriki-champagne-sunset",
    title: "Tokoriki Champagne Sunset",
    location: "Tokoriki Island",
    category: "Sailing",
    image: images.dealSunsetCruise,
  }),
  mkExp({
    slug: "tokoriki-house-reef-snorkel",
    title: "Tokoriki House Reef Snorkel",
    location: "Tokoriki Island",
    category: "Water",
    image: images.snorkel,
  }),
  mkExp({
    slug: "tokoriki-couples-yoga",
    title: "Tokoriki Couples Yoga",
    location: "Tokoriki Island",
    category: "Wellness",
    image: images.dealSpa,
  }),
];

export const fillPackageDeals: FijiDeal[] = [
  // Denarau (+2 → 6)
  mkPkg({
    slug: "denarau-marina-villa-week",
    title: "Denarau Marina Villa Week",
    location: "Denarau",
    destination: "Denarau",
    price: "FJD 2,450",
    image: images.dealDenarau,
    nights: 7,
  }),
  mkPkg({
    slug: "denarau-golf-spa-escape",
    title: "Denarau Golf & Spa Escape",
    location: "Denarau",
    destination: "Denarau",
    price: "FJD 1,980",
    image: images.dealPool,
  }),
  // Mamanuca (+2 → 6)
  mkPkg({
    slug: "mamanuca-castaway-week",
    title: "Mamanuca Castaway Week",
    location: "Mamanuca Islands",
    destination: "Mamanuca Islands",
    price: "FJD 2,680",
    image: images.dealMamanuca,
    nights: 7,
  }),
  mkPkg({
    slug: "mamanuca-luxury-reef-package",
    title: "Mamanuca Luxury Reef Package",
    location: "Mamanuca Islands",
    destination: "Mamanuca Islands",
    price: "FJD 2,290",
    image: images.dealLikuliku,
  }),
  // Yasawa (+2 → 6)
  mkPkg({
    slug: "yasawa-cave-lagoon-escape",
    title: "Yasawa Cave & Lagoon Escape",
    location: "Yasawa Islands",
    destination: "Yasawa Islands",
    price: "FJD 2,380",
    image: images.yasawaCard,
  }),
  mkPkg({
    slug: "yasawa-luxury-sailing-week",
    title: "Yasawa Luxury Sailing Week",
    location: "Yasawa Islands",
    destination: "Yasawa Islands",
    price: "FJD 3,120",
    image: images.dealSunsetCruise,
    nights: 7,
  }),
  // Taveuni (+3 → 6)
  mkPkg({
    slug: "taveuni-dive-waterfall-package",
    title: "Taveuni Dive & Waterfall Package",
    location: "Taveuni",
    destination: "Taveuni",
    price: "FJD 2,650",
    image: images.taveuniCard,
  }),
  mkPkg({
    slug: "taveuni-garden-island-week",
    title: "Taveuni Garden Island Week",
    location: "Taveuni",
    destination: "Taveuni",
    price: "FJD 3,050",
    image: images.storyTaveuni,
    nights: 7,
  }),
  mkPkg({
    slug: "taveuni-eco-adventure-package",
    title: "Taveuni Eco Adventure Package",
    location: "Taveuni",
    destination: "Taveuni",
    price: "FJD 2,420",
    image: images.hiking,
  }),
  // Pacific Harbour (+3 → 6)
  mkPkg({
    slug: "pacific-harbour-zip-raft-package",
    title: "Zip & Raft Adventure Package",
    location: "Pacific Harbour",
    destination: "Pacific Harbour",
    price: "FJD 2,280",
    image: images.adventure,
  }),
  mkPkg({
    slug: "pacific-harbour-pearl-resort-week",
    title: "Pearl Resort Adventure Week",
    location: "Pacific Harbour",
    destination: "Pacific Harbour",
    price: "FJD 2,890",
    image: images.pacificHarbourCard,
    nights: 7,
  }),
  mkPkg({
    slug: "pacific-harbour-fishing-package",
    title: "Pacific Harbour Fishing Package",
    location: "Pacific Harbour",
    destination: "Pacific Harbour",
    price: "FJD 2,150",
    image: images.pacificHarbour,
  }),
  // Suva (+2 → 6)
  mkPkg({
    slug: "suva-heritage-weekend",
    title: "Suva Heritage Weekend",
    location: "Suva",
    destination: "Suva",
    price: "FJD 980",
    image: images.suvaCard,
    nights: 2,
  }),
  mkPkg({
    slug: "suva-capital-luxury-week",
    title: "Suva Capital Luxury Week",
    location: "Suva",
    destination: "Suva",
    price: "FJD 2,150",
    image: images.suva,
    nights: 7,
  }),
  // Vanua Levu (+3 → 6)
  mkPkg({
    slug: "vanua-levu-north-coast-package",
    title: "Vanua Levu North Coast Package",
    location: "Vanua Levu",
    destination: "Vanua Levu",
    price: "FJD 2,380",
    image: images.vanuaLevu,
  }),
  mkPkg({
    slug: "vanua-levu-reef-week",
    title: "Great Sea Reef Week",
    location: "Vanua Levu",
    destination: "Vanua Levu",
    price: "FJD 3,280",
    image: images.snorkel,
    nights: 7,
  }),
  mkPkg({
    slug: "vanua-levu-rainforest-retreat",
    title: "Vanua Levu Rainforest Retreat",
    location: "Vanua Levu",
    destination: "Vanua Levu",
    price: "FJD 2,120",
    image: images.hiking,
  }),
  // Kadavu (+4 → 6)
  mkPkg({
    slug: "kadavu-manta-week",
    title: "Kadavu Manta Week",
    location: "Kadavu",
    destination: "Kadavu",
    price: "FJD 3,150",
    image: images.kadavu,
    nights: 7,
  }),
  mkPkg({
    slug: "kadavu-astrolabe-explorer",
    title: "Astrolabe Reef Explorer",
    location: "Kadavu",
    destination: "Kadavu",
    price: "FJD 2,750",
    image: images.snorkel,
  }),
  mkPkg({
    slug: "kadavu-village-culture-package",
    title: "Kadavu Village Culture Package",
    location: "Kadavu",
    destination: "Kadavu",
    price: "FJD 2,180",
    image: images.village,
  }),
  mkPkg({
    slug: "kadavu-kayak-island-package",
    title: "Kadavu Kayak Island Package",
    location: "Kadavu",
    destination: "Kadavu",
    price: "FJD 2,350",
    image: images.storyKayak,
  }),
  // Savusavu (+5 → 6)
  mkPkg({
    slug: "savusavu-hot-springs-package",
    title: "Savusavu Hot Springs Package",
    location: "Savusavu",
    destination: "Savusavu",
    price: "FJD 2,280",
    image: images.dealSpa,
  }),
  mkPkg({
    slug: "savusavu-bay-luxury-week",
    title: "Savusavu Bay Luxury Week",
    location: "Savusavu",
    destination: "Savusavu",
    price: "FJD 3,450",
    image: images.vanuaLevu,
    nights: 7,
  }),
  mkPkg({
    slug: "savusavu-diving-package",
    title: "Savusavu Diving Package",
    location: "Savusavu",
    destination: "Savusavu",
    price: "FJD 2,650",
    image: images.snorkel,
  }),
  mkPkg({
    slug: "savusavu-couples-retreat",
    title: "Savusavu Couples Retreat",
    location: "Savusavu",
    destination: "Savusavu",
    price: "FJD 3,280",
    priceNote: "per couple",
    image: images.dealHoneymoon,
  }),
  mkPkg({
    slug: "savusavu-namale-estate-package",
    title: "Namale Estate Package",
    location: "Savusavu",
    destination: "Savusavu",
    price: "FJD 4,200",
    priceNote: "per couple",
    image: images.luxury,
    nights: 5,
  }),
  // Beqa (+4 → 6)
  mkPkg({
    slug: "beqa-lagoon-escape-package",
    title: "Beqa Lagoon Escape",
    location: "Beqa Island",
    destination: "Beqa Island",
    price: "FJD 1,950",
    image: images.dealBeach,
  }),
  mkPkg({
    slug: "beqa-adventure-duo-package",
    title: "Beqa Adventure Duo Package",
    location: "Beqa Island",
    destination: "Beqa Island",
    price: "FJD 2,450",
    image: images.dealSharkDive,
  }),
  mkPkg({
    slug: "beqa-cultural-immersion",
    title: "Beqa Cultural Immersion",
    location: "Beqa Island",
    destination: "Beqa Island",
    price: "FJD 1,780",
    image: images.eventFirewalking,
  }),
  mkPkg({
    slug: "beqa-island-week",
    title: "Beqa Island Week",
    location: "Beqa Island",
    destination: "Beqa Island",
    price: "FJD 2,890",
    image: images.dealResort,
    nights: 7,
  }),
  // Mana (+4 → 6)
  mkPkg({
    slug: "mana-reef-family-week",
    title: "Mana Reef Family Week",
    location: "Mana Island",
    destination: "Mana Island",
    price: "FJD 2,280",
    image: images.mamanucaCard,
    nights: 7,
  }),
  mkPkg({
    slug: "mana-island-escape",
    title: "Mana Island Escape",
    location: "Mana Island",
    destination: "Mana Island",
    price: "FJD 1,890",
    image: images.dealBeach,
  }),
  mkPkg({
    slug: "mana-all-inclusive-package",
    title: "Mana All-Inclusive Package",
    location: "Mana Island",
    destination: "Mana Island",
    price: "FJD 2,450",
    image: images.dealPool,
    nights: 5,
  }),
  mkPkg({
    slug: "mana-sunset-honeymoon",
    title: "Mana Sunset Honeymoon",
    location: "Mana Island",
    destination: "Mana Island",
    price: "FJD 2,680",
    priceNote: "per couple",
    image: images.dealHoneymoon,
  }),
  // Malolo (+4 → 6)
  mkPkg({
    slug: "malolo-turtle-reef-week",
    title: "Malolo Turtle Reef Week",
    location: "Malolo Island",
    destination: "Malolo Island",
    price: "FJD 2,350",
    image: images.mamanuca,
    nights: 7,
  }),
  mkPkg({
    slug: "malolo-romance-package",
    title: "Malolo Romance Package",
    location: "Malolo Island",
    destination: "Malolo Island",
    price: "FJD 2,580",
    priceNote: "per couple",
    image: images.dealHoneymoon,
  }),
  mkPkg({
    slug: "malolo-adventure-package",
    title: "Malolo Adventure Package",
    location: "Malolo Island",
    destination: "Malolo Island",
    price: "FJD 2,120",
    image: images.adventure,
  }),
  mkPkg({
    slug: "malolo-beach-picnic-package",
    title: "Malolo Beach Picnic Package",
    location: "Malolo Island",
    destination: "Malolo Island",
    price: "FJD 1,980",
    image: images.picnic,
  }),
  // Tokoriki (+4 → 6)
  mkPkg({
    slug: "tokoriki-adults-only-week",
    title: "Tokoriki Adults-Only Week",
    location: "Tokoriki Island",
    destination: "Tokoriki Island",
    price: "FJD 3,650",
    image: images.dealLikuliku,
    nights: 7,
  }),
  mkPkg({
    slug: "tokoriki-spa-romance-package",
    title: "Tokoriki Spa Romance Package",
    location: "Tokoriki Island",
    destination: "Tokoriki Island",
    price: "FJD 3,280",
    priceNote: "per couple",
    image: images.dealSpa,
  }),
  mkPkg({
    slug: "tokoriki-beach-bure-escape",
    title: "Tokoriki Beach Bure Escape",
    location: "Tokoriki Island",
    destination: "Tokoriki Island",
    price: "FJD 2,890",
    image: images.dealBeach,
  }),
  mkPkg({
    slug: "tokoriki-helicopter-honeymoon",
    title: "Tokoriki Helicopter Honeymoon",
    location: "Tokoriki Island",
    destination: "Tokoriki Island",
    price: "FJD 4,100",
    priceNote: "per couple",
    image: images.dealHoneymoon,
    nights: 5,
  }),
];

export const fillResorts: Resort[] = [
  // Coral Coast (+5 → 6)
  mkResort({
    slug: "outrigger-fiji-beach-resort",
    title: "Outrigger Fiji Beach Resort",
    location: "Coral Coast",
    priceFrom: "FJD 620",
    image: images.dealBeach,
  }),
  mkResort({
    slug: "warwick-fiji-resort",
    title: "Warwick Fiji Resort & Spa",
    location: "Coral Coast",
    priceFrom: "FJD 580",
    image: images.dealResort,
  }),
  mkResort({
    slug: "natadola-beach-resort",
    title: "Natadola Beach Resort",
    location: "Natadola",
    priceFrom: "FJD 690",
    image: images.dealCoralCoast,
  }),
  mkResort({
    slug: "korotogo-clifftop-retreat-stay",
    title: "Korotogo Clifftop Retreat",
    location: "Korotogo",
    priceFrom: "FJD 540",
    image: images.coralCoast,
  }),
  mkResort({
    slug: "sigatoka-valley-lodge",
    title: "Sigatoka Valley Riverside Lodge",
    location: "Sigatoka",
    priceFrom: "FJD 420",
    image: images.coralCoastCard,
  }),
  // Nadi (+1 → 6)
  mkResort({
    slug: "radisson-blu-nadi",
    title: "Radisson Blu Resort Fiji",
    location: "Nadi",
    priceFrom: "FJD 480",
    image: images.nadi,
  }),
  // Denarau (+3 → 6)
  mkResort({
    slug: "radisson-blu-denarau",
    title: "Radisson Blu Denarau",
    location: "Denarau",
    priceFrom: "FJD 520",
    image: images.denarauCard,
  }),
  mkResort({
    slug: "westin-denarau",
    title: "The Westin Denarau Island",
    location: "Denarau",
    priceFrom: "FJD 590",
    image: images.dealDenarau,
  }),
  mkResort({
    slug: "sheraton-denarau-villas",
    title: "Sheraton Denarau Villas",
    location: "Denarau",
    priceFrom: "FJD 680",
    image: images.dealPool,
  }),
  // Mamanuca (+3 → 6)
  mkResort({
    slug: "treasure-island-resort",
    title: "Treasure Island Resort",
    location: "Mamanuca Islands",
    priceFrom: "FJD 780",
    image: images.dealMamanuca,
  }),
  mkResort({
    slug: "plantation-island-resort",
    title: "Plantation Island Resort",
    location: "Mamanuca Islands",
    priceFrom: "FJD 650",
    image: images.mamanuca,
  }),
  mkResort({
    slug: "lomani-island-resort",
    title: "Lomani Island Resort",
    location: "Mamanuca Islands",
    priceFrom: "FJD 720",
    image: images.mamanucaCard,
  }),
  // Yasawa (+5 → 6)
  mkResort({
    slug: "turtle-island-yasawa",
    title: "Turtle Island",
    location: "Yasawa Islands",
    priceFrom: "FJD 2,400",
    image: images.yasawa,
    stars: 5,
  }),
  mkResort({
    slug: "barefoot-manta-resort",
    title: "Barefoot Manta Resort",
    location: "Yasawa Islands",
    priceFrom: "FJD 890",
    image: images.yasawaCard,
  }),
  mkResort({
    slug: "blue-lagoon-beach-resort",
    title: "Blue Lagoon Beach Resort",
    location: "Yasawa Islands",
    priceFrom: "FJD 620",
    image: images.dealBeach,
  }),
  mkResort({
    slug: "paradise-cove-yasawa",
    title: "Paradise Cove Resort",
    location: "Yasawa Islands",
    priceFrom: "FJD 750",
    image: images.dealOverwater,
  }),
  mkResort({
    slug: "nanuya-levu-lodge",
    title: "Nanuya Levu Island Lodge",
    location: "Yasawa Islands",
    priceFrom: "FJD 980",
    image: images.storyYasawa,
  }),
  // Taveuni (+5 → 6)
  mkResort({
    slug: "garden-island-resort-taveuni",
    title: "Garden Island Resort",
    location: "Taveuni",
    priceFrom: "FJD 520",
    image: images.taveuniHero,
  }),
  mkResort({
    slug: "matangi-island-resort",
    title: "Matangi Private Island Resort",
    location: "Taveuni",
    priceFrom: "FJD 1,450",
    image: images.taveuniCard,
  }),
  mkResort({
    slug: "qamea-resort-spa",
    title: "Qamea Resort & Spa",
    location: "Taveuni",
    priceFrom: "FJD 980",
    image: images.dealSpa,
  }),
  mkResort({
    slug: "taveuni-palms-resort",
    title: "Taveuni Palms Resort",
    location: "Taveuni",
    priceFrom: "FJD 1,120",
    image: images.storyTaveuni,
  }),
  mkResort({
    slug: "maravu-plantation-taveuni",
    title: "Maravu Plantation Lodge",
    location: "Taveuni",
    priceFrom: "FJD 450",
    image: images.culture,
    stars: 4,
  }),
  // Pacific Harbour (+5 → 6)
  mkResort({
    slug: "warwick-pacific-harbour",
    title: "Warwick Fiji on the Pacific Harbour",
    location: "Pacific Harbour",
    priceFrom: "FJD 480",
    image: images.pacificHarbour,
  }),
  mkResort({
    slug: "uprising-beach-resort",
    title: "Uprising Beach Resort",
    location: "Pacific Harbour",
    priceFrom: "FJD 380",
    image: images.dealBeach,
    stars: 4,
  }),
  mkResort({
    slug: "riverside-lodge-pacific-harbour",
    title: "Riverside Adventure Lodge",
    location: "Pacific Harbour",
    priceFrom: "FJD 320",
    image: images.adventure,
    stars: 4,
  }),
  mkResort({
    slug: "beachouse-pacific-harbour",
    title: "Beachouse Resort",
    location: "Pacific Harbour",
    priceFrom: "FJD 350",
    image: images.coralCoast,
    stars: 4,
  }),
  mkResort({
    slug: "navua-riverside-retreat",
    title: "Navua Riverside Retreat",
    location: "Pacific Harbour",
    priceFrom: "FJD 290",
    image: images.storyKayak,
    stars: 4,
  }),
  // Suva (+5 → 6)
  mkResort({
    slug: "holiday-inn-suva",
    title: "Holiday Inn Suva",
    location: "Suva",
    priceFrom: "FJD 280",
    image: images.suva,
    stars: 4,
  }),
  mkResort({
    slug: "novotel-suva",
    title: "Novotel Suva Lami Bay",
    location: "Suva",
    priceFrom: "FJD 320",
    image: images.suvaCard,
    stars: 4,
  }),
  mkResort({
    slug: "quest-suva",
    title: "Quest Suva",
    location: "Suva",
    priceFrom: "FJD 240",
    image: images.nadiCard,
    stars: 4,
  }),
  mkResort({
    slug: "tanoa-plaza-suva",
    title: "Tanoa Plaza Hotel",
    location: "Suva",
    priceFrom: "FJD 220",
    image: images.culture,
    stars: 4,
  }),
  mkResort({
    slug: "suva-harbour-suites",
    title: "Suva Harbour Suites",
    location: "Suva",
    priceFrom: "FJD 310",
    image: images.dealDenarau,
    stars: 4,
  }),
  // Vanua Levu (+5 → 6)
  mkResort({
    slug: "jmcousteau-resort",
    title: "Jean-Michel Cousteau Resort",
    location: "Vanua Levu",
    priceFrom: "FJD 1,280",
    image: images.vanuaLevu,
  }),
  mkResort({
    slug: "dolphin-bay-vanua-levu",
    title: "Dolphin Bay Resort",
    location: "Vanua Levu",
    priceFrom: "FJD 620",
    image: images.snorkel,
  }),
  mkResort({
    slug: "koro-sun-resort",
    title: "Koro Sun Resort",
    location: "Vanua Levu",
    priceFrom: "FJD 540",
    image: images.dealBeach,
  }),
  mkResort({
    slug: "labasa-hotel",
    title: "Grand Eastern Hotel Labasa",
    location: "Vanua Levu",
    priceFrom: "FJD 220",
    image: images.culture,
    stars: 4,
  }),
  mkResort({
    slug: "vanua-levu-eco-lodge",
    title: "Vanua Levu Eco Lodge",
    location: "Vanua Levu",
    priceFrom: "FJD 380",
    image: images.hiking,
    stars: 4,
  }),
  // Savusavu (+5 → 6) — location Savusavu
  mkResort({
    slug: "daku-resort-savusavu",
    title: "Daku Resort",
    location: "Savusavu",
    priceFrom: "FJD 420",
    image: images.vanuaLevu,
    stars: 4,
  }),
  mkResort({
    slug: "savusavu-hot-springs-hotel",
    title: "Savusavu Hot Springs Hotel",
    location: "Savusavu",
    priceFrom: "FJD 350",
    image: images.dealSpa,
    stars: 4,
  }),
  mkResort({
    slug: "koro-sun-savusavu",
    title: "Koro Sun Savusavu",
    location: "Savusavu",
    priceFrom: "FJD 580",
    image: images.dealBeach,
  }),
  mkResort({
    slug: "savusavu-bay-villas",
    title: "Savusavu Bay Villas",
    location: "Savusavu",
    priceFrom: "FJD 720",
    image: images.dealOverwater,
  }),
  mkResort({
    slug: "namale-savusavu-villa",
    title: "Namale Private Villa",
    location: "Savusavu",
    priceFrom: "FJD 1,450",
    image: images.luxury,
  }),
  // Kadavu (+5 → 6)
  mkResort({
    slug: "papageno-kadavu",
    title: "Papageno Resort",
    location: "Kadavu",
    priceFrom: "FJD 520",
    image: images.kadavu,
    stars: 4,
  }),
  mkResort({
    slug: "kokomo-kadavu",
    title: "Kokomo Private Island",
    location: "Kadavu",
    priceFrom: "FJD 2,800",
    image: images.dealPrivateIsland,
  }),
  mkResort({
    slug: "kadavu-eco-cottages",
    title: "Kadavu Eco Cottages",
    location: "Kadavu",
    priceFrom: "FJD 380",
    image: images.storyKayak,
    stars: 4,
  }),
  mkResort({
    slug: "astrolabe-reef-lodge",
    title: "Astrolabe Reef Lodge",
    location: "Kadavu",
    priceFrom: "FJD 450",
    image: images.snorkel,
    stars: 4,
  }),
  mkResort({
    slug: "kadavu-beach-bures",
    title: "Kadavu Beach Bures",
    location: "Kadavu",
    priceFrom: "FJD 490",
    image: images.dealBeach,
    stars: 4,
  }),
  // Beqa (+5 → 6)
  mkResort({
    slug: "beqa-lagoon-villas",
    title: "Beqa Lagoon Villas",
    location: "Beqa Island",
    priceFrom: "FJD 580",
    image: images.dealSharkDive,
  }),
  mkResort({
    slug: "beqa-lalati-resort",
    title: "Lalati Resort & Spa",
    location: "Beqa Island",
    priceFrom: "FJD 720",
    image: images.dealSpa,
  }),
  mkResort({
    slug: "beqa-island-bures",
    title: "Beqa Island Beach Bures",
    location: "Beqa Island",
    priceFrom: "FJD 450",
    image: images.dealBeach,
    stars: 4,
  }),
  mkResort({
    slug: "beqa-cultural-lodge",
    title: "Beqa Cultural Lodge",
    location: "Beqa Island",
    priceFrom: "FJD 380",
    image: images.village,
    stars: 4,
  }),
  mkResort({
    slug: "beqa-shark-dive-lodge",
    title: "Beqa Shark Dive Lodge",
    location: "Beqa Island",
    priceFrom: "FJD 420",
    image: images.adventure,
    stars: 4,
  }),
  // Mana (+5 → 6)
  mkResort({
    slug: "raintree-lodge-mana",
    title: "Raintree Lodge Mana",
    location: "Mana Island",
    priceFrom: "FJD 620",
    image: images.mamanucaCard,
  }),
  mkResort({
    slug: "mana-beachfront-villas",
    title: "Mana Beachfront Villas",
    location: "Mana Island",
    priceFrom: "FJD 750",
    image: images.dealBeach,
  }),
  mkResort({
    slug: "mana-lagoon-suites",
    title: "Mana Lagoon Suites",
    location: "Mana Island",
    priceFrom: "FJD 690",
    image: images.dealPool,
  }),
  mkResort({
    slug: "mana-reef-bures",
    title: "Mana Reef Bures",
    location: "Mana Island",
    priceFrom: "FJD 580",
    image: images.snorkel,
    stars: 4,
  }),
  mkResort({
    slug: "mana-island-villas",
    title: "Mana Island Private Villas",
    location: "Mana Island",
    priceFrom: "FJD 820",
    image: images.dealOverwater,
  }),
  // Malolo (+5 → 6)
  mkResort({
    slug: "funky-fish-malolo",
    title: "Funky Fish Beach Resort",
    location: "Malolo Island",
    priceFrom: "FJD 480",
    image: images.mamanuca,
    stars: 4,
  }),
  mkResort({
    slug: "malolo-beach-villas",
    title: "Malolo Beach Villas",
    location: "Malolo Island",
    priceFrom: "FJD 720",
    image: images.dealBeach,
  }),
  mkResort({
    slug: "malolo-lagoon-bures",
    title: "Malolo Lagoon Bures",
    location: "Malolo Island",
    priceFrom: "FJD 650",
    image: images.dealMamanuca,
  }),
  mkResort({
    slug: "malolo-private-retreat",
    title: "Malolo Private Retreat",
    location: "Malolo Island",
    priceFrom: "FJD 890",
    image: images.luxury,
  }),
  mkResort({
    slug: "malolo-turtle-cove",
    title: "Malolo Turtle Cove",
    location: "Malolo Island",
    priceFrom: "FJD 780",
    image: images.snorkel,
  }),
  // Tokoriki (+6 → 6)
  mkResort({
    slug: "tokoriki-island-resort-stay",
    title: "Tokoriki Island Resort",
    location: "Tokoriki Island",
    priceFrom: "FJD 1,200",
    image: images.resortTokoriki,
  }),
  mkResort({
    slug: "tokoriki-beachfront-bures",
    title: "Tokoriki Beachfront Bures",
    location: "Tokoriki Island",
    priceFrom: "FJD 1,350",
    image: images.dealHoneymoon,
  }),
  mkResort({
    slug: "tokoriki-ocean-villas",
    title: "Tokoriki Ocean Villas",
    location: "Tokoriki Island",
    priceFrom: "FJD 1,480",
    image: images.dealOverwater,
  }),
  mkResort({
    slug: "tokoriki-spa-suites",
    title: "Tokoriki Spa Suites",
    location: "Tokoriki Island",
    priceFrom: "FJD 1,280",
    image: images.dealSpa,
  }),
  mkResort({
    slug: "tokoriki-honeymoon-bure",
    title: "Tokoriki Honeymoon Bure",
    location: "Tokoriki Island",
    priceFrom: "FJD 1,650",
    image: images.dealLikuliku,
  }),
  mkResort({
    slug: "tokoriki-private-villa",
    title: "Tokoriki Private Villa",
    location: "Tokoriki Island",
    priceFrom: "FJD 1,890",
    image: images.luxury,
  }),
];

export { CORAL_COAST_BASELINE };
