import { images } from "@/lib/images";
import type { Experience } from "./types";

export const experiences: Experience[] = [
  {
    slug: "snorkelling-crystal-waters",
    title: "Snorkelling in Crystal Waters",
    location: "Mamanuca Islands",
    category: "Water",
    duration: "Half Day",
    ages: "All ages",
    priceFrom: "FJD 189",
    rating: { score: "4.9", count: 320 },
    heroImage: images.experienceSnorkel,
    overview:
      "Glide over rainbow coral gardens in the Mamanuca's clearest lagoons with a private guide, premium gear and a champagne picnic on a deserted sandbank.",
    highlights: ["Private guide", "Premium snorkel gear", "Champagne picnic", "Marine biologist briefing"],
    included: ["Return boat transfer", "Snorkel equipment", "Refreshments", "Marine park fees"],
    itinerary: ["Denarau marina departure", "Two snorkel sites", "Sandbank picnic", "Return sunset cruise"],
    faqs: [
      { question: "Do I need experience?", answer: "No — suitable for beginners with basic swimming ability." },
      { question: "What should I bring?", answer: "Reef-safe sunscreen, swimwear and a light cover-up." },
    ],
    relatedSlugs: ["sunset-cruises", "village-tours", "island-hopping"],
  },
  {
    slug: "sunset-cruises",
    title: "Sunset Cruises",
    location: "Denarau",
    category: "Sailing",
    duration: "2–3 Hours",
    ages: "All ages",
    priceFrom: "FJD 145",
    rating: { score: "4.8", count: 210 },
    heroImage: images.experienceSunsetCruise,
    overview:
      "Sail into a golden Pacific sunset aboard a luxury catamaran with canapés, premium drinks and live Fijian guitar as the Mamanuca silhouettes fade into twilight.",
    highlights: ["Luxury catamaran", "Canapés & drinks", "Live music", "360° sunset views"],
    included: ["Welcome drink", "Canapé selection", "Return transfer option"],
    itinerary: ["Marina boarding", "Coastal sail", "Sunset toast", "Return under stars"],
    faqs: [{ question: "Is it weather dependent?", answer: "Cruises operate in most conditions; full refund if cancelled for safety." }],
    relatedSlugs: ["snorkelling-crystal-waters", "island-hopping", "village-tours"],
  },
  {
    slug: "hiking-waterfalls",
    title: "Hiking & Waterfalls",
    location: "Taveuni",
    category: "Adventure",
    duration: "Full Day",
    ages: "16+",
    priceFrom: "FJD 220",
    rating: { score: "4.9", count: 156 },
    heroImage: images.experienceHiking,
    overview:
      "Trek through Bouma National Heritage Park to hidden waterfalls, swim in emerald pools and lunch on tropical fruit in the Garden Island's pristine rainforest.",
    highlights: ["Expert local guide", "Three waterfall swim stops", "Rainforest ecology", "Farm-to-table lunch"],
    included: ["Park fees", "Guide", "Lunch", "Transfers from resort"],
    itinerary: ["Morning forest trek", "Waterfall swims", "Village lunch", "Afternoon return"],
    faqs: [{ question: "Fitness level?", answer: "Moderate — 4–5 hours on uneven trails with some steep sections." }],
    relatedSlugs: ["snorkelling-crystal-waters", "village-tours", "island-hopping"],
  },
  {
    slug: "village-tours",
    title: "Village Tours",
    location: "Coral Coast",
    category: "Culture",
    duration: "Half Day",
    ages: "All ages",
    priceFrom: "FJD 95",
    rating: { score: "4.9", count: 280 },
    heroImage: images.experienceVillageTour,
    overview:
      "Experience authentic Fijian hospitality — kava ceremony, meke dance, craft demonstrations and a traditional lovo feast prepared by the village chief's family.",
    highlights: ["Kava ceremony", "Meke performance", "Lovo feast", "Craft workshop"],
    included: ["Village donation", "Ceremony participation", "Traditional lunch", "Transport"],
    itinerary: ["Village welcome", "Kava & meke", "Craft demo", "Lovo lunch"],
    faqs: [{ question: "What should I wear?", answer: "Modest clothing covering shoulders and knees. Remove hats in the village." }],
    relatedSlugs: ["snorkelling-crystal-waters", "sunset-cruises", "hiking-waterfalls"],
  },
  {
    slug: "natadola-lagoon-snorkel",
    title: "Natadola Lagoon Snorkelling",
    location: "Natadola, Coral Coast",
    category: "Water",
    duration: "Half Day",
    ages: "All ages",
    priceFrom: "FJD 165",
    rating: { score: "4.9", count: 198 },
    heroImage: images.snorkel,
    overview:
      "Explore Fiji's finest family lagoon — shallow reef pools, tropical fish and white-sand shallows with a private guide and premium snorkel gear on Natadola Beach.",
    highlights: ["Shallow reef pools", "Private guide", "Premium gear", "Beach picnic"],
    included: ["Snorkel equipment", "Guide", "Refreshments", "Beach transfer"],
    itinerary: ["Resort pickup", "Reef briefing", "Guided snorkel", "Beach relaxation"],
    faqs: [{ question: "Is it suitable for children?", answer: "Yes — Natadola's gentle lagoon is ideal for first-time snorkellers." }],
    relatedSlugs: ["village-tours", "sigatoka-river-safari", "natadola-beach-horse-riding"],
  },
  {
    slug: "sigatoka-river-safari",
    title: "Sigatoka River Safari",
    location: "Sigatoka River, Coral Coast",
    category: "Adventure",
    duration: "Full Day",
    ages: "8+",
    priceFrom: "FJD 245",
    rating: { score: "4.8", count: 142 },
    heroImage: images.storyKayak,
    overview:
      "Jet-boat up the green Sigatoka River to remote hillside villages — kava welcomes, craft demonstrations and a traditional lovo lunch with river valley views.",
    highlights: ["Jet-boat river cruise", "Remote village visit", "Kava ceremony", "Lovo lunch"],
    included: ["Jet-boat transfer", "Village guide", "Traditional lunch", "Hotel pickup"],
    itinerary: ["River jet-boat", "Village welcome", "Craft & culture", "Lovo feast"],
    faqs: [{ question: "What should I wear?", answer: "Comfortable clothes, sun hat and shoes you don't mind getting wet on the boat." }],
    relatedSlugs: ["village-tours", "natadola-lagoon-snorkel", "sigatoka-sand-dunes"],
  },
  {
    slug: "kula-wildlife-park",
    title: "Kula Eco Park",
    location: "Korotogo, Coral Coast",
    category: "Family",
    duration: "Half Day",
    ages: "All ages",
    priceFrom: "FJD 75",
    rating: { score: "4.7", count: 310 },
    heroImage: images.culture,
    overview:
      "Hands-on conservation on the Coral Coast — native iguanas, reef walks, bird encounters and educational trails perfect for families south of Sigatoka.",
    highlights: ["Native wildlife", "Reef walk", "Conservation talks", "Family-friendly"],
    included: ["Park entry", "Guided walk", "Reef trail", "Transfers on request"],
    itinerary: ["Park arrival", "Wildlife trail", "Reef walk", "Free exploration"],
    faqs: [{ question: "How long do we need?", answer: "Allow 2–3 hours to enjoy the trails and reef walk at a relaxed pace." }],
    relatedSlugs: ["natadola-lagoon-snorkel", "village-tours", "natadola-beach-horse-riding"],
  },
  {
    slug: "natadola-beach-horse-riding",
    title: "Natadola Beach Horse Riding",
    location: "Natadola, Coral Coast",
    category: "Adventure",
    duration: "2 Hours",
    ages: "12+",
    priceFrom: "FJD 185",
    rating: { score: "4.9", count: 167 },
    heroImage: images.coralCoast,
    overview:
      "Canter along Natadola's sweeping white-sand beach at sunrise or sunset — one of the South Pacific's most cinematic riding experiences with expert guides.",
    highlights: ["Beach riding", "Sunrise & sunset slots", "Expert guides", "All skill levels"],
    included: ["Horse & tack", "Guide", "Safety briefing", "Resort transfer"],
    itinerary: ["Stable briefing", "Beach ride", "Photo stops", "Return"],
    faqs: [{ question: "Beginner friendly?", answer: "Yes — guides match horses to your experience level." }],
    relatedSlugs: ["natadola-lagoon-snorkel", "village-tours", "sigatoka-sand-dunes"],
  },
  {
    slug: "sigatoka-sand-dunes",
    title: "Sigatoka Sand Dunes Trek",
    location: "Sigatoka Sand Dunes, Coral Coast",
    category: "Nature",
    duration: "Half Day",
    ages: "10+",
    priceFrom: "FJD 120",
    rating: { score: "4.8", count: 89 },
    heroImage: images.adventure,
    overview:
      "Hike Fiji's first national park — ancient dunes, archaeological sites and panoramic views over the Sigatoka River mouth and Coral Coast coastline.",
    highlights: ["National park trek", "Archaeological sites", "Coastal views", "Expert naturalist"],
    included: ["Park fees", "Guide", "Water", "Transport"],
    itinerary: ["Park entrance", "Dune trek", "Viewpoint", "Return"],
    faqs: [{ question: "Fitness level?", answer: "Easy to moderate — sandy paths with some inclines; allow 2–3 hours." }],
    relatedSlugs: ["sigatoka-river-safari", "village-tours", "kula-wildlife-park"],
  },
  {
    slug: "sabeto-mud-pools",
    title: "Sabeto Mud Pools & Hot Springs",
    location: "Sabeto, Nadi",
    category: "Wellness",
    duration: "Half Day",
    ages: "All ages",
    priceFrom: "FJD 85",
    rating: { score: "4.8", count: 245 },
    heroImage: images.wellness,
    overview:
      "Rejuvenate in natural thermal mud pools and hot springs beneath the Sabeto Mountains — a quintessential Nadi experience with village guides and tropical garden surrounds.",
    highlights: ["Natural mud baths", "Hot spring soak", "Village guides", "Mountain views"],
    included: ["Village guide", "Towels", "Changing facilities", "Hotel transfers"],
    itinerary: ["Sabeto valley drive", "Mud pool ritual", "Hot spring soak", "Return to Nadi"],
    faqs: [
      {
        question: "What should I bring?",
        answer: "Swimwear, old clothes you don't mind getting muddy, and reef-safe sunscreen.",
      },
    ],
    relatedSlugs: ["sleeping-giant-gardens", "sri-siva-temple-tour", "highland-village-nadi"],
  },
  {
    slug: "sleeping-giant-gardens",
    title: "Garden of the Sleeping Giant",
    location: "Nadi",
    category: "Nature",
    duration: "2–3 Hours",
    ages: "All ages",
    priceFrom: "FJD 65",
    rating: { score: "4.9", count: 178 },
    heroImage: images.storyNadi,
    overview:
      "Wander orchid trails and lily ponds in Raymond Burr's legendary Nadi gardens — a serene escape at the foot of the Sleeping Giant mountain ridge.",
    highlights: ["Orchid collections", "Rainforest canopy walk", "Lily ponds", "Photography stops"],
    included: ["Garden entry", "Self-guided map", "Transfers on request"],
    itinerary: ["Garden arrival", "Orchid trail", "Canopy walk", "Lily pond circuit"],
    faqs: [
      {
        question: "Best time to visit?",
        answer: "Morning offers cooler temperatures and the best light for photography.",
      },
    ],
    relatedSlugs: ["sabeto-mud-pools", "sri-siva-temple-tour", "nadi-market-cultural-tour"],
  },
  {
    slug: "sri-siva-temple-tour",
    title: "Sri Siva Subramaniya Temple",
    location: "Nadi",
    category: "Culture",
    duration: "2 Hours",
    ages: "All ages",
    priceFrom: "FJD 55",
    rating: { score: "4.9", count: 312 },
    heroImage: images.culture,
    overview:
      "Explore the largest Hindu temple in the Southern Hemisphere — Dravidian architecture, vivid frescoes and guided insight into Fiji's multicultural spiritual heritage.",
    highlights: ["Dravidian architecture", "Guided commentary", "Cultural context", "Photography"],
    included: ["Guide", "Temple etiquette briefing", "Transfers on request"],
    itinerary: ["Welcome briefing", "Temple tour", "Art & architecture", "Q&A"],
    faqs: [
      {
        question: "What should I wear?",
        answer: "Modest clothing covering shoulders and knees. Remove shoes before entering the temple.",
      },
    ],
    relatedSlugs: ["nadi-market-cultural-tour", "sleeping-giant-gardens", "village-tours"],
  },
  {
    slug: "nadi-market-cultural-tour",
    title: "Nadi Market & Cultural Tour",
    location: "Nadi",
    category: "Culture",
    duration: "Half Day",
    ages: "All ages",
    priceFrom: "FJD 75",
    rating: { score: "4.7", count: 156 },
    heroImage: images.storyNadi,
    overview:
      "Taste tropical produce, spices and Indian-Fijian street food at Nadi's bustling markets with a local guide who shares stories of the town's multicultural soul.",
    highlights: ["Market tastings", "Spice & produce", "Local guide", "Craft stalls"],
    included: ["Guide", "Market tastings", "Bottled water"],
    itinerary: ["Market walk", "Food tastings", "Craft browsing", "Return"],
    faqs: [
      {
        question: "Is food included?",
        answer: "Light tastings are included; additional purchases are at your own expense.",
      },
    ],
    relatedSlugs: ["sri-siva-temple-tour", "sabeto-mud-pools", "sunset-cruises"],
  },
  {
    slug: "mamanuca-day-cruise-nadi",
    title: "Mamanuca Islands Day Cruise",
    location: "Nadi & Denarau",
    category: "Sailing",
    duration: "Full Day",
    ages: "All ages",
    priceFrom: "FJD 195",
    rating: { score: "4.9", count: 428 },
    heroImage: images.islandHop,
    overview:
      "Depart Denarau Marina for a full-day Mamanuca cruise — snorkel stops, beach BBQ lunch and island time on Fiji's most photogenic lagoons.",
    highlights: ["Marina departure", "Snorkel stops", "Beach BBQ", "Island time"],
    included: ["Cruise", "Lunch", "Snorkel gear", "Denarau transfers"],
    itinerary: ["Marina boarding", "Snorkel site one", "Beach BBQ", "Second island stop"],
    faqs: [
      {
        question: "Where does it depart?",
        answer: "Port Denarau Marina — complimentary transfers from Nadi hotels can be arranged.",
      },
    ],
    relatedSlugs: ["snorkelling-crystal-waters", "sunset-cruises", "island-hopping"],
  },
  {
    slug: "highland-village-nadi",
    title: "Highland Village Experience",
    location: "Nadi Highlands",
    category: "Culture",
    duration: "Full Day",
    ages: "All ages",
    priceFrom: "FJD 165",
    rating: { score: "4.9", count: 134 },
    heroImage: images.village,
    overview:
      "Journey into the Nadi highlands for an authentic village welcome — kava ceremony, lovo feast and panoramic views over Viti Levu's lush interior.",
    highlights: ["Kava ceremony", "Lovo feast", "Highland views", "Village crafts"],
    included: ["Village guide", "Traditional lunch", "Ceremony participation", "Transport"],
    itinerary: ["Highland drive", "Village welcome", "Kava & meke", "Lovo lunch"],
    faqs: [
      {
        question: "What should I bring?",
        answer: "Modest clothing, a light jacket for the highlands and a small village gift (kava root) is appreciated.",
      },
    ],
    relatedSlugs: ["sabeto-mud-pools", "village-tours", "sri-siva-temple-tour"],
  },
  {
    slug: "island-hopping",
    title: "Island Hopping Adventure",
    location: "Mamanuca & Yasawa",
    category: "Multi-day",
    duration: "3–7 Days",
    ages: "All ages",
    priceFrom: "FJD 890",
    rating: { score: "4.9", count: 412 },
    heroImage: images.islandHop,
    overview:
      "Curated multi-island journey by private speedboat or seaplane — boutique resorts, hidden beaches and bespoke experiences tailored by your concierge.",
    highlights: ["Private transfers", "Boutique resort stays", "Flexible itinerary", "Dedicated concierge"],
    included: ["Inter-island transfers", "Resort coordination", "Daily breakfast", "Concierge support"],
    itinerary: ["Day 1: Mamanuca arrival", "Day 2–3: Yasawa exploration", "Day 4+: Custom extensions"],
    faqs: [
      {
        question: "Can I customise?",
        answer: "Every island-hop is bespoke — your concierge designs the route with you.",
      },
      {
        question: "How far in advance should I book?",
        answer:
          "Luxury resorts fill quickly in peak season (June–September). Book 3–6 months ahead when you can — our concierge often secures last-minute availability with partner resorts.",
      },
      {
        question: "How do I get between islands?",
        answer:
          "Private speedboat, resort transfers or seaplane — we coordinate every leg and meet you at Denarau Marina or your arrival airport.",
      },
      {
        question: "Are resort stays included?",
        answer:
          "Yes — nightly boutique resort accommodation, daily breakfast and inter-island transfers are coordinated as part of your package. Spa, diving and extras are arranged à la carte.",
      },
      {
        question: "Is island-hopping suitable for families?",
        answer:
          "Absolutely. We match family-friendly resorts, shallow lagoons and age-appropriate activities across Mamanuca and Yasawa.",
      },
    ],
    relatedSlugs: ["snorkelling-crystal-waters", "sunset-cruises", "hiking-waterfalls"],
  },
  {
    slug: "sabeto-mud-pools",
    title: "Sabeto Mud Pools & Hot Springs",
    location: "Nadi",
    category: "Culture",
    duration: "Half Day",
    ages: "All ages",
    priceFrom: "FJD 85",
    rating: { score: "4.8", count: 240 },
    heroImage: images.village,
    overview:
      "Therapeutic mud baths and natural hot springs at the foot of the Sabeto Mountains — a quintessential Nadi ritual with village guides and tropical garden surrounds.",
    highlights: ["Natural hot springs", "Mud bath ritual", "Village guides", "Garden setting"],
    included: ["Guide", "Towels", "Transport", "Refreshments"],
    itinerary: ["Hotel pickup", "Mud pools", "Hot spring soak", "Return"],
    faqs: [{ question: "What to bring?", answer: "Swimwear, old clothes and reef-safe sunscreen." }],
    relatedSlugs: ["village-tours", "sunset-cruises", "snorkelling-crystal-waters"],
  },
  {
    slug: "garden-of-the-sleeping-giant",
    title: "Garden of the Sleeping Giant",
    location: "Nadi",
    category: "Nature",
    duration: "2 Hours",
    ages: "All ages",
    priceFrom: "FJD 65",
    rating: { score: "4.7", count: 190 },
    heroImage: images.wellness,
    overview:
      "Wander orchid trails and lily ponds at Raymond Burr's legendary Nadi garden — shaded boardwalks, tropical blooms and a serene escape minutes from the airport.",
    highlights: ["Orchid collections", "Shaded trails", "Lily ponds", "Photography stops"],
    included: ["Garden entry", "Guide", "Transport option"],
    itinerary: ["Garden arrival", "Guided walk", "Free exploration", "Return"],
    faqs: [{ question: "How long to allow?", answer: "1.5–2 hours at a relaxed pace." }],
    relatedSlugs: ["sabeto-mud-pools", "village-tours", "sunset-cruises"],
  },
  {
    slug: "nadi-temple-cultural-tour",
    title: "Sri Siva Subramaniya Temple Tour",
    location: "Nadi",
    category: "Culture",
    duration: "2 Hours",
    ages: "All ages",
    priceFrom: "FJD 55",
    rating: { score: "4.9", count: 175 },
    heroImage: images.culture,
    overview:
      "Guided visit to the Southern Hemisphere's largest Hindu temple — intricate Dravidian architecture, cultural context and Nadi's multicultural story.",
    highlights: ["Temple architecture", "Cultural guide", "Photo opportunities", "Modest dress guidance"],
    included: ["Guide", "Temple donation", "Transport"],
    itinerary: ["Temple welcome", "Guided tour", "Q&A", "Return"],
    faqs: [{ question: "Dress code?", answer: "Shoulders and knees covered; sarongs provided if needed." }],
    relatedSlugs: ["garden-of-the-sleeping-giant", "sabeto-mud-pools", "village-tours"],
  },
  {
    slug: "denarau-marina-island-day",
    title: "Denarau Marina Island Day Trip",
    location: "Nadi",
    category: "Water",
    duration: "Full Day",
    ages: "All ages",
    priceFrom: "FJD 195",
    rating: { score: "4.8", count: 220 },
    heroImage: images.denarau,
    overview:
      "Full-day Mamanuca sampler from Nadi — speedboat transfers, snorkel stops, beach lunch and resort island time coordinated from Denarau Marina.",
    highlights: ["Speedboat transfers", "Snorkel stops", "Beach lunch", "Resort island time"],
    included: ["Boat transfers", "Snorkel gear", "Lunch", "Nadi pickup"],
    itinerary: ["Nadi pickup", "Marina departure", "Island snorkel", "Beach lunch", "Return"],
    faqs: [{ question: "Hotel pickup?", answer: "Included from Nadi and Denarau hotels." }],
    relatedSlugs: ["snorkelling-crystal-waters", "sunset-cruises", "island-hopping"],
  },
  {
    slug: "denarau-championship-golf",
    title: "Denarau Championship Golf",
    location: "Denarau",
    category: "Adventure",
    duration: "Half Day",
    ages: "16+",
    priceFrom: "FJD 210",
    rating: { score: "4.8", count: 134 },
    heroImage: images.dealDenarau,
    overview:
      "Play Denarau's championship fairways with ocean views — tee times, club rental and resort transfers arranged for visiting golfers.",
    highlights: ["Championship course", "Ocean views", "Club rental", "Resort transfers"],
    included: ["Green fees", "Cart", "Club rental option", "Transfers"],
    itinerary: ["Resort pickup", "Practice range", "18 holes", "Clubhouse refreshment"],
    faqs: [{ question: "Handicap required?", answer: "Recommended but not mandatory for resort guests." }],
    relatedSlugs: ["sunset-cruises", "snorkelling-crystal-waters", "denarau-marina-island-day"],
  },
  {
    slug: "denarau-jet-ski-safari",
    title: "Denarau Jet Ski Safari",
    location: "Denarau",
    category: "Water",
    duration: "2 Hours",
    ages: "16+",
    priceFrom: "FJD 175",
    rating: { score: "4.7", count: 156 },
    heroImage: images.dealMamanuca,
    overview:
      "Guided jet ski circuit from Denarau Marina — lagoon runs, island viewpoints and safety briefing with premium ski fleet.",
    highlights: ["Guided safari", "Lagoon circuit", "Island viewpoints", "Safety briefing"],
    included: ["Jet ski", "Guide", "Safety gear", "Briefing"],
    itinerary: ["Marina briefing", "Lagoon circuit", "Photo stop", "Return"],
    faqs: [{ question: "Experience needed?", answer: "Beginners welcome after safety briefing." }],
    relatedSlugs: ["sunset-cruises", "snorkelling-crystal-waters", "denarau-championship-golf"],
  },
  {
    slug: "yasawa-blue-lagoon-caves",
    title: "Sawa-i-Lau Blue Lagoon Caves",
    location: "Yasawa Islands",
    category: "Adventure",
    duration: "Full Day",
    ages: "10+",
    priceFrom: "FJD 280",
    rating: { score: "4.9", count: 188 },
    heroImage: images.yasawa,
    overview:
      "Swim through cathedral caves and turquoise chambers at Sawa-i-Lau — the Yasawa's most iconic day expedition with boat transfers and guided cave entry.",
    highlights: ["Cave swimming", "Blue Lagoon", "Boat expedition", "Expert guides"],
    included: ["Boat transfer", "Guide", "Snorkel gear", "Lunch"],
    itinerary: ["Island pickup", "Cave briefing", "Swim chambers", "Lagoon lunch"],
    faqs: [{ question: "Swimming ability?", answer: "Confident swimmers recommended for inner chambers." }],
    relatedSlugs: ["island-hopping", "yasawa-village-homestay", "snorkelling-crystal-waters"],
  },
  {
    slug: "yasawa-village-homestay",
    title: "Yasawa Village Homestay Day",
    location: "Yasawa Islands",
    category: "Culture",
    duration: "Full Day",
    ages: "All ages",
    priceFrom: "FJD 165",
    rating: { score: "4.9", count: 142 },
    heroImage: images.village,
    overview:
      "Authentic village day in the remote Yasawas — kava ceremony, lovo lunch, craft demonstrations and stories from community hosts.",
    highlights: ["Village homestay", "Kava ceremony", "Lovo feast", "Craft workshop"],
    included: ["Village donation", "Lunch", "Guide", "Boat transfer"],
    itinerary: ["Village welcome", "Kava & meke", "Craft demo", "Lovo lunch"],
    faqs: [{ question: "What to wear?", answer: "Modest clothing; remove hats in the village." }],
    relatedSlugs: ["yasawa-blue-lagoon-caves", "island-hopping", "village-tours"],
  },
  {
    slug: "yasawa-sea-kayaking",
    title: "Yasawa Sea Kayaking",
    location: "Yasawa Islands",
    category: "Water",
    duration: "Half Day",
    ages: "12+",
    priceFrom: "FJD 145",
    rating: { score: "4.8", count: 98 },
    heroImage: images.storyYasawa,
    overview:
      "Paddle crystal Yasawa bays with a guide — hidden coves, reef edges and beach landings on a half-day kayak adventure.",
    highlights: ["Guided kayaking", "Hidden coves", "Reef edges", "Beach landings"],
    included: ["Kayak & paddle", "Guide", "Safety gear", "Refreshments"],
    itinerary: ["Beach briefing", "Coastal paddle", "Snorkel stop", "Return"],
    faqs: [{ question: "Fitness level?", answer: "Moderate — 2–3 hours paddling with breaks." }],
    relatedSlugs: ["yasawa-blue-lagoon-caves", "snorkelling-crystal-waters", "island-hopping"],
  },
  {
    slug: "yasawa-sunset-sail",
    title: "Yasawa Sunset Sail",
    location: "Yasawa Islands",
    category: "Sailing",
    duration: "3 Hours",
    ages: "All ages",
    priceFrom: "FJD 195",
    rating: { score: "4.9", count: 112 },
    heroImage: images.dealSunsetCruise,
    overview:
      "Private sunset sail between Yasawa islands — canapés, champagne toast and volcanic silhouettes as the Pacific turns gold.",
    highlights: ["Private sail", "Sunset toast", "Canapés", "Island silhouettes"],
    included: ["Welcome drink", "Canapés", "Skipper & crew"],
    itinerary: ["Boarding", "Coastal sail", "Sunset toast", "Return"],
    faqs: [{ question: "Weather cancellations?", answer: "Full reschedule or refund if unsafe conditions." }],
    relatedSlugs: ["yasawa-sea-kayaking", "sunset-cruises", "yasawa-blue-lagoon-caves"],
  },
  {
    slug: "rainbow-reef-dive-day",
    title: "Rainbow Reef Dive Day",
    location: "Taveuni",
    category: "Water",
    duration: "Full Day",
    ages: "16+",
    priceFrom: "FJD 320",
    rating: { score: "4.95", count: 204 },
    heroImage: images.dealSharkDive,
    overview:
      "Two-tank dive day on the Great White Wall and Rainbow Reef — world-class soft coral, expert divemasters and resort boat transfers.",
    highlights: ["Rainbow Reef", "Great White Wall", "Two-tank dive", "Expert divemasters"],
    included: ["Tanks & weights", "Boat", "Lunch", "Divemaster"],
    itinerary: ["Morning briefing", "First dive", "Surface interval", "Second dive"],
    faqs: [{ question: "Certification?", answer: "Open Water minimum; Advanced recommended for deeper sites." }],
    relatedSlugs: ["hiking-waterfalls", "taveuni-birdwatching", "lavena-coastal-walk"],
  },
  {
    slug: "taveuni-birdwatching",
    title: "Taveuni Birdwatching Trail",
    location: "Taveuni",
    category: "Nature",
    duration: "Half Day",
    ages: "All ages",
    priceFrom: "FJD 135",
    rating: { score: "4.8", count: 87 },
    heroImage: images.storyTaveuni,
    overview:
      "Track rare silktails and orange doves in Bouma rainforest with a specialist naturalist — the Garden Island's premier birding experience.",
    highlights: ["Silktail sightings", "Specialist guide", "Rainforest trail", "Photography"],
    included: ["Guide", "Park fees", "Binoculars", "Refreshments"],
    itinerary: ["Dawn start", "Forest trail", "Bird hides", "Return"],
    faqs: [{ question: "Best season?", answer: "Year-round; dawn hours offer peak activity." }],
    relatedSlugs: ["hiking-waterfalls", "rainbow-reef-dive-day", "lavena-coastal-walk"],
  },
  {
    slug: "lavena-coastal-walk",
    title: "Lavena Coastal Walk",
    location: "Taveuni",
    category: "Adventure",
    duration: "Full Day",
    ages: "12+",
    priceFrom: "FJD 185",
    rating: { score: "4.9", count: 76 },
    heroImage: images.taveuniCard,
    overview:
      "Coastal trek to Wainibau Falls through Lavena village — river crossings, waterfall swims and village hospitality on Taveuni's wild south coast.",
    highlights: ["Coastal trek", "Wainibau Falls", "River crossings", "Village visit"],
    included: ["Guide", "Village fee", "Lunch", "Transfers"],
    itinerary: ["Trail start", "River crossings", "Waterfall swim", "Village lunch"],
    faqs: [{ question: "Fitness?", answer: "Moderate — 5–6 hours with uneven terrain." }],
    relatedSlugs: ["hiking-waterfalls", "rainbow-reef-dive-day", "taveuni-birdwatching"],
  },
  {
    slug: "beqa-shark-dive-experience",
    title: "Beqa Lagoon Shark Dive",
    location: "Pacific Harbour",
    category: "Water",
    duration: "Half Day",
    ages: "18+",
    priceFrom: "FJD 320",
    rating: { score: "4.9", count: 267 },
    heroImage: images.dealSharkDive,
    overview:
      "World-famous bull shark encounter in Beqa Lagoon — professional guides, full equipment and Pacific Harbour resort transfers.",
    highlights: ["Bull shark dive", "Professional guides", "Full equipment", "Resort transfers"],
    included: ["Equipment", "Guide", "Tanks", "Transfers"],
    itinerary: ["Briefing", "Boat to site", "Shark dive", "Return"],
    faqs: [{ question: "Certification?", answer: "Open Water required; no cage — experienced operators only." }],
    relatedSlugs: ["navua-river-rafting", "zip-fiji-adventure", "hiking-waterfalls"],
  },
  {
    slug: "navua-river-rafting",
    title: "Upper Navua River Rafting",
    location: "Pacific Harbour",
    category: "Adventure",
    duration: "Full Day",
    ages: "14+",
    priceFrom: "FJD 295",
    rating: { score: "4.9", count: 198 },
    heroImage: images.adventure,
    overview:
      "White-water raft the Upper Navua through volcanic canyons — rainforest gorge, waterfall swims and riverside lunch on Fiji's premier rafting day.",
    highlights: ["Grade III rapids", "Volcanic gorge", "Waterfall swim", "Riverside lunch"],
    included: ["Raft & gear", "Guide", "Lunch", "Transfers"],
    itinerary: ["Briefing", "Raft descent", "Waterfall stop", "Lunch", "Return"],
    faqs: [{ question: "Swimming?", answer: "Must be able to swim; life jackets provided." }],
    relatedSlugs: ["beqa-shark-dive-experience", "zip-fiji-adventure", "hiking-waterfalls"],
  },
  {
    slug: "zip-fiji-adventure",
    title: "Zip Fiji Canopy Adventure",
    location: "Pacific Harbour",
    category: "Adventure",
    duration: "Half Day",
    ages: "10+",
    priceFrom: "FJD 185",
    rating: { score: "4.7", count: 145 },
    heroImage: images.hiking,
    overview:
      "Zip-line through rainforest canopy near Pacific Harbour — multiple lines, suspension bridges and guided adrenaline with safety-first operators.",
    highlights: ["Canopy zip-lines", "Suspension bridges", "Rainforest views", "Safety briefing"],
    included: ["Harness & gear", "Guide", "Transfers option"],
    itinerary: ["Safety briefing", "Zip circuit", "Bridge crossings", "Return"],
    faqs: [{ question: "Weight limits?", answer: "Typically 30–120 kg; confirm at booking." }],
    relatedSlugs: ["navua-river-rafting", "beqa-shark-dive-experience", "hiking-waterfalls"],
  },
  {
    slug: "suva-heritage-walk",
    title: "Suva Heritage Walking Tour",
    location: "Suva",
    category: "Culture",
    duration: "Half Day",
    ages: "All ages",
    priceFrom: "FJD 75",
    rating: { score: "4.8", count: 132 },
    heroImage: images.suva,
    overview:
      "Colonial architecture, Parliament precinct and Thurston Gardens — a guided walk through Fiji's capital with local historians.",
    highlights: ["Colonial architecture", "Parliament precinct", "Thurston Gardens", "Local historian"],
    included: ["Guide", "Museum entry option", "City map"],
    itinerary: ["City centre", "Heritage buildings", "Gardens", "Market detour"],
    faqs: [{ question: "Walking distance?", answer: "Approximately 3 km on paved paths." }],
    relatedSlugs: ["suva-municipal-market", "colo-i-suva-forest", "suva-museum-tour"],
  },
  {
    slug: "suva-municipal-market",
    title: "Suva Municipal Market Tour",
    location: "Suva",
    category: "Culture",
    duration: "2 Hours",
    ages: "All ages",
    priceFrom: "FJD 55",
    rating: { score: "4.9", count: 168 },
    heroImage: images.suvaCard,
    overview:
      "Taste tropical produce and spices at Suva's vibrant municipal market — guided tastings, kava stalls and Fijian-Indian street food introductions.",
    highlights: ["Market tastings", "Spice stalls", "Kava introduction", "Street food"],
    included: ["Guide", "Tastings", "Market map"],
    itinerary: ["Market meet", "Produce tour", "Tastings", "Wrap-up"],
    faqs: [{ question: "Dietary needs?", answer: "Vegetarian-friendly; advise allergies at booking." }],
    relatedSlugs: ["suva-heritage-walk", "colo-i-suva-forest", "suva-museum-tour"],
  },
  {
    slug: "colo-i-suva-forest",
    title: "Colo-i-Suva Forest Park",
    location: "Suva",
    category: "Nature",
    duration: "Half Day",
    ages: "All ages",
    priceFrom: "FJD 65",
    rating: { score: "4.7", count: 124 },
    heroImage: images.wellness,
    overview:
      "Swim in emerald forest pools and walk shaded trails at Colo-i-Suva — Suva's rainforest escape minutes from the capital.",
    highlights: ["Forest pools", "Shaded trails", "Birdlife", "Swimming holes"],
    included: ["Park fees", "Guide", "Transport"],
    itinerary: ["Park entry", "Trail walk", "Pool swim", "Return"],
    faqs: [{ question: "What to bring?", answer: "Swimwear, towel and insect repellent." }],
    relatedSlugs: ["suva-heritage-walk", "suva-municipal-market", "suva-museum-tour"],
  },
  {
    slug: "suva-museum-tour",
    title: "Fiji Museum Guided Tour",
    location: "Suva",
    category: "Culture",
    duration: "2 Hours",
    ages: "All ages",
    priceFrom: "FJD 45",
    rating: { score: "4.8", count: 98 },
    heroImage: images.culture,
    overview:
      "Curator-led tour of the Fiji Museum — cannibal forks to sailing canoes, colonial history and contemporary Pacific art in Thurston Gardens.",
    highlights: ["Curator guide", "Pacific artefacts", "Colonial history", "Thurston Gardens"],
    included: ["Museum entry", "Guide"],
    itinerary: ["Museum intro", "Gallery tour", "Gardens stroll"],
    faqs: [{ question: "Photography?", answer: "Allowed in most galleries; flash restricted." }],
    relatedSlugs: ["suva-heritage-walk", "colo-i-suva-forest", "suva-municipal-market"],
  },
  {
    slug: "savusavu-hot-springs",
    title: "Savusavu Hot Springs & Bay",
    location: "Savusavu",
    category: "Nature",
    duration: "Half Day",
    ages: "All ages",
    priceFrom: "FJD 95",
    rating: { score: "4.8", count: 76 },
    heroImage: images.vanuaLevu,
    overview:
      "Natural geothermal springs and Savusavu Bay viewpoints — plantation roads, hot pools and bay panoramas on Vanua Levu's hidden coast.",
    highlights: ["Hot springs", "Bay viewpoints", "Plantation drive", "Natural pools"],
    included: ["Guide", "Transport", "Refreshments"],
    itinerary: ["Savusavu town", "Hot springs", "Bay lookout", "Return"],
    faqs: [{ question: "Swimming?", answer: "Yes in designated warm pools." }],
    relatedSlugs: ["great-sea-reef-snorkel", "wasali-nature-reserve", "vanua-levu-plantation-tour"],
  },
  {
    slug: "great-sea-reef-snorkel",
    title: "Great Sea Reef Snorkel",
    location: "Vanua Levu",
    category: "Water",
    duration: "Full Day",
    ages: "All ages",
    priceFrom: "FJD 265",
    rating: { score: "4.9", count: 89 },
    heroImage: images.snorkel,
    overview:
      "Snorkel the world's third-largest reef system off Vanua Levu — pristine hard coral, reef fish and boat day with marine guide.",
    highlights: ["Great Sea Reef", "Pristine coral", "Marine guide", "Boat day"],
    included: ["Boat", "Snorkel gear", "Lunch", "Guide"],
    itinerary: ["Boat departure", "Reef snorkel", "Lunch", "Second site"],
    faqs: [{ question: "Experience?", answer: "Suitable for confident snorkellers; flotation available." }],
    relatedSlugs: ["savusavu-hot-springs", "wasali-nature-reserve", "vanua-levu-plantation-tour"],
  },
  {
    slug: "wasali-nature-reserve",
    title: "Wasali Nature Reserve Trek",
    location: "Vanua Levu",
    category: "Nature",
    duration: "Half Day",
    ages: "10+",
    priceFrom: "FJD 110",
    rating: { score: "4.7", count: 64 },
    heroImage: images.hiking,
    overview:
      "Rainforest trek in Wasali Nature Reserve — endemic birds, orchids and village guides on Vanua Levu's quiet interior.",
    highlights: ["Rainforest trek", "Endemic birds", "Orchid trail", "Village guides"],
    included: ["Guide", "Park fees", "Water", "Transport"],
    itinerary: ["Trailhead", "Forest trek", "Viewpoint", "Return"],
    faqs: [{ question: "Fitness?", answer: "Easy to moderate — 2–3 hours." }],
    relatedSlugs: ["great-sea-reef-snorkel", "savusavu-hot-springs", "vanua-levu-plantation-tour"],
  },
  {
    slug: "vanua-levu-plantation-tour",
    title: "Vanua Levu Plantation Tour",
    location: "Vanua Levu",
    category: "Culture",
    duration: "Half Day",
    ages: "All ages",
    priceFrom: "FJD 85",
    rating: { score: "4.6", count: 58 },
    heroImage: images.culture,
    overview:
      "Copra and cacao plantation visit with tasting — northern Fiji's agricultural heartland and farm-to-table samples.",
    highlights: ["Plantation visit", "Cacao tasting", "Copra demo", "Farm lunch"],
    included: ["Guide", "Tastings", "Transport"],
    itinerary: ["Plantation tour", "Processing demo", "Tasting", "Return"],
    faqs: [{ question: "Dietary?", answer: "Chocolate and tropical fruit tastings included." }],
    relatedSlugs: ["savusavu-hot-springs", "great-sea-reef-snorkel", "wasali-nature-reserve"],
  },
  {
    slug: "kadavu-great-astrolabe-dive",
    title: "Great Astrolabe Reef Dive",
    location: "Kadavu",
    category: "Water",
    duration: "Full Day",
    ages: "16+",
    priceFrom: "FJD 340",
    rating: { score: "4.95", count: 72 },
    heroImage: images.kadavu,
    overview:
      "Dive the Great Astrolabe Reef from Kadavu — manta channels, pristine walls and intimate dive groups from eco-resort bases.",
    highlights: ["Astrolabe Reef", "Manta channels", "Pristine walls", "Small groups"],
    included: ["Two dives", "Equipment", "Lunch", "Boat"],
    itinerary: ["Briefing", "Morning dive", "Lunch", "Afternoon dive"],
    faqs: [{ question: "Season?", answer: "Manta sightings peak May–Oct." }],
    relatedSlugs: ["kadavu-kayak-coast", "kadavu-village-visit", "kadavu-bird-island"],
  },
  {
    slug: "kadavu-kayak-coast",
    title: "Kadavu Coastal Kayaking",
    location: "Kadavu",
    category: "Adventure",
    duration: "Half Day",
    ages: "12+",
    priceFrom: "FJD 155",
    rating: { score: "4.8", count: 54 },
    heroImage: images.storyKayak,
    overview:
      "Paddle Kadavu's undeveloped coastline — mangrove channels, reef edges and deserted beaches far from the tourist trail.",
    highlights: ["Coastal kayaking", "Mangrove channels", "Reef edges", "Deserted beaches"],
    included: ["Kayak", "Guide", "Safety gear", "Refreshments"],
    itinerary: ["Beach briefing", "Coastal paddle", "Snorkel stop", "Return"],
    faqs: [{ question: "Remoteness?", answer: "Kadavu is accessed by domestic flight or ferry from Suva." }],
    relatedSlugs: ["kadavu-great-astrolabe-dive", "kadavu-village-visit", "kadavu-bird-island"],
  },
  {
    slug: "kadavu-village-visit",
    title: "Kadavu Village Cultural Day",
    location: "Kadavu",
    category: "Culture",
    duration: "Full Day",
    ages: "All ages",
    priceFrom: "FJD 125",
    rating: { score: "4.9", count: 48 },
    heroImage: images.village,
    overview:
      "Traditional village welcome on Kadavu — kava ceremony, reef fishing demo and lovo feast with community hosts.",
    highlights: ["Village welcome", "Kava ceremony", "Reef fishing demo", "Lovo feast"],
    included: ["Village donation", "Lunch", "Guide", "Boat transfer"],
    itinerary: ["Village arrival", "Ceremony", "Activities", "Lovo lunch"],
    faqs: [{ question: "Dress?", answer: "Modest clothing; sulu provided if needed." }],
    relatedSlugs: ["kadavu-great-astrolabe-dive", "kadavu-kayak-coast", "kadavu-bird-island"],
  },
  {
    slug: "kadavu-bird-island",
    title: "Kadavu Bird Island Walk",
    location: "Kadavu",
    category: "Nature",
    duration: "Half Day",
    ages: "All ages",
    priceFrom: "FJD 95",
    rating: { score: "4.7", count: 42 },
    heroImage: images.storyTaveuni,
    overview:
      "Track Kadavu parrots and endemic forest birds on guided rainforest trails — specialist naturalist and island conservation story.",
    highlights: ["Kadavu parrots", "Endemic birds", "Rainforest trail", "Conservation talk"],
    included: ["Naturalist guide", "Park fees", "Refreshments"],
    itinerary: ["Dawn trail", "Bird hides", "Forest walk", "Return"],
    faqs: [{ question: "Best time?", answer: "Early morning for peak bird activity." }],
    relatedSlugs: ["kadavu-great-astrolabe-dive", "kadavu-village-visit", "kadavu-kayak-coast"],
  },
  {
    slug: "beqa-firewalking-ceremony",
    title: "Beqa Firewalking Ceremony",
    location: "Beqa Island",
    category: "Culture",
    duration: "Half Day",
    ages: "All ages",
    priceFrom: "FJD 135",
    rating: { score: "4.9", count: 156 },
    heroImage: images.eventFirewalking,
    overview:
      "Witness legendary Beqa firewalking — village ceremony, meke performance and traditional feast on the island of the fire walkers.",
    highlights: ["Firewalking ceremony", "Meke dance", "Village feast", "Cultural briefing"],
    included: ["Boat transfer", "Ceremony", "Village lunch", "Guide"],
    itinerary: ["Boat to Beqa", "Ceremony", "Meke", "Lovo lunch"],
    faqs: [{ question: "Access?", answer: "Boat transfer from Pacific Harbour area included." }],
    relatedSlugs: ["beqa-lagoon-snorkel", "beqa-village-homestay", "beqa-shark-dive-experience"],
  },
  {
    slug: "beqa-lagoon-snorkel",
    title: "Beqa Lagoon Snorkel",
    location: "Beqa Island",
    category: "Water",
    duration: "Half Day",
    ages: "All ages",
    priceFrom: "FJD 145",
    rating: { score: "4.8", count: 88 },
    heroImage: images.snorkel,
    overview:
      "Reef snorkel in Beqa Lagoon's calm waters — soft coral gardens, reef fish and boat day from Pacific Harbour gateway.",
    highlights: ["Soft coral gardens", "Calm lagoon", "Reef fish", "Boat day"],
    included: ["Boat", "Snorkel gear", "Guide", "Refreshments"],
    itinerary: ["Boat departure", "Reef snorkel", "Beach stop", "Return"],
    faqs: [{ question: "Combine with shark dive?", answer: "Yes — popular two-day adventure packages available." }],
    relatedSlugs: ["beqa-firewalking-ceremony", "beqa-village-homestay", "beqa-shark-dive-experience"],
  },
  {
    slug: "beqa-village-homestay",
    title: "Beqa Village Homestay",
    location: "Beqa Island",
    category: "Culture",
    duration: "Full Day",
    ages: "All ages",
    priceFrom: "FJD 115",
    rating: { score: "4.8", count: 62 },
    heroImage: images.village,
    overview:
      "Day homestay in a Beqa village — fishing demo, craft workshop and traditional lunch with island hosts.",
    highlights: ["Village homestay", "Fishing demo", "Craft workshop", "Traditional lunch"],
    included: ["Village donation", "Lunch", "Boat transfer", "Guide"],
    itinerary: ["Village welcome", "Activities", "Craft", "Lunch"],
    faqs: [{ question: "Overnight stays?", answer: "Available on request through concierge." }],
    relatedSlugs: ["beqa-firewalking-ceremony", "beqa-lagoon-snorkel", "beqa-shark-dive-experience"],
  },
  {
    slug: "mana-island-snorkel-safari",
    title: "Mana Island Snorkel Safari",
    location: "Mana Island",
    category: "Water",
    duration: "Half Day",
    ages: "All ages",
    priceFrom: "FJD 175",
    rating: { score: "4.8", count: 134 },
    heroImage: images.mamanuca,
    overview:
      "Snorkel Mana Island's house reef and nearby sandbanks — family-friendly lagoon, premium gear and resort boat transfers.",
    highlights: ["House reef", "Sandbank stop", "Premium gear", "Family-friendly"],
    included: ["Boat", "Snorkel gear", "Guide", "Refreshments"],
    itinerary: ["Resort pickup", "Reef snorkel", "Sandbank", "Return"],
    faqs: [{ question: "Kids?", answer: "Ideal for families; shallow lagoon areas available." }],
    relatedSlugs: ["mana-island-sunset-cruise", "mana-kayak-lagoon", "snorkelling-crystal-waters"],
  },
  {
    slug: "mana-island-sunset-cruise",
    title: "Mana Island Sunset Cruise",
    location: "Mana Island",
    category: "Sailing",
    duration: "2 Hours",
    ages: "All ages",
    priceFrom: "FJD 125",
    rating: { score: "4.7", count: 98 },
    heroImage: images.dealSunsetCruise,
    overview:
      "Sunset sail around Mana Island — canapés, tropical drinks and Mamanuca silhouettes from your resort base.",
    highlights: ["Sunset sail", "Canapés", "Tropical drinks", "Lagoon views"],
    included: ["Drinks", "Canapés", "Crew"],
    itinerary: ["Boarding", "Lagoon sail", "Sunset toast", "Return"],
    faqs: [{ question: "Weather?", answer: "Operates most evenings; reschedule if unsafe." }],
    relatedSlugs: ["mana-island-snorkel-safari", "mana-kayak-lagoon", "sunset-cruises"],
  },
  {
    slug: "mana-kayak-lagoon",
    title: "Mana Lagoon Kayaking",
    location: "Mana Island",
    category: "Water",
    duration: "2 Hours",
    ages: "8+",
    priceFrom: "FJD 95",
    rating: { score: "4.7", count: 76 },
    heroImage: images.storyKayak,
    overview:
      "Kayak Mana's calm lagoon at sunrise — reef edges, tropical fish and guided paddle for all skill levels.",
    highlights: ["Sunrise paddle", "Calm lagoon", "Reef edges", "All levels"],
    included: ["Kayak", "Guide", "Safety gear"],
    itinerary: ["Beach briefing", "Lagoon paddle", "Return"],
    faqs: [{ question: "Beginners?", answer: "Yes — calm lagoon ideal for first-time kayakers." }],
    relatedSlugs: ["mana-island-snorkel-safari", "mana-island-sunset-cruise", "snorkelling-crystal-waters"],
  },
  {
    slug: "malolo-island-resort-snorkel",
    title: "Malolo Island Reef Snorkel",
    location: "Malolo Island",
    category: "Water",
    duration: "Half Day",
    ages: "All ages",
    priceFrom: "FJD 165",
    rating: { score: "4.8", count: 112 },
    heroImage: images.dealMamanuca,
    overview:
      "Explore Malolo's fringing reef — turtle sightings, tropical fish and guided snorkel from island resort bases.",
    highlights: ["Fringing reef", "Turtle sightings", "Guided snorkel", "Resort access"],
    included: ["Snorkel gear", "Guide", "Boat option", "Refreshments"],
    itinerary: ["Reef briefing", "Guided snorkel", "Free swim", "Return"],
    faqs: [{ question: "Turtles?", answer: "Frequent sightings; never touch marine life." }],
    relatedSlugs: ["malolo-island-hike", "malolo-beach-picnic", "snorkelling-crystal-waters"],
  },
  {
    slug: "malolo-island-hike",
    title: "Malolo Island Ridge Hike",
    location: "Malolo Island",
    category: "Adventure",
    duration: "Half Day",
    ages: "12+",
    priceFrom: "FJD 120",
    rating: { score: "4.7", count: 68 },
    heroImage: images.hiking,
    overview:
      "Ridge hike across Malolo with panoramic Mamanuca views — guided trail, coconut plantations and summit lookout.",
    highlights: ["Ridge trail", "Panoramic views", "Plantation walk", "Summit lookout"],
    included: ["Guide", "Water", "Trail snacks"],
    itinerary: ["Trail start", "Ridge walk", "Summit", "Descent"],
    faqs: [{ question: "Fitness?", answer: "Moderate — 2–3 hours with inclines." }],
    relatedSlugs: ["malolo-island-resort-snorkel", "malolo-beach-picnic", "snorkelling-crystal-waters"],
  },
  {
    slug: "malolo-beach-picnic",
    title: "Malolo Private Beach Picnic",
    location: "Malolo Island",
    category: "Culture",
    duration: "Half Day",
    ages: "All ages",
    priceFrom: "FJD 195",
    rating: { score: "4.9", count: 89 },
    heroImage: images.picnic,
    overview:
      "Champagne picnic on a private Malolo beach — gourmet hamper, shade pavilion and butler service on powder sand.",
    highlights: ["Private beach", "Gourmet hamper", "Champagne", "Butler service"],
    included: ["Hamper", "Champagne", "Setup", "Transfers"],
    itinerary: ["Beach setup", "Picnic", "Swim time", "Return"],
    faqs: [{ question: "Custom menus?", answer: "Dietary requirements accommodated on request." }],
    relatedSlugs: ["malolo-island-resort-snorkel", "malolo-island-hike", "snorkelling-crystal-waters"],
  },
  {
    slug: "tokoriki-spa-ritual",
    title: "Tokoriki Couples Spa Ritual",
    location: "Tokoriki Island",
    category: "Wellness",
    duration: "3 Hours",
    ages: "18+",
    priceFrom: "FJD 285",
    rating: { score: "4.95", count: 124 },
    heroImage: images.dealSpa,
    overview:
      "Oceanfront couples spa ritual at Tokoriki — Bobo massage, floral bath and champagne on Fiji's most romantic adults-only island.",
    highlights: ["Couples ritual", "Oceanfront pavilion", "Bobo massage", "Champagne"],
    included: ["Spa ritual", "Champagne", "Transfers on island"],
    itinerary: ["Welcome drink", "Massage", "Floral bath", "Relaxation"],
    faqs: [{ question: "Adults only?", answer: "Tokoriki is adults-only; spa guests must be 18+." }],
    relatedSlugs: ["tokoriki-sunset-dinner", "tokoriki-reef-dive", "snorkelling-crystal-waters"],
  },
  {
    slug: "tokoriki-sunset-dinner",
    title: "Tokoriki Private Beach Dinner",
    location: "Tokoriki Island",
    category: "Culture",
    duration: "3 Hours",
    ages: "18+",
    priceFrom: "FJD 350",
    rating: { score: "4.95", count: 98 },
    heroImage: images.dealHoneymoon,
    overview:
      "Candlelit beach dinner for two on Tokoriki — private chef, personal butler and Pacific sunset on white sand.",
    highlights: ["Private chef", "Candlelit setup", "Personal butler", "Sunset views"],
    included: ["Multi-course dinner", "Wine pairing", "Setup", "Butler"],
    itinerary: ["Sunset arrival", "Champagne", "Dinner courses", "Dessert"],
    faqs: [{ question: "Honeymoon?", answer: "Popular for proposals and anniversaries — advise concierge." }],
    relatedSlugs: ["tokoriki-spa-ritual", "tokoriki-reef-dive", "romantic-honeymoon-escape"],
  },
  {
    slug: "tokoriki-reef-dive",
    title: "Tokoriki Reef Discovery Dive",
    location: "Tokoriki Island",
    category: "Water",
    duration: "Half Day",
    ages: "14+",
    priceFrom: "FJD 195",
    rating: { score: "4.8", count: 86 },
    heroImage: images.dealLikuliku,
    overview:
      "Discover scuba on Tokoriki's house reef — PADI intro dive, reef fish and professional instruction in calm lagoon waters.",
    highlights: ["Intro dive", "House reef", "PADI instruction", "Calm lagoon"],
    included: ["Equipment", "Instructor", "Pool session", "Reef dive"],
    itinerary: ["Pool briefing", "Skills", "Reef dive", "Certification option"],
    faqs: [{ question: "No experience?", answer: "Designed for first-time divers; medical form required." }],
    relatedSlugs: ["tokoriki-spa-ritual", "tokoriki-sunset-dinner", "snorkelling-crystal-waters"],
  },
];

export function getExperience(slug: string) {
  return experiences.find((e) => e.slug === slug);
}

export function getExperienceSlugs() {
  return experiences.map((e) => e.slug);
}
