/** AUTO-GENERATED by scripts/hero-video-automation.mjs — do not edit manually */

export const HERO_VIDEO_MANIFEST_META = {
  version: 1,
  generatedAt: "2026-06-16T09:59:51.837Z",
  outputDir: "/assets/hero-videos",
  optimization: {"targetResolution":"1920x1080 max","codec":"source HD (no ffmpeg — install ffmpeg for re-encode)","audio":"removed (hero is muted)","posterFormat":"jpeg preview from Pexels"},
} as const;

export const HOME_HERO_VIDEOS_GENERATED = [
  {
    title: "Overwater luxury resort",
    src: "/assets/hero-videos/fiji-01.mp4",
    poster: "/assets/hero-videos/posters/fiji-01.jpg",
    sourcePage: "https://www.pexels.com/video/aerial-view-of-beautiful-resort-2169880/",
    theme: "Cinematic aerial — overwater villas & turquoise lagoon",
  },
  {
    title: "Premium island resort",
    src: "/assets/hero-videos/fiji-02.mp4",
    poster: "/assets/hero-videos/posters/fiji-02.jpg",
    sourcePage: "https://www.pexels.com/video/5127021/",
    theme: "Sweeping drone over luxury beachfront & emerald water",
  },
  {
    title: "Beachfront luxury escape",
    src: "/assets/hero-videos/fiji-03.mp4",
    poster: "/assets/hero-videos/posters/fiji-03.jpg",
    sourcePage: "https://www.pexels.com/video/aerial-view-of-a-resort-hotel-by-the-beach-9503163/",
    theme: "Aerial resort pools meeting deep Pacific blue",
  },
  {
    title: "Golden tropical coast",
    src: "/assets/hero-videos/fiji-04.mp4",
    poster: "/assets/hero-videos/posters/fiji-04.jpg",
    sourcePage: "https://www.pexels.com/video/3571264/",
    theme: "Warm golden light on sand & teal shallows",
  },
  {
    title: "Emerald lagoon islands",
    src: "/assets/hero-videos/fiji-05.mp4",
    poster: "/assets/hero-videos/posters/fiji-05.jpg",
    sourcePage: "https://www.pexels.com/video/7671125/",
    theme: "Volcanic green islands rising from crystal lagoon",
  }
] as const;
