/** AUTO-GENERATED by scripts/hero-image-automation.mjs — do not edit manually */

export const HERO_IMAGE_MANIFEST_META = {
  version: 2,
  generatedAt: "2026-06-19T12:45:00.000Z",
  outputDir: "/assets/hero-images",
  optimization: {"width":2880,"height":1620,"aspect":"16:9","quality":95,"format":"jpeg","fit":"crop"},
} as const;

export const HOME_HERO_IMAGES_GENERATED = [
  {
    title: "Private sandbar pavilion",
    src: "/assets/hero-images/fiji-00.png",
    alt: "Aerial view of a glass pavilion on a white sandbar in turquoise Fiji lagoon at golden hour",
    theme: "Secluded sandbar retreat — turquoise shallows and deep Pacific blue",
    island: "Fiji Islands",
    objectPosition: "center center",
  },
  {
    title: "Fiji archipelago",
    src: "/assets/hero-images/fiji-01.jpg",
    alt: "Fiji archipelago — Scattered islands in crystal Pacific",
    theme: "Scattered islands in crystal Pacific",
    island: "Fiji Islands",
    objectPosition: "center 42%",
  },
  {
    title: "Reef lagoon",
    src: "/assets/hero-images/fiji-02.jpg",
    alt: "Reef lagoon — Drone over emerald reef channels",
    theme: "Drone over emerald reef channels",
    island: "Yasawa Islands",
    objectPosition: "center 38%",
  },
  {
    title: "Island chain",
    src: "/assets/hero-images/fiji-03.jpg",
    alt: "Island chain — Volcanic peaks rising from blue Pacific",
    theme: "Volcanic peaks rising from blue Pacific",
    island: "Mamanuca Islands",
    objectPosition: "center 36%",
  }
] as const;
