import { HOME_HERO_IMAGES_GENERATED } from "@/lib/hero-images.generated";

/**
 * Fiji-verified image library — every slot = one unique photo ID (site-wide).
 * Generated by scripts/generate-images.mjs — do not hand-edit IDs.
 */
const q = "w=1400&q=90&auto=format";
const qHero = "w=1920&q=92&auto=format&fit=crop";
const qCard = "w=1600&q=92&auto=format&fit=crop";

const u = (id: string, hero = false, card = false) =>
  id.startsWith("/")
    ? id
    : `https://images.unsplash.com/photo-${id}?${hero ? qHero : card ? qCard : q}`;

export const images = {
  heroHome: "/assets/hero-images/fiji-00.jpg",
  heroHomeLegacy: "/hero img.png",
  adventure: u("1700631102725-7194689f7075", false, true),
  luxury: u("1718152219113-5bcfd04f1c7e", false, true),
  family: u("1718152220075-46996d82f65c", false, true),
  wellness: u("1619931325102-08f310801e15", false, true),
  culture: u("1597728221962-143c397d498c", false, true),
  romance: u("1555758897-bdb880473c5c", false, true),
  storyKayak: u("1583297016081-23a9753cd364"),
  experienceSnorkel: u("1656041885868-002ad96abf37", false, true),
  experienceSunsetCruise: u("1649575091574-fe53762ed1eb", false, true),
  experienceHiking: u("1583208107530-c696e0b31578", false, true),
  experienceVillageTour: u("1597152524829-de8cb789172d", false, true),
  snorkel: u("1734343470204-2790c780c8fb"),
  sunset: u("1649575091763-c6e639496f78"),
  hiking: u("1595910825218-c4934349a615"),
  village: u("1700619769449-fc1ca34a2647"),
  picnic: u("1725393325387-07f0d4951528"),
  guideFirstTrip: u("1656071855457-7bdabdd58e7e"),
  guideVisa: u("1764555737101-6c9cf9aea376"),
  guideBestTime: u("1654180680389-4141e2912ef6"),
  guideHealth: u("1756048829869-dabbf82ed79a"),
  guideLuxury: u("1594068049109-675b51ac3c06"),
  guideFlights: u("1776046478783-b9ffb8f496d9"),
  dealsBeachBanner: u("1547077664-16bc77c6a523", true),
  dealResort: u("1558528909-66a2cffd8ce1"),
  dealPool: u("1656042246835-e2fb93fb4a76"),
  dealDenarau: u("1654180714269-9667f416a93f"),
  dealHoneymoon: u("1656483366133-588162e101ef"),
  dealMamanuca: u("1706066954162-d557cc64a163"),
  dealCoralCoast: u("1650010003431-fcd249763cc4"),
  dealOverwater: u("1756048830711-3e69f12ddf74"),
  dealBeach: u("1579264670573-d6d70b68ab4c"),
  dealSpa: u("1654180674774-45dbe0b3bdca"),
  dealPrivateIsland: u("1656072993656-123e27b185f1"),
  dealNadiPackage: u("1654180709575-8d47ae1b2d80"),
  dealLikuliku: u("1579264670617-f91a0831db5f"),
  dealYasawaAdventure: u("1692658330847-f20b9be36cab"),
  dealSharkDive: u("1734343470199-dcef3f2104af"),
  dealSunsetCruise: u("1668565891264-2ffa08a2ce58"),
  heroThingsToDo: u("1583297084116-e420ca5aba80", true),
  heroPlacesToStay: u("1718152220142-1878c0fce8e4", true),
  coralCoast: u("1718152218900-339319bfe82e"),
  coralCoastCard: u("1731317736162-0d067d4ba549"),
  nadi: u("1679966520098-f16132db6f22"),
  nadiCard: u("1730946450226-d15e3bca7877"),
  denarau: u("1700631102571-4f8de88b5a70"),
  denarauCard: u("1648729638732-f444544d1990"),
  mamanuca: u("1559940626-639e49dcbe69"),
  mamanucaCard: u("1692659505534-a1abd5eb4c73"),
  yasawa: u("1730440009900-f91ec0c60612"),
  yasawaCard: u("1683951443218-850f929b65e4"),
  pacificHarbour: u("1731317736062-c9f8c085fe63"),
  pacificHarbourCard: u("1654180639088-65f1bc3312d6"),
  suva: u("1706435689170-7cb06383ea50"),
  suvaCard: u("1449347206122-792f0e389512"),
  taveuniHero: u("1582260627178-67ee302a806f"),
  taveuniCard: u("1543716349-79942dce62c9"),
  surfing: u("1731317736040-e55efb6b06a9"),
  suncoast: u("1543716349-7b4e0d028d70"),
  allPlaces: u("1664016422278-2ce49aac3d0f"),
  islandHop: u("1654180444501-633d033d8923"),
  travelReq: u("1730440010043-78b29d4302be"),
  weather: u("1440561360730-384048528ced"),
  transport: u("1668565858550-61ca2c9eed27"),
  destination: u("1655719647308-7839ce3f0e74"),
  featuredEvent: u("1756450409271-6143eb8375a0"),
  newsletterBoat: u("1579264670602-3f79420f9dc1", true),
  supportIsland: u("1654180717539-c36da10e173a"),
  ctaCoast: u("1654180674739-4151c5e7ee69", true),
  resortPool: u("1619491655385-cc3dc1471431"),
  bure: u("1718152219058-9b7ec5d31671"),
  storyYasawa: u("1718152220104-aa00d9c0b716"),
  storyMamanuca: u("1545986467-13cfe33c156e"),
  storyNadi: u("1579597237873-791c42ac2ff0"),
  storySuva: u("1700809737987-e66be07bc1cf"),
  storyTaveuni: u("1718152219079-df6038b2c411"),
  storyCoralCoast: u("1580211337411-b1c777ea72a4"),
  videoPosterYasawa: u("1731978242386-6bb5b3d862cc"),
  videoPosterMamanuca: u("1668565877909-6a83a1c207a0"),
  videoPosterNadi: u("1598503777149-d6eb22e493f8"),
  videoPosterSuva: u("1545986508-99508351cb07"),
  videoPosterTaveuni: u("1583297112653-9af7d9c2b1b0"),
  videoPosterCoralCoast: u("1731361781110-4569284691b8"),
  videoPosterAbout: u("1584593401421-865fdf856a0f"),
  videoPosterNature: u("1730946483509-5973b21e90ad"),
  resortLikuliku: u("1700619769904-3e2bedeb2c51"),
  resortTokoriki: u("1654180363018-c5a0a308ae02"),
  resortHilton: u("1731978242575-31c0357ec7c8"),
  resortSofitel: u("1730946450247-a09fa58fee94"),
  resortIntercontinental: u("1579264670612-6eb62a173aec"),
  resortCastaway: u("1654180666810-1936b84ab4e3"),
  eventFestival: u("1589770506547-150098706564"),
  eventHibiscus: u("1566263573288-af6b4a37ec8d"),
  eventFirewalking: u("1718152220019-433fbfbc66d4"),
  eventMusic: u("1675955999592-7399e3ce42ec"),
  eventRegatta: u("1568062442124-a5ddb0b82fc6"),
  eventBula: u("1663889442870-c13c86358ae0"),
  eventFood: u("1655719529394-e8a369f30365"),
  eventSailing: u("1781406050681-17bf0f460dff"),
  vanuaLevu: u("1620011059654-1d7caf209797"),
  kadavu: u("1718152220002-6708fe3894a5"),
} as const;

/** Home hero rotation — 6 premium Fiji island stills. Regenerate: npm run hero:images */
export const HOME_HERO_IMAGES = [...HOME_HERO_IMAGES_GENERATED];

/** Legacy slide URLs — 8 unique (local first slide for fast LCP) */
export const HOME_HERO_SLIDES = [
  images.heroHome,
  u("1743356174523-b04efcc66b46", true),
  u("1694604359217-8e992b813d3c", true),
  u("1731978242403-16bf5d103e06", true),
  u("1579597234901-64cfd4ca5d3a", true),
  u("1743356174408-a4d2dd23230e", true),
  u("1668062572949-e45f0269319e", true),
  u("1743356174397-d6da6f014f8f", true),
] as const;

/** Social grid — 12 unique */
export const homeSocialImages = [
  u("1718152220474-706b1ab35183"),
  u("1668062572946-136123620ac1"),
  u("1559636776-41842f840807"),
  u("1700809737677-3a250cbf0954"),
  u("1594067928360-9e9066e1b633"),
  u("1668565867790-82c779d61a2d"),
  u("1654180702510-341074f06b8e"),
  u("1545986467-028b5ab3baca"),
  u("1599311672956-d874f73ac8a8"),
  u("1656132593475-8c711f5b7369"),
  u("1718152220162-9bd888741ea5"),
  u("1718152220115-cbd74b590324"),
] as const;

/** Things-to-do category grid — 32 unique, semantically matched per card title */
export const THINGS_TO_DO_IMAGES = [
  u("1583297016126-171661ade4e5"), // Beqa Lagoon Shark Dive
  u("1718152220111-6e1208d984bc"), // Mamanuca Snorkelling & Kayaking
  u("1756048830256-2717e6c41597"), // Yasawa Scuba Diving
  u("1654180635272-13fc4be2ecf3"), // Navua Rafting, Ziplining & Surf
  u("1651205430581-3b277f44ca34"), // Traditional Fijian Village Tours
  u("1700619769671-83fafd40be79"), // Kava Ceremony Experiences
  u("1718152219095-8f9fc28f5b66"), // Meke Dance Performances
  u("1731978242542-3e2e0585a2a7"), // Suva Municipal Market & Crafts
  u("1414235077428-338989a2e8c0"), // Kokoda — Fiji's Signature Dish
  u("1718152220007-6fb2c02fec95"), // Traditional Lovo Feast
  u("1594068217043-26028fb5b0c8"), // Beachfront Seafood Dining
  u("1731978242562-2dbc589ce5a3"), // Nadi Markets & Resort Dining
  u("1679966519774-bcefa8da9bce"), // Bouma National Heritage Park
  u("1718152219059-130e2b7936d0"), // Tavoro Waterfalls
  u("1730440009654-05bd2dc6c05a"), // Rainbow Reef Coral Gardens
  u("1730440009900-f8988fb5b306"), // Yasawa Blue Lagoons & Marine Reserves
  u("1654180444273-958864814bb4"), // Denarau Family Resorts
  u("1572811227797-5e08bd51e56c"), // Natadola Safe Lagoon Beaches
  u("1730946450176-0d2206dd796b"), // Kula Wild Wildlife Park
  u("1718152220045-4283a8fe5c34"), // Mamanuca Family Island Days
  u("1756048830148-6d3a8c803e4a"), // Sunset Cruises for Couples
  u("1736394543882-457fb15c2add"), // Likuliku Overwater Bures
  u("1718152219044-edc915854e70"), // Private Sandbank Dinners
  u("1718152218906-ae6688d2f22f"), // Turtle Island Honeymoon
  u("1731361781026-7ad35caeb0bb"), // Oceanfront Yoga at Dawn
  u("1731980755566-9c4c65273eb7"), // Traditional Bobo Massage
  u("1683951916403-32dcb8ffaead"), // Luxury Island Spa Retreats
  u("1519253577721-083d740006e5"), // Reef Meditation & Island Relaxation
  u("1579264670616-271de0d18144"), // Mamanuca Island Hopping
  u("1730440010018-01f55450914f"), // Yasawa Flyer Sailing
  u("1731978242394-2cf33f6bd53c"), // Private Yacht Charters
  u("1605923908021-de225858a51e"), // Luxury Catamaran Sunset Sails
] as const;

/** Dev guard — throws if any two slots share the same photo ID */
export function assertUniqueImageSlots() {
  const seen = new Map<string, string>();
  const entries = Object.entries(images) as [string, string][];
  const arrays: [string, readonly string[]][] = [
    ["HOME_HERO_SLIDES", HOME_HERO_SLIDES],
    ["homeSocialImages", homeSocialImages],
    ["THINGS_TO_DO_IMAGES", THINGS_TO_DO_IMAGES],
  ];

  for (const [key, url] of entries) {
    const id = url.includes("photo-") ? url.split("photo-")[1]?.split("?")[0] : url;
    if (seen.has(id)) {
      throw new Error(`Duplicate image: ${key} and ${seen.get(id)} share ${id}`);
    }
    seen.set(id, key);
  }
  for (const [arrName, arr] of arrays) {
    arr.forEach((url, i) => {
      const id = url.includes("photo-") ? url.split("photo-")[1]?.split("?")[0] : url;
      if (seen.has(id)) {
        throw new Error(`Duplicate image: ${arrName}[${i}] shares ${id} with ${seen.get(id)}`);
      }
      seen.set(id, `${arrName}[${i}]`);
    });
  }
}

if (process.env.NODE_ENV === "development") {
  try {
    assertUniqueImageSlots();
  } catch {
    /* logged at build */
  }
}
