import type { WorldCountry, WorldTour } from "./types";
import { countryIndex, getCountryIndex } from "./country-index";

const img = (id: string) =>
  `https://images.unsplash.com/photo-${id}?w=1400&q=85`;

export const showcaseCountries: WorldCountry[] = [
  {
    slug: "fiji",
    name: "Fiji",
    continent: "oceania",
    capital: "Suva",
    lat: -18.141,
    lng: 178.442,
    flag: "🇫🇯",
    featured: true,
    trending: true,
    tagline: "Where bespoke journeys meet barefoot luxury",
    overview:
      "Three hundred islands of turquoise lagoons, volcanic peaks, and warmth that endures — Fiji is the crown jewel of Oceania for discerning travellers.",
    heroImage: img("1507525428034-b723cf961d3e"),
    cardImage: img("1544551763-46a013bb70d5"),
    bestTime: "May – October (dry season)",
    weather: "Tropical, 26–30°C year-round",
    visa: "Visa-free for 120+ nationalities (up to 4 months)",
    currency: "Fijian Dollar (FJD)",
    language: "English, Fijian, Hindi",
    budget: "luxury",
    travelStyles: ["luxury", "beach", "romance", "adventure"],
    landscapes: ["island", "beach", "forest"],
    highlights: ["Private islands", "World-class diving", "Village culture"],
    attractions: ["Mamanuca Islands", "Yasawa Chain", "Coral Coast", "Taveuni"],
    visitCount: 890000,
    relatedSlugs: ["maldives", "french-polynesia", "australia"],
    cities: [
      {
        slug: "nadi",
        countrySlug: "fiji",
        name: "Nadi",
        tagline: "Gateway to the islands",
        lat: -17.799,
        lng: 177.416,
        image: img("1544551763-46a013bb70d5"),
        highlights: ["Denarau Marina", "Garden of the Sleeping Giant"],
        activities: ["Island hopping", "Temple visits", "Golf"],
        luxuryExperiences: ["Private seaplane transfers", "Yacht charters"],
        landmarks: ["Sri Siva Subramaniya Temple"],
      },
      {
        slug: "suva",
        countrySlug: "fiji",
        name: "Suva",
        tagline: "Capital of culture",
        lat: -18.141,
        lng: 178.442,
        image: img("1589394815807-57435a65beb3"),
        highlights: ["Colonial architecture", "Municipal Market"],
        activities: ["Museum tours", "Food markets", "Coastal walks"],
        luxuryExperiences: ["Private cultural immersions"],
        landmarks: ["Fiji Museum", "Thurston Gardens"],
      },
      {
        slug: "mamanuca",
        countrySlug: "fiji",
        name: "Mamanuca Islands",
        tagline: "Iconic lagoon paradise",
        lat: -17.667,
        lng: 177.083,
        image: img("1506905925346-21bda4d32df4"),
        highlights: ["Crystal lagoons", "Overwater bures"],
        activities: ["Snorkelling", "Sunset cruises", "Spa retreats"],
        luxuryExperiences: ["Private island buyouts", "Helicopter transfers"],
        landmarks: ["Monuriki Island", "Castaway Island"],
      },
    ],
  },
  {
    slug: "maldives",
    name: "Maldives",
    continent: "asia",
    capital: "Malé",
    lat: 4.175,
    lng: 73.509,
    flag: "🇲🇻",
    featured: true,
    tagline: "Overwater sanctuaries above the Indian Ocean",
    overview:
      "A constellation of coral atolls where every resort is its own private world — the definitive address for overwater luxury.",
    heroImage: img("1514282401047-d79a71a590e8"),
    cardImage: img("1573843981267-be1999ff37cd"),
    bestTime: "November – April",
    weather: "Tropical, 27–31°C",
    visa: "Visa on arrival (30 days)",
    currency: "Maldivian Rufiyaa (MVR)",
    language: "Dhivehi, English",
    budget: "luxury",
    travelStyles: ["luxury", "beach", "romance"],
    landscapes: ["island", "beach"],
    highlights: ["Overwater villas", "House reefs", "Bioluminescent bays"],
    attractions: ["Baa Atoll UNESCO", "Hanifaru Bay", "Vaadhoo Island"],
    visitCount: 1680000,
    relatedSlugs: ["fiji", "french-polynesia", "thailand"],
    cities: [
      {
        slug: "male",
        countrySlug: "maldives",
        name: "Malé",
        tagline: "The vibrant capital atoll",
        lat: 4.175,
        lng: 73.509,
        image: img("1573843981267-be1999ff37cd"),
        highlights: ["Grand Friday Mosque", "Fish market"],
        activities: ["Island hopping", "Diving", "Spa"],
        luxuryExperiences: ["Private yacht expeditions"],
        landmarks: ["Hukuru Miskiy", "Artificial Beach"],
      },
      {
        slug: "baa-atoll",
        countrySlug: "maldives",
        name: "Baa Atoll",
        tagline: "UNESCO biosphere reserve",
        lat: 5.103,
        lng: 73.07,
        image: img("1514282401047-d79a71a590e8"),
        highlights: ["Manta rays", "Pristine reefs"],
        activities: ["Snorkelling", "Sunset sailing"],
        luxuryExperiences: ["Underwater dining", "Private sandbank picnics"],
        landmarks: ["Hanifaru Bay"],
      },
    ],
  },
  {
    slug: "japan",
    name: "Japan",
    continent: "asia",
    capital: "Tokyo",
    lat: 35.676,
    lng: 139.65,
    flag: "🇯🇵",
    trending: true,
    featured: true,
    tagline: "Ancient soul, futuristic precision",
    overview:
      "From Kyoto's temple gardens to Tokyo's Michelin-starred rooftops — Japan rewards the curious traveller at every turn.",
    heroImage: img("1540959733332-eab4deabeeaf"),
    cardImage: img("1493976040374-85c8e445f1af"),
    bestTime: "March – May, October – November",
    weather: "Four seasons, varied by region",
    visa: "Visa-free for 70+ countries (90 days)",
    currency: "Japanese Yen (JPY)",
    language: "Japanese",
    budget: "mid",
    travelStyles: ["culture", "luxury", "adventure", "family"],
    landscapes: ["city", "mountain", "forest"],
    highlights: ["Cherry blossoms", "Ryokan stays", "Bullet trains"],
    attractions: ["Mount Fuji", "Fushimi Inari", "Arashiyama Bamboo"],
    visitCount: 31800000,
    relatedSlugs: ["south-korea", "thailand", "singapore"],
    cities: [
      {
        slug: "tokyo",
        countrySlug: "japan",
        name: "Tokyo",
        tagline: "Megacity of contrasts",
        lat: 35.676,
        lng: 139.65,
        image: img("1540959733332-eab4deabeeaf"),
        highlights: ["Shibuya", "Ginza", "TeamLab"],
        activities: ["Fine dining", "Temple visits", "Shopping"],
        luxuryExperiences: ["Private kaiseki", "Helicopter city tours"],
        landmarks: ["Senso-ji", "Tokyo Skytree", "Meiji Shrine"],
      },
      {
        slug: "kyoto",
        countrySlug: "japan",
        name: "Kyoto",
        tagline: "Imperial heritage capital",
        lat: 35.011,
        lng: 135.768,
        image: img("1493976040374-85c8e445f1af"),
        highlights: ["Geisha districts", "Zen gardens"],
        activities: ["Tea ceremony", "Temple walks", "Kimono tours"],
        luxuryExperiences: ["Private ryokan", "Garden meditation"],
        landmarks: ["Fushimi Inari", "Kinkaku-ji", "Arashiyama"],
      },
    ],
  },
  {
    slug: "france",
    name: "France",
    continent: "europe",
    capital: "Paris",
    lat: 48.857,
    lng: 2.352,
    flag: "🇫🇷",
    trending: true,
    featured: true,
    tagline: "Art de vivre on a global scale",
    overview:
      "From Parisian haute couture to Provence's lavender fields — France defines European luxury travel.",
    heroImage: img("1502602898657-3e0015ccb509"),
    cardImage: img("1499856871958-5b9627545dca"),
    bestTime: "April – June, September – October",
    weather: "Temperate, regional variation",
    visa: "Schengen visa / visa-free (90 days)",
    currency: "Euro (EUR)",
    language: "French",
    budget: "luxury",
    travelStyles: ["luxury", "culture", "romance"],
    landscapes: ["city", "beach", "mountain"],
    highlights: ["Michelin dining", "Châteaux", "Riviera"],
    attractions: ["Eiffel Tower", "Louvre", "French Riviera"],
    visitCount: 21700000,
    relatedSlugs: ["italy", "spain", "switzerland"],
    cities: [
      {
        slug: "paris",
        countrySlug: "france",
        name: "Paris",
        tagline: "The city of light",
        lat: 48.857,
        lng: 2.352,
        image: img("1502602898657-3e0015ccb509"),
        highlights: ["Museums", "Café culture", "Fashion"],
        activities: ["Gallery tours", "River cruises", "Fine dining"],
        luxuryExperiences: ["Private Louvre tours", "Champagne salons"],
        landmarks: ["Eiffel Tower", "Notre-Dame", "Arc de Triomphe"],
      },
      {
        slug: "nice",
        countrySlug: "france",
        name: "Nice",
        tagline: "Gateway to the Riviera",
        lat: 43.71,
        lng: 7.262,
        image: img("1555881400-74d7acaacd8b"),
        highlights: ["Promenade des Anglais", "Old Town"],
        activities: ["Yacht charters", "Wine tours", "Beach clubs"],
        luxuryExperiences: ["Villa stays", "Private Monaco tours"],
        landmarks: ["Castle Hill", "Cours Saleya Market"],
      },
    ],
  },
  {
    slug: "usa",
    name: "United States",
    continent: "north-america",
    capital: "Washington D.C.",
    lat: 38.907,
    lng: -77.037,
    flag: "🇺🇸",
    trending: true,
    featured: true,
    tagline: "Infinite horizons, iconic experiences",
    overview:
      "From Manhattan skylines to Hawaiian sunsets — the United States offers unmatched geographic diversity.",
    heroImage: img("1485738422979-d7ca8d4ef1dd"),
    cardImage: img("1501594907352-04cda38ebc29"),
    bestTime: "Varies by region",
    weather: "Diverse — tropical to arctic",
    visa: "ESTA / B-2 tourist visa",
    currency: "US Dollar (USD)",
    language: "English",
    budget: "mid",
    travelStyles: ["luxury", "adventure", "family", "culture"],
    landscapes: ["city", "beach", "mountain", "desert", "forest"],
    highlights: ["National parks", "Coastal highways", "World cities"],
    attractions: ["Grand Canyon", "Hawaii", "New York City"],
    visitCount: 51100000,
    relatedSlugs: ["canada", "mexico", "costa-rica"],
    cities: [
      {
        slug: "new-york",
        countrySlug: "usa",
        name: "New York",
        tagline: "The city that never sleeps",
        lat: 40.713,
        lng: -74.006,
        image: img("1485738422979-d7ca8d4ef1dd"),
        highlights: ["Broadway", "Central Park", "Museums"],
        activities: ["Fine dining", "Gallery hopping", "Rooftop bars"],
        luxuryExperiences: ["Private penthouse suites", "Helicopter tours"],
        landmarks: ["Statue of Liberty", "Empire State", "Brooklyn Bridge"],
      },
      {
        slug: "hawaii",
        countrySlug: "usa",
        name: "Hawaii",
        tagline: "Pacific paradise archipelago",
        lat: 21.307,
        lng: -157.858,
        image: img("1507525428034-b723cf961d3e"),
        highlights: ["Volcanoes", "Surf culture", "Luxury resorts"],
        activities: ["Snorkelling", "Hiking", "Luau experiences"],
        luxuryExperiences: ["Private island resorts", "Sunset catamarans"],
        landmarks: ["Waikiki Beach", "Pearl Harbor", "Haleakalā"],
      },
    ],
  },
  {
    slug: "greece",
    name: "Greece",
    continent: "europe",
    capital: "Athens",
    lat: 37.984,
    lng: 23.728,
    flag: "🇬🇷",
    featured: true,
    tagline: "Mythology carved in marble and sea",
    overview:
      "Whitewashed villages cascading into the Aegean — Greece is Europe's most romantic archipelago.",
    heroImage: img("1613395877348-35f3ccf5ec36"),
    cardImage: img("1555993533-5cec00b195d0"),
    bestTime: "April – October",
    weather: "Mediterranean, hot summers",
    visa: "Schengen visa / visa-free (90 days)",
    currency: "Euro (EUR)",
    language: "Greek",
    budget: "mid",
    travelStyles: ["beach", "culture", "romance", "luxury"],
    landscapes: ["island", "beach", "mountain"],
    highlights: ["Santorini sunsets", "Ancient ruins", "Island hopping"],
    attractions: ["Acropolis", "Santorini", "Mykonos", "Crete"],
    visitCount: 31000000,
    relatedSlugs: ["italy", "croatia", "turkey"],
    cities: [
      {
        slug: "athens",
        countrySlug: "greece",
        name: "Athens",
        tagline: "Cradle of civilisation",
        lat: 37.984,
        lng: 23.728,
        image: img("1555993533-5cec00b195d0"),
        highlights: ["Ancient ruins", "Plaka district"],
        activities: ["Museum tours", "Food walks", "Archaeology"],
        luxuryExperiences: ["Private Acropolis tours", "Rooftop dining"],
        landmarks: ["Parthenon", "Acropolis Museum"],
      },
      {
        slug: "santorini",
        countrySlug: "greece",
        name: "Santorini",
        tagline: "Caldera of dreams",
        lat: 36.393,
        lng: 25.461,
        image: img("1613395877348-35f3ccf5ec36"),
        highlights: ["Blue domes", "Volcanic beaches"],
        activities: ["Wine tasting", "Sunset sailing", "Photography"],
        luxuryExperiences: ["Cave pool suites", "Private yacht charters"],
        landmarks: ["Oia", "Fira", "Red Beach"],
      },
    ],
  },
];

export const worldTours: WorldTour[] = [
  { slug: "fiji-island-hop", title: "Fiji Private Island Odyssey", countrySlug: "fiji", image: img("1506905925346-21bda4d32df4"), duration: "10 days", priceFrom: "$8,500", style: "luxury", featured: true },
  { slug: "maldives-overwater", title: "Maldives Overwater Escape", countrySlug: "maldives", image: img("1514282401047-d79a71a590e8"), duration: "7 days", priceFrom: "$12,000", style: "romance", featured: true },
  { slug: "japan-culture", title: "Japan Cultural Immersion", countrySlug: "japan", image: img("1493976040374-85c8e445f1af"), duration: "14 days", priceFrom: "$9,200", style: "culture", featured: true },
  { slug: "greece-islands", title: "Greek Islands Yacht Charter", countrySlug: "greece", image: img("1613395877348-35f3ccf5ec36"), duration: "8 days", priceFrom: "$7,800", style: "luxury" },
  { slug: "morocco-riad", title: "Morocco Imperial Cities", countrySlug: "morocco", image: img("1489749798305-4fea3ae63d6b"), duration: "9 days", priceFrom: "$4,500", style: "culture" },
];

export function getWorldCountry(slug: string): WorldCountry | undefined {
  const full = showcaseCountries.find((c) => c.slug === slug);
  if (full) return full;
  const idx = getCountryIndex(slug);
  if (!idx) return undefined;
  return {
    ...idx,
    tagline: `Discover ${idx.name}`,
    overview: `Explore ${idx.name} — a destination on every discerning traveller's list.`,
    heroImage: `https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1400&q=80`,
    cardImage: `https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&q=80`,
    bestTime: "Varies by region",
    weather: "Check seasonal forecasts",
    visa: "Consult official requirements",
    currency: "Local currency",
    language: "Local language",
    budget: "mid",
    travelStyles: ["culture"],
    landscapes: ["city"],
    highlights: [idx.capital, "Local cuisine", "Cultural sites"],
    attractions: [idx.capital],
    visitCount: 100000,
    cities: [
      {
        slug: idx.capital.toLowerCase().replace(/\s+/g, "-").replace(/\./g, ""),
        countrySlug: idx.slug,
        name: idx.capital,
        tagline: `Capital of ${idx.name}`,
        lat: idx.lat,
        lng: idx.lng,
        image: `https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&q=80`,
        highlights: ["City centre", "Historic quarter"],
        activities: ["Sightseeing", "Local cuisine", "Museums"],
        luxuryExperiences: ["Private guided tours"],
        landmarks: [idx.capital],
      },
    ],
    relatedSlugs: countryIndex.filter((c) => c.continent === idx.continent && c.slug !== slug).slice(0, 3).map((c) => c.slug),
  };
}

export function getWorldCountrySlugs() {
  return countryIndex.map((c) => c.slug);
}

export function getCity(countrySlug: string, citySlug: string) {
  const country = getWorldCountry(countrySlug);
  return country?.cities.find((c) => c.slug === citySlug);
}
