import type {
  AdminNotification,
  Booking,
  ChartPoint,
  ContentItem,
  DashboardMetrics,
  FinanceSummary,
  PlatformUser,
  Settlement,
  Supplier,
  TourListing,
} from "./types";

export const dashboardMetrics: DashboardMetrics = {
  totalRevenue: 2847500,
  monthlyRevenue: 412800,
  revenueChange: 18.4,
  totalBookings: 3847,
  todayBookings: 23,
  bookingsChange: 12.6,
  activeSuppliers: 86,
  totalTravelers: 12450,
  travelersChange: 8.2,
  websiteVisitors: 284000,
  visitorsChange: 22.1,
  conversionRate: 3.8,
  conversionChange: 0.4,
};

export const revenueGrowth: ChartPoint[] = [
  { label: "Jan", value: 198000 },
  { label: "Feb", value: 224000 },
  { label: "Mar", value: 256000 },
  { label: "Apr", value: 289000 },
  { label: "May", value: 312000 },
  { label: "Jun", value: 348000 },
  { label: "Jul", value: 385000 },
  { label: "Aug", value: 412800 },
];

export const dailyVisitors: ChartPoint[] = [
  { label: "Mon", value: 8420 },
  { label: "Tue", value: 9100 },
  { label: "Wed", value: 8750 },
  { label: "Thu", value: 9680 },
  { label: "Fri", value: 11200 },
  { label: "Sat", value: 13400 },
  { label: "Sun", value: 12100 },
];

export const monthlyBookings: ChartPoint[] = [
  { label: "Jan", value: 312 },
  { label: "Feb", value: 348 },
  { label: "Mar", value: 389 },
  { label: "Apr", value: 421 },
  { label: "May", value: 456 },
  { label: "Jun", value: 498 },
  { label: "Jul", value: 512 },
  { label: "Aug", value: 487 },
];

export const topDestinations: ChartPoint[] = [
  { label: "Mamanuca Islands", value: 892 },
  { label: "Yasawa Islands", value: 654 },
  { label: "Coral Coast", value: 521 },
  { label: "Denarau", value: 478 },
  { label: "Taveuni", value: 312 },
  { label: "Nadi", value: 289 },
];

export const topTours: ChartPoint[] = [
  { label: "Sunset Sailing Cruise", value: 234 },
  { label: "Cloud 9 Day Trip", value: 198 },
  { label: "Shark Dive Experience", value: 176 },
  { label: "Island Hopping Package", value: 165 },
  { label: "Nadi Airport Transfer", value: 142 },
];

export const topSuppliersChart: ChartPoint[] = [
  { label: "Pacific Blue Adventures", value: 428000 },
  { label: "Fiji Island Escapes", value: 356000 },
  { label: "Coral Reef Tours", value: 298000 },
  { label: "Bula Transfers", value: 245000 },
  { label: "Yasawa Expeditions", value: 198000 },
];

export const financeSummary: FinanceSummary = {
  totalRevenue: 2847500,
  commissionEarned: 427125,
  supplierEarnings: 2420375,
  pendingSettlements: 68400,
  paidSettlements: 2351975,
  monthlyCommission: 61920,
  avgOrderValue: 740,
};

export const bookings: Booking[] = [
  {
    id: "BK-2026-0847",
    travelerName: "Sarah Mitchell",
    travelerEmail: "sarah.m@email.com",
    tourName: "Sunset Sailing — Mamanuca",
    supplierName: "Pacific Blue Adventures",
    destination: "Mamanuca Islands",
    bookingDate: "2026-06-13T09:24:00Z",
    travelDate: "2026-07-18",
    amount: 890,
    commission: 133.5,
    paymentStatus: "paid",
    bookingStatus: "confirmed",
  },
  {
    id: "BK-2026-0846",
    travelerName: "James Chen",
    travelerEmail: "j.chen@email.com",
    tourName: "Nadi Airport → Denarau Transfer",
    supplierName: "Bula Transfers",
    destination: "Nadi",
    bookingDate: "2026-06-13T08:15:00Z",
    travelDate: "2026-06-20",
    amount: 65,
    commission: 9.75,
    paymentStatus: "paid",
    bookingStatus: "confirmed",
  },
  {
    id: "BK-2026-0845",
    travelerName: "Emma Wilson",
    travelerEmail: "emma.w@email.com",
    tourName: "Cloud 9 Floating Platform",
    supplierName: "Fiji Island Escapes",
    destination: "Mamanuca Islands",
    bookingDate: "2026-06-12T16:42:00Z",
    travelDate: "2026-06-28",
    amount: 420,
    commission: 63,
    paymentStatus: "paid",
    bookingStatus: "completed",
  },
  {
    id: "BK-2026-0844",
    travelerName: "Michael O'Brien",
    travelerEmail: "mobrien@email.com",
    tourName: "Shark Dive — Beqa Lagoon",
    supplierName: "Coral Reef Tours",
    destination: "Coral Coast",
    bookingDate: "2026-06-12T14:30:00Z",
    travelDate: "2026-07-05",
    amount: 1250,
    commission: 187.5,
    paymentStatus: "pending",
    bookingStatus: "pending",
  },
  {
    id: "BK-2026-0843",
    travelerName: "Lisa Nakamura",
    travelerEmail: "l.nakamura@email.com",
    tourName: "Yasawa 3-Day Island Package",
    supplierName: "Yasawa Expeditions",
    destination: "Yasawa Islands",
    bookingDate: "2026-06-12T11:08:00Z",
    travelDate: "2026-08-10",
    amount: 2180,
    commission: 327,
    paymentStatus: "paid",
    bookingStatus: "confirmed",
  },
  {
    id: "BK-2026-0842",
    travelerName: "David Thompson",
    travelerEmail: "d.thompson@email.com",
    tourName: "Private Boat Transfer — Denarau to Tokoriki",
    supplierName: "Pacific Blue Adventures",
    destination: "Mamanuca Islands",
    bookingDate: "2026-06-11T19:55:00Z",
    travelDate: "2026-06-15",
    amount: 340,
    commission: 51,
    paymentStatus: "paid",
    bookingStatus: "completed",
  },
  {
    id: "BK-2026-0841",
    travelerName: "Anna Kowalski",
    travelerEmail: "a.kowalski@email.com",
    tourName: "Sigatoka River Safari",
    supplierName: "Fiji Island Escapes",
    destination: "Coral Coast",
    bookingDate: "2026-06-11T15:22:00Z",
    travelDate: "2026-06-22",
    amount: 185,
    commission: 27.75,
    paymentStatus: "refunded",
    bookingStatus: "refunded",
  },
  {
    id: "BK-2026-0840",
    travelerName: "Robert Hughes",
    travelerEmail: "r.hughes@email.com",
    tourName: "Taveuni Waterfall Hike",
    supplierName: "Coral Reef Tours",
    destination: "Taveuni",
    bookingDate: "2026-06-11T10:45:00Z",
    travelDate: "2026-07-12",
    amount: 295,
    commission: 44.25,
    paymentStatus: "paid",
    bookingStatus: "cancelled",
  },
  {
    id: "BK-2026-0839",
    travelerName: "Sophie Laurent",
    travelerEmail: "s.laurent@email.com",
    tourName: "Denarau Marina Catamaran",
    supplierName: "Pacific Blue Adventures",
    destination: "Denarau",
    bookingDate: "2026-06-10T22:18:00Z",
    travelDate: "2026-06-25",
    amount: 560,
    commission: 84,
    paymentStatus: "paid",
    bookingStatus: "confirmed",
  },
  {
    id: "BK-2026-0838",
    travelerName: "Tom Anderson",
    travelerEmail: "t.anderson@email.com",
    tourName: "Suva City Cultural Tour",
    supplierName: "Bula Transfers",
    destination: "Suva",
    bookingDate: "2026-06-10T18:30:00Z",
    travelDate: "2026-06-18",
    amount: 120,
    commission: 18,
    paymentStatus: "failed",
    bookingStatus: "pending",
  },
];

export const suppliers: Supplier[] = [
  {
    id: "SUP-001",
    name: "Teiva Ratuva",
    company: "Pacific Blue Adventures",
    email: "teiva@pacificblue.fj",
    phone: "+679 999 1234",
    services: ["Tours", "Boat Transfers", "Experiences"],
    status: "verified",
    toursListed: 14,
    totalRevenue: 428000,
    joinedAt: "2024-03-15",
    verified: true,
  },
  {
    id: "SUP-002",
    name: "Maria Santos",
    company: "Fiji Island Escapes",
    email: "maria@fijiisland.fj",
    phone: "+679 888 5678",
    services: ["Tours", "Travel Packages"],
    status: "approved",
    toursListed: 22,
    totalRevenue: 356000,
    joinedAt: "2024-01-08",
    verified: true,
  },
  {
    id: "SUP-003",
    name: "Jonah Naisoro",
    company: "Coral Reef Tours",
    email: "jonah@coralreef.fj",
    phone: "+679 777 9012",
    services: ["Diving", "Snorkelling", "Experiences"],
    status: "verified",
    toursListed: 9,
    totalRevenue: 298000,
    joinedAt: "2024-06-22",
    verified: true,
  },
  {
    id: "SUP-004",
    name: "Priya Sharma",
    company: "Bula Transfers",
    email: "priya@bulatransfers.fj",
    phone: "+679 666 3456",
    services: ["Airport Transfers", "Private Transportation"],
    status: "approved",
    toursListed: 6,
    totalRevenue: 245000,
    joinedAt: "2024-09-10",
    verified: false,
  },
  {
    id: "SUP-005",
    name: "Leo Vaka",
    company: "Yasawa Expeditions",
    email: "leo@yasawaexp.fj",
    phone: "+679 555 7890",
    services: ["Island Packages", "Boat Transfers"],
    status: "pending",
    toursListed: 0,
    totalRevenue: 0,
    joinedAt: "2026-06-01",
    verified: false,
  },
  {
    id: "SUP-006",
    name: "Helen Park",
    company: "Sunset Cruises Fiji",
    email: "helen@sunsetcruises.fj",
    phone: "+679 444 2345",
    services: ["Boat Transfers", "Experiences"],
    status: "suspended",
    toursListed: 3,
    totalRevenue: 42000,
    joinedAt: "2025-02-14",
    verified: false,
  },
  {
    id: "SUP-007",
    name: "Mark Delaney",
    company: "Highland Adventures",
    email: "mark@highland.fj",
    phone: "+679 333 6789",
    services: ["Hiking", "Tours"],
    status: "rejected",
    toursListed: 0,
    totalRevenue: 0,
    joinedAt: "2026-05-20",
    verified: false,
  },
];

export const tours: TourListing[] = [
  {
    id: "TR-001",
    name: "Sunset Sailing — Mamanuca",
    supplierName: "Pacific Blue Adventures",
    destination: "Mamanuca Islands",
    category: "Boat Tour",
    price: 890,
    bookings: 234,
    rating: 4.9,
    status: "featured",
    featured: true,
    updatedAt: "2026-06-10",
  },
  {
    id: "TR-002",
    name: "Cloud 9 Floating Platform",
    supplierName: "Fiji Island Escapes",
    destination: "Mamanuca Islands",
    category: "Experience",
    price: 420,
    bookings: 198,
    rating: 4.8,
    status: "featured",
    featured: true,
    updatedAt: "2026-06-08",
  },
  {
    id: "TR-003",
    name: "Shark Dive — Beqa Lagoon",
    supplierName: "Coral Reef Tours",
    destination: "Coral Coast",
    category: "Diving",
    price: 1250,
    bookings: 176,
    rating: 4.95,
    status: "approved",
    featured: false,
    updatedAt: "2026-06-05",
  },
  {
    id: "TR-004",
    name: "Nadi Airport → Denarau Transfer",
    supplierName: "Bula Transfers",
    destination: "Nadi",
    category: "Airport Transfer",
    price: 65,
    bookings: 142,
    rating: 4.7,
    status: "approved",
    featured: false,
    updatedAt: "2026-06-01",
  },
  {
    id: "TR-005",
    name: "Yasawa 3-Day Island Package",
    supplierName: "Yasawa Expeditions",
    destination: "Yasawa Islands",
    category: "Travel Package",
    price: 2180,
    bookings: 89,
    rating: 4.85,
    status: "pending",
    featured: false,
    updatedAt: "2026-06-12",
  },
  {
    id: "TR-006",
    name: "Sigatoka River Safari",
    supplierName: "Fiji Island Escapes",
    destination: "Coral Coast",
    category: "Tour",
    price: 185,
    bookings: 67,
    rating: 4.6,
    status: "approved",
    featured: false,
    updatedAt: "2026-05-28",
  },
  {
    id: "TR-007",
    name: "Taveuni Waterfall Hike",
    supplierName: "Coral Reef Tours",
    destination: "Taveuni",
    category: "Hiking",
    price: 295,
    bookings: 45,
    rating: 4.75,
    status: "approved",
    featured: false,
    updatedAt: "2026-05-20",
  },
  {
    id: "TR-008",
    name: "Denarau Marina Catamaran",
    supplierName: "Pacific Blue Adventures",
    destination: "Denarau",
    category: "Boat Tour",
    price: 560,
    bookings: 112,
    rating: 4.8,
    status: "approved",
    featured: false,
    updatedAt: "2026-05-15",
  },
];

export const users: PlatformUser[] = [
  {
    id: "USR-1001",
    name: "Sarah Mitchell",
    email: "sarah.m@email.com",
    country: "Australia",
    bookings: 4,
    totalSpent: 3240,
    status: "active",
    joinedAt: "2025-08-12",
    lastActive: "2026-06-13T09:24:00Z",
  },
  {
    id: "USR-1002",
    name: "James Chen",
    email: "j.chen@email.com",
    country: "Singapore",
    bookings: 2,
    totalSpent: 890,
    status: "active",
    joinedAt: "2025-11-03",
    lastActive: "2026-06-13T08:15:00Z",
  },
  {
    id: "USR-1003",
    name: "Emma Wilson",
    email: "emma.w@email.com",
    country: "New Zealand",
    bookings: 6,
    totalSpent: 5680,
    status: "active",
    joinedAt: "2024-12-20",
    lastActive: "2026-06-12T16:42:00Z",
  },
  {
    id: "USR-1004",
    name: "Michael O'Brien",
    email: "mobrien@email.com",
    country: "Ireland",
    bookings: 1,
    totalSpent: 1250,
    status: "active",
    joinedAt: "2026-06-01",
    lastActive: "2026-06-12T14:30:00Z",
  },
  {
    id: "USR-1005",
    name: "Lisa Nakamura",
    email: "l.nakamura@email.com",
    country: "Japan",
    bookings: 3,
    totalSpent: 4820,
    status: "active",
    joinedAt: "2025-04-18",
    lastActive: "2026-06-12T11:08:00Z",
  },
  {
    id: "USR-1006",
    name: "Spam Bot",
    email: "bot@fake.com",
    country: "Unknown",
    bookings: 0,
    totalSpent: 0,
    status: "blocked",
    joinedAt: "2026-05-28",
    lastActive: "2026-05-29T03:00:00Z",
  },
  {
    id: "USR-1007",
    name: "David Thompson",
    email: "d.thompson@email.com",
    country: "USA",
    bookings: 2,
    totalSpent: 680,
    status: "inactive",
    joinedAt: "2025-09-05",
    lastActive: "2026-03-15T10:00:00Z",
  },
];

export const settlements: Settlement[] = [
  {
    id: "STL-2026-06-001",
    supplierName: "Pacific Blue Adventures",
    period: "May 2026",
    grossAmount: 48200,
    commission: 7230,
    netAmount: 40970,
    status: "pending",
    invoiceId: "INV-PA-0526",
    dueDate: "2026-06-20",
  },
  {
    id: "STL-2026-06-002",
    supplierName: "Fiji Island Escapes",
    period: "May 2026",
    grossAmount: 38600,
    commission: 5790,
    netAmount: 32810,
    status: "processing",
    invoiceId: "INV-FI-0526",
    dueDate: "2026-06-20",
  },
  {
    id: "STL-2026-05-001",
    supplierName: "Coral Reef Tours",
    period: "Apr 2026",
    grossAmount: 32100,
    commission: 4815,
    netAmount: 27285,
    status: "paid",
    invoiceId: "INV-CR-0426",
    dueDate: "2026-05-20",
  },
  {
    id: "STL-2026-05-002",
    supplierName: "Bula Transfers",
    period: "Apr 2026",
    grossAmount: 18400,
    commission: 2760,
    netAmount: 15640,
    status: "paid",
    invoiceId: "INV-BT-0426",
    dueDate: "2026-05-20",
  },
  {
    id: "STL-2026-05-003",
    supplierName: "Yasawa Expeditions",
    period: "Apr 2026",
    grossAmount: 12800,
    commission: 1920,
    netAmount: 10880,
    status: "paid",
    invoiceId: "INV-YE-0426",
    dueDate: "2026-05-20",
  },
];

export const notifications: AdminNotification[] = [
  {
    id: "NTF-001",
    type: "booking",
    title: "New booking received",
    message: "Sarah Mitchell booked Sunset Sailing — Mamanuca (FJD 890)",
    createdAt: "2026-06-13T09:24:00Z",
    read: false,
  },
  {
    id: "NTF-002",
    type: "supplier",
    title: "New supplier signup",
    message: "Leo Vaka applied to join as Yasawa Expeditions",
    createdAt: "2026-06-12T14:10:00Z",
    read: false,
  },
  {
    id: "NTF-003",
    type: "tour",
    title: "New tour submission",
    message: "Yasawa 3-Day Island Package pending approval",
    createdAt: "2026-06-12T11:30:00Z",
    read: false,
  },
  {
    id: "NTF-004",
    type: "payment",
    title: "Payment received",
    message: "FJD 2,180 from Lisa Nakamura — Yasawa Package",
    createdAt: "2026-06-12T11:08:00Z",
    read: true,
  },
  {
    id: "NTF-005",
    type: "refund",
    title: "Refund request",
    message: "Anna Kowalski requested refund for Sigatoka River Safari",
    createdAt: "2026-06-11T16:00:00Z",
    read: true,
  },
  {
    id: "NTF-006",
    type: "booking",
    title: "New booking received",
    message: "James Chen booked Nadi Airport Transfer (FJD 65)",
    createdAt: "2026-06-13T08:15:00Z",
    read: false,
  },
];

export const contentItems: ContentItem[] = [
  {
    id: "CNT-001",
    type: "destination",
    title: "Mamanuca Islands",
    status: "published",
    updatedAt: "2026-06-01",
    author: "Admin",
  },
  {
    id: "CNT-002",
    type: "destination",
    title: "Yasawa Islands",
    status: "published",
    updatedAt: "2026-05-28",
    author: "Admin",
  },
  {
    id: "CNT-003",
    type: "guide",
    title: "Best Time to Visit Fiji",
    status: "published",
    updatedAt: "2026-05-20",
    author: "Content Team",
  },
  {
    id: "CNT-004",
    type: "faq",
    title: "Booking & Cancellation Policy",
    status: "published",
    updatedAt: "2026-05-15",
    author: "Admin",
  },
  {
    id: "CNT-005",
    type: "homepage",
    title: "Hero Banner — Summer Campaign",
    status: "scheduled",
    updatedAt: "2026-06-10",
    author: "Marketing",
  },
  {
    id: "CNT-006",
    type: "banner",
    title: "Early Bird Package Promo",
    status: "draft",
    updatedAt: "2026-06-08",
    author: "Marketing",
  },
  {
    id: "CNT-007",
    type: "transport",
    title: "Airport Transfer Guide",
    status: "published",
    updatedAt: "2026-04-22",
    author: "Content Team",
  },
  {
    id: "CNT-008",
    type: "tour",
    title: "Featured Experiences Block",
    status: "published",
    updatedAt: "2026-06-05",
    author: "Admin",
  },
];

export const userStats = {
  total: 12450,
  newThisMonth: 842,
  active: 3890,
  blocked: 23,
};
